//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface AudioMessage : NSObject
{
    _Bool m_isRunning;
    _Bool m_isRecording;
    _Bool m_isPlaying;
    int m_nInSampleRate;
    int m_nInChannels;
    int m_nInFrameSize;
    int m_nOutSampleRate;
    int m_nOutChannels;
    int m_nOutFrameSize;
    char *m_pRecordingBuffer;
    char *m_pPlayingBuffer;
    int m_nRecordingOffset;
    int m_nPlayingOffset;
    int m_CurrentWorkMode;
    int m_WillWorkMode;
    struct OpaqueAudioComponentInstance *m_ioUnit;
    struct AudioStreamBasicDescription m_inputDataFormat;
    struct AudioStreamBasicDescription m_outputDataFormat;
}

- (void)SetDataFormat:(struct AudioStreamBasicDescription *)arg1 SampleRate:(int)arg2 ChannelPerFrame:(int)arg3;
- (void)SetOutputCallback;
- (void)SetInputCallback;
- (void)SetOutputDataFormat;
- (void)SetInputDataFormat;
- (void)SetOutputIOEnable:(_Bool)arg1;
- (void)SetInputIOEnable:(_Bool)arg1;
- (_Bool)StopPlay;
- (_Bool)StartPlay;
- (_Bool)StopRecord;
- (_Bool)StartRecord;
- (void)Uninit;
- (void)Init;

@end

