//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface ConversationHelper : NSObject
{
}

+ (void)setConvAvatarUrl:(scoped_refptr_fd92d7bf)arg1;
+ (void)setConvAvatar:(scoped_refptr_fd92d7bf)arg1;
+ (id)p_getMessageSummary:(const struct Message *)arg1 withWording:(id)arg2 users:(const vector_89e6321f *)arg3 isRoom:(_Bool)arg4;
+ (id)p_parseLinkMessage:(const struct Message *)arg1 withUsers:(const vector_89e6321f *)arg2 isRoom:(_Bool)arg3;
+ (id)p_parseLishiRedEnvelopesMessage:(const struct Message *)arg1 withUsers:(const vector_89e6321f *)arg2 isRoom:(_Bool)arg3;
+ (id)p_parseRedEnvelopesMessage:(const struct Message *)arg1 withUsers:(const vector_89e6321f *)arg2 isRoom:(_Bool)arg3;
+ (id)p_parseWorklogAppMessage:(const struct Message *)arg1;
+ (id)p_parseAppCardMessage:(const struct Message *)arg1 withUsers:(const vector_89e6321f *)arg2 isRoom:(_Bool)arg3;
+ (id)p_parseRecommendNewCorpMessage:(const struct Message *)arg1;
+ (id)p_parsePersonalCardMessage:(const struct Message *)arg1;
+ (id)p_parseAppRichMessage:(const struct Message *)arg1;
+ (id)p_parseTaskCardMessage:(const struct Message *)arg1;
+ (id)p_parseTextCardMessage:(const struct Message *)arg1;
+ (id)p_parseAppNewsMessage:(const struct Message *)arg1;
+ (id)p_parseCardMessage2Text:(const struct Message *)arg1;
+ (id)p_parseCardMessage:(const struct Message *)arg1;
+ (id)p_parseEmotionMessage:(const struct Message *)arg1;
+ (id)p_parseModifyEmailMessage:(const struct Message *)arg1;
+ (id)p_parseRTXTeamMessage:(const struct Message *)arg1 withUsers:(const vector_89e6321f *)arg2 isRoom:(_Bool)arg3;
+ (id)p_parseAdminMessage:(const struct Message *)arg1 withUsers:(const vector_89e6321f *)arg2 isRoom:(_Bool)arg3;
+ (id)p_parseAttendanceMessage:(const struct Message *)arg1 withUsers:(const vector_89e6321f *)arg2 isRoom:(_Bool)arg3;
+ (id)p_parseContentFileMessage:(const struct Message *)arg1 withUsers:(const vector_89e6321f *)arg2 isRoom:(_Bool)arg3;
+ (id)p_parseVideoMessage:(const struct Message *)arg1 withUsers:(const vector_89e6321f *)arg2 isRoom:(_Bool)arg3;
+ (id)p_parseForwardMessage:(const struct Message *)arg1 withUsers:(const vector_89e6321f *)arg2 isRoom:(_Bool)arg3;
+ (id)p_parseRichMessage:(const struct RichMessage *)arg1;
+ (id)p_getRichMessageContent:(const basic_string_a490aa4c *)arg1;
+ (id)p_parseRichMessage:(const struct Message *)arg1 withUsers:(const vector_89e6321f *)arg2 isRoom:(_Bool)arg3;
+ (id)p_sliceUserNames:(const vector_89e6321f *)arg1 withUserIdStr:(const basic_string_a490aa4c *)arg2 exceptUserId:(unsigned long long)arg3;
+ (id)p_sliceUserNames:(const vector_89e6321f *)arg1 withUserIdStr:(const basic_string_a490aa4c *)arg2;
+ (vector_7dcb3552)p_parseUserIdStr:(const basic_string_a490aa4c *)arg1;
+ (id)p_searchUserName:(const vector_89e6321f *)arg1 withUserId:(unsigned long long)arg2 senderName:(const basic_string_a490aa4c *)arg3;
+ (id)p_searchUserName:(const vector_89e6321f *)arg1 withUserId:(unsigned long long)arg2;
+ (id)p_parseMessage:(const struct Message *)arg1 withUsers:(const vector_89e6321f *)arg2 isRoom:(_Bool)arg3;
+ (id)parseForwardMessage:(const struct Message *)arg1 andSearchText:(id)arg2;
+ (id)parseSearchContentWithMessage:(const scoped_refptr_c1fa851d *)arg1 andSearchText:(id)arg2;
+ (id)parseSearchContentWithMessage:(const scoped_refptr_c1fa851d *)arg1;
+ (id)parseRichMessage:(const struct RichMessage *)arg1;
+ (vector_7dcb3552)getUserIdsAtMessage:(const struct Message *)arg1;
+ (void)getConversationsUsers:(const vector_8fc7f2c8 *)arg1 withCallback:(const Callback_2a9a0e8b *)arg2;
+ (void)parseRoomPushMessage:(const scoped_refptr_c1fa851d *)arg1 withCallBack:(const Callback_c63b5ff8 *)arg2;
+ (void)parsePersonPushMessage:(const scoped_refptr_c1fa851d *)arg1 withCallBack:(const Callback_c63b5ff8 *)arg2;
+ (_Bool)isVoiceMessageDeviceAvailable;
+ (_Bool)canSendMessage:(scoped_refptr_fd92d7bf)arg1;
+ (id)p_parsePVMergMultiMsg:(const struct Message *)arg1;
+ (id)parsePVMergMultiMsg:(const struct Message *)arg1;
+ (id)p_parsePVMergSingleMsg:(const struct Message *)arg1;
+ (id)parseHongBaoAckedMessage:(const struct Message *)arg1;
+ (id)parseReceiptNotifyMessage:(const struct Message *)arg1 withUsers:(const vector_89e6321f *)arg2;
+ (void)sortConversationMembersAvatar:(vector_4ea3d2e4 *)arg1 withCreatorId:(unsigned long long)arg2 andLoginUserId:(unsigned long long)arg3;
+ (void)sortConversationMembers:(vector_4ea3d2e4 *)arg1 withCreatorId:(unsigned long long)arg2 andLoginUserId:(unsigned long long)arg3;
+ (id)parseDraftMessage:(const struct Message *)arg1;
+ (id)parseRevokedMessage:(const struct Message *)arg1 withUsers:(const vector_89e6321f *)arg2;
+ (id)parseNotifyMessage:(const struct Message *)arg1 withUsers:(const vector_89e6321f *)arg2;
+ (id)parseConversationLastMessage:(const struct Message *)arg1 withUsers:(const vector_89e6321f *)arg2 convType:(int)arg3;

@end

