//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "FOXMonthCalendarViewDelegate-Protocol.h"
#import "TimePeriodPickerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class CreateEventLogInfo, FOXMonthCalendarViewController, NSDate, NSString, TimePeriodPicker, UIButton, UIControl, UIDatePicker, UILabel, UISegmentedControl, UIView;
@protocol FOXEventDateTimePickerDelegate;

@interface FOXEventDateTimeViewController : UITableViewController <UIScrollViewDelegate, FOXMonthCalendarViewDelegate, TimePeriodPickerDelegate>
{
    UIDatePicker *timePicker;
    TimePeriodPicker *timePeriodPicker;
    _Bool _isSelectedTimePeriod;
    _Bool _showTimerPick;
    UILabel *colonLabel;
    NSDate *curSelDate;
    FOXMonthCalendarViewController *_monthCalendar;
    UIView *headerView;
    UIButton *OKButton;
    UISegmentedControl *segment;
    UILabel *titleLabel;
    UIControl *control;
    UIView *modifyFooterView;
    UIView *footerTopSeperatorLine;
    UIView *footerMiddleSeperatorLine;
    UIButton *deleteButton;
    UIButton *comfirmButton;
    _Bool _isNeedTimePicker;
    CreateEventLogInfo *_logInfo;
    _Bool _isModifyAlertTime;
    _Bool _isNoNeedSetTimeOffset;
    long long _tag;
    id <FOXEventDateTimePickerDelegate> _delegate;
    id _sender;
}

@property(nonatomic) __weak id sender; // @synthesize sender=_sender;
@property(nonatomic) __weak id <FOXEventDateTimePickerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long tag; // @synthesize tag=_tag;
@property(nonatomic) _Bool isNoNeedSetTimeOffset; // @synthesize isNoNeedSetTimeOffset=_isNoNeedSetTimeOffset;
@property(nonatomic) _Bool isModifyAlertTime; // @synthesize isModifyAlertTime=_isModifyAlertTime;
- (void).cxx_destruct;
- (void)setTimePeriod:(int)arg1;
- (void)setTimerPickerDate:(id)arg1;
- (void)setTimerPickerMinInterval:(long long)arg1;
- (void)setTimerPickerMaxDate:(id)arg1;
- (void)setTimerPickerMinDate:(id)arg1;
- (void)willDismissActionView;
- (void)didDismissActionView;
- (void)handleSegmentClick;
- (void)handleTimePickerChanged:(id)arg1;
- (void)selctTimePeriodPickerChanged:(unsigned long long)arg1;
- (void)handleOkButtonClick:(id)arg1;
- (void)initDatePicker:(id)arg1 dateTime:(id)arg2 delegate:(id)arg3 NeedTimePicker:(_Bool)arg4;
- (void)initDatePicker:(id)arg1 dateTime:(id)arg2 delegate:(id)arg3 NeedTimePicker:(_Bool)arg4 isSelectedTimePeriod:(_Bool)arg5 showTimerPick:(_Bool)arg6;
- (void)p_onConfirmButtonClick:(id)arg1;
- (void)p_onDeleteButtonClick:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didMonthCalendarSelected:(long long)arg1 month:(long long)arg2 day:(long long)arg3;
- (void)adjustLittleMonthCalendarViewHeightWithHeight:(float)arg1;
- (void)adjustLittleMonthCalendarViewHeightWithNumOfCells:(long long)arg1;
- (void)setHeaderTitle:(id)arg1;
- (id)dayStrFromDate:(id)arg1;
- (id)strFromDate:(id)arg1;
- (void)updateSegmentTime:(id)arg1;
- (void)updateTitleLabel:(id)arg1;
- (void)updateSegmentDate:(id)arg1;
- (void)initCalendarBody;
- (void)initTimePickerBody;
- (void)renderCustomSegmentUI;
- (void)initCalendarHeaderNeedTimeTitle:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

