//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NativeCodeHandlerBase.h"

#import "WWKForwardingControllerDelegate-Protocol.h"

@class NSString;

@interface JWeixinNativeCodeHandler_saveImage : NativeCodeHandlerBase <WWKForwardingControllerDelegate>
{
    NSString *_qrscanResult;
}

+ (_Bool)requiresPermission;
@property(retain, nonatomic) NSString *qrscanResult; // @synthesize qrscanResult=_qrscanResult;
- (void).cxx_destruct;
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;
- (void)recognizeQRCodeWithResult:(id)arg1;
- (void)shareImageWithData:(id)arg1;
- (void)forwardImageWithPath:(id)arg1 data:(id)arg2;
- (void)favoriteImageWithPath:(id)arg1 data:(id)arg2;
- (void)saveImageWithData:(id)arg1;
- (id)validView;
- (id)validViewController;
- (void)getImagePathWithURL:(id)arg1 orBase64Data:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)getImageDataWithURL:(id)arg1 orBase64Data:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)showActionSheetWithQROption:(_Bool)arg1;
- (void)handleJSCallInNativeCode:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

