//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NativeCodeHandlerBase.h"

#import "WWKForwardingControllerDelegate-Protocol.h"

@class JWeixinCallWrapper, NSString;

@interface JWeixinNativeCodeHandler_shareAppMessage : NativeCodeHandlerBase <WWKForwardingControllerDelegate>
{
    JWeixinCallWrapper *_jWeixinCallWrapper;
}

+ (_Bool)requiresExplicitPermission;
- (void).cxx_destruct;
- (void)didClickCancelButtonInforwardingController:(id)arg1;
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;
- (void)handleJSCallInNativeCode:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

