//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol MailProxyObserverDelegate <NSObject>

@optional
- (void)mailSendProgressDidChange:(struct Mail *)arg1;
- (void)mailSendStateDidChange:(struct Mail *)arg1;
- (void)mail:(struct Mail *)arg1 didChangeAttachmentDownloadProgressAtIndex:(int)arg2;
- (void)mail:(struct Mail *)arg1 didChangeAttachmentDownloadStateAtIndex:(int)arg2;
@end

