//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (ConversationDefaultName)
+ (id)cPlusStringToNSString:(const basic_string_a490aa4c *)arg1;
+ (id)corpCheckInfoWithCorpInfo:(const struct CorpBriefInfo *)arg1 andUser:(const struct User *)arg2;
+ (id)displayNameWithUserId:(unsigned long long)arg1;
+ (id)displayShortCorpNameWithCorpInfo:(const struct CorpBriefInfo *)arg1 otherRID:(unsigned long long)arg2;
+ (id)pstnSysContactDisplayCorpNameWithCorpInfo:(const struct CorpBriefInfo *)arg1;
+ (id)displayCorpNameWithCorpInfo:(const struct CorpBriefInfo *)arg1 otherRID:(unsigned long long)arg2;
+ (id)displayShortCorpNameWithCorpInfo:(const struct CorpBriefInfo *)arg1;
+ (id)displayCorpNameWithCorpInfo:(const struct CorpBriefInfo *)arg1;
+ (id)displayNameWithUser:(const struct User *)arg1;
+ (id)completeNameWithUser:(const struct User *)arg1;
+ (id)nameWithAccountString:(id)arg1;
+ (id)domainWithAccountString:(id)arg1;
+ (id)realNameWithUser:(const struct User *)arg1;
+ (id)waterMakingName:(const struct User *)arg1;
+ (id)chineseNameWithUser:(const struct User *)arg1;
+ (id)englishNameWithUser:(const struct User *)arg1;
+ (id)defaultTitleWithConversation:(const struct Conversation *)arg1;
+ (id)defaultTitleWithConversation:(const struct Conversation *)arg1 withCreatorId:(unsigned long long)arg2 sliceMaxMembersCount:(unsigned int)arg3;
+ (id)defaultTitleWithConversation:(const struct Conversation *)arg1 withCreatorId:(unsigned long long)arg2;
@end

