//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (cardWall)
+ (struct CGContext *)createARGBBitmapContextFromImage:(struct CGImage *)arg1;
+ (id)getRGBDictionaryByColor:(id)arg1;
+ (double)getSumColorfulinImage:(id)arg1;
+ (double)getSumGrayinImage:(id)arg1;
+ (id)getImageFromImage:(id)arg1 withRect:(struct CGRect)arg2;
+ (id)getSubImage:(id)arg1 withRect:(struct CGRect)arg2;
@end

