//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITabBarItem.h>

@interface UITabBarItem (CustomBadge)
- (void)setCircleView:(_Bool)arg1;
- (long long)tabBarCount;
- (void)setCustomBadgeValue:(id)arg1 withFont:(id)arg2 andFontColor:(id)arg3 andBackgroundColor:(id)arg4;
- (void)setMyAppCustomBadgeValue:(id)arg1;
@end

