//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (WWKPreviewDocumentController)
- (_Bool)previewDocumentWithAttachment:(int)arg1 forMail:(scoped_refptr_b418b350)arg2;
- (_Bool)previewDocumentWithFile:(id)arg1 forMessage:(id)arg2 showfav:(_Bool)arg3;
- (_Bool)previewDocumentWithFile:(id)arg1 forMessage:(id)arg2 fromChannel:(long long)arg3 favId:(id)arg4;
- (_Bool)previewDocumentWithFile:(id)arg1 forMessage:(id)arg2 withExtraData:(id)arg3;
- (_Bool)previewDocumentWithFile_CloudDisk:(id)arg1 withCloudObject:(id)arg2 commentNum:(unsigned long long)arg3 withGoCmtBlk:(CDUnknownBlockType)arg4;
- (_Bool)previewDocumentWithFile:(id)arg1 forMessage:(id)arg2;
- (_Bool)previewDocumentWithFile:(id)arg1;
- (_Bool)previewDocumentWithURL:(id)arg1;
@end

