//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VVTableViewDetailTextCell.h"

@class UIImageView;

@interface VVTableViewHeaderImageCell : VVTableViewDetailTextCell
{
    UIImageView *_headerImageView;
}

@property(retain, nonatomic) UIImageView *headerImageView; // @synthesize headerImageView=_headerImageView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setCellData:(id)arg1;
- (void)setupSubviews;

@end

