//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WebviewJSEventHandlerBase.h"

#import "FOXEventDateTimePickerDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "WWKAssetGroupsControllerDelegate-Protocol.h"
#import "WWKForwardingControllerDelegate-Protocol.h"
#import "WWKImageBrowseViewControllerDelegate-Protocol.h"
#import "WWKPickerViewControllerDelegate-Protocol.h"

@class NSString;

@interface WebviewJSEventHandlerUtility : WebviewJSEventHandlerBase <FOXEventDateTimePickerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, WWKImageBrowseViewControllerDelegate, WWKAssetGroupsControllerDelegate, WWKPickerViewControllerDelegate, WWKForwardingControllerDelegate>
{
}

- (void)dealloc;
- (void)handleJSEvent:(id)arg1;
- (void)showWeakTips:(id)arg1 toView:(id)arg2;
- (void)showWeakTips:(id)arg1 toView:(id)arg2 mode:(long long)arg3;
- (void)multiImageBrowseViewControllerWillBack:(id)arg1;
- (void)didCancel;
- (void)didFinishPickPhotos:(id)arg1 isSendOriginalSize:(_Bool)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)updateFrameWithHeight:(float)arg1;
- (void)updateFrameWithNumOfCells:(long long)arg1 andCtrl:(id)arg2;
- (void)didDismissFoxActionView;
- (void)didDateSelected:(id)arg1 dateTime:(id)arg2;
- (void)didDateSelected:(id)arg1 dateTime:(id)arg2 hour:(int)arg3;
- (void)didPickerViewSelectedItemAtIndex:(long long)arg1;
- (id)getNowDateFromatAnDate:(id)arg1;
- (void)uploadImage:(id)arg1 imageKey:(id)arg2 complet:(CDUnknownBlockType)arg3 parentView:(id)arg4;
- (void)doAfterGetDepartmenBack:(scoped_refptr_85c18dd7)arg1 withEvent:(id)arg2;
- (void)doAfterGetDepartmenBack2:(scoped_refptr_85c18dd7)arg1 withEvent:(id)arg2;
- (void)showChooseUserUI:(id)arg1 withDepartment:(const scoped_refptr_85c18dd7 *)arg2 needNavToUp:(_Bool)arg3;
- (void)handleShowListDataDialog:(id)arg1;
- (void)handleShowTips:(id)arg1;
- (void)handleShowAlert:(id)arg1;
- (void)handleLog:(id)arg1;
- (void)didGetUser:(scoped_refptr_e1f85e48)arg1 withEvent:(id)arg2 needNavToUp:(_Bool)arg3;
- (void)handleChooseUser:(id)arg1;
- (void)handleChooseImage:(id)arg1;
- (void)respondQueryRect:(id)arg1;
- (void)handlePreviewImages:(id)arg1;
- (void)handleSelectTime:(id)arg1;
- (void)handleSetClipboard:(id)arg1;
- (void)handleSetWebviewTitle:(id)arg1;
- (void)handleViewBackIsClose:(id)arg1;
- (void)handleClearBrowserHistory:(id)arg1;
- (void)handleGetAppInfo:(id)arg1;
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;
- (void)showBBSWebviewRightMenu:(id)arg1;
- (void)btnFellowbbsMyPublish:(id)arg1;
- (void)btnFellowbbsPublish:(id)arg1;
- (void)showWebviewRightImageMenu:(id)arg1;
- (void)showWebviewRightTextMenu:(id)arg1;
- (void)handleGetSessionKey:(id)arg1;
- (void)handleSendCardMsg:(id)arg1;
- (void)handleShowWebviewRightMenu:(id)arg1;
- (void)handleShowActionMenu:(id)arg1;
- (void)handleNotifyWebviewEvent:(id)arg1;
- (void)handleWebviewDisableBounce:(id)arg1;
- (void)handleCloseWebview:(id)arg1;
- (void)handleGetUserInfo:(id)arg1;
- (void)handleOpenWebview:(id)arg1;
- (void)handleShareToWeixin:(id)arg1;
- (void)handleShowAlertWithInputFiled:(id)arg1;
- (void)handleLishiHongBaoMessage:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

