//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NotificationProxyObserverDelegate-Protocol.h"

@class NSMutableDictionary, WEWCloudObjectEntry;
@protocol WEWFileCloudFolderListFromModelDelegate;

@interface WEWFileCloudFolderListManager : NSObject <NotificationProxyObserverDelegate>
{
    struct scoped_ptr<NotificationProxyObserver, base::DefaultDeleter<NotificationProxyObserver>> _notification_observer;
    _Bool _isNetworkError;
    id <WEWFileCloudFolderListFromModelDelegate> _folderListDelegate;
    WEWCloudObjectEntry *_currentTopFolderInfo;
    unsigned long long _sortType;
    NSMutableDictionary *_topFoldersInfo;
}

+ (id)shareInstance;
@property(retain, nonatomic) NSMutableDictionary *topFoldersInfo; // @synthesize topFoldersInfo=_topFoldersInfo;
@property(nonatomic) _Bool isNetworkError; // @synthesize isNetworkError=_isNetworkError;
@property(nonatomic) unsigned long long sortType; // @synthesize sortType=_sortType;
@property(retain, nonatomic) WEWCloudObjectEntry *currentTopFolderInfo; // @synthesize currentTopFolderInfo=_currentTopFolderInfo;
@property(nonatomic) __weak id <WEWFileCloudFolderListFromModelDelegate> folderListDelegate; // @synthesize folderListDelegate=_folderListDelegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)releaseMemeryCache;
- (id)getErrorInfo:(int)arg1 extra:(_Bool)arg2;
- (_Bool)checkCreateTeamFolder:(id)arg1 membersData:(id)arg2 withSelfVid:(unsigned long long)arg3;
- (_Bool)checkEditTeamFolderMembersData:(id)arg1;
- (id)getAclFromMembers:(id)arg1 withVersion:(unsigned long long)arg2;
- (void)showCreateLaunch:(_Bool)arg1;
- (_Bool)checkShowCreateLaunch;
- (void)reupdateTopFoldersInfoCache:(id)arg1;
- (void)p_checkReachability;
- (void)onNotification:(int)arg1 source:(const struct NotificationSource *)arg2 details:(const struct NotificationDetails *)arg3;
- (void)handleCloudFileUpdatedComeNotification:(id)arg1;
- (void)unregistNotification;
- (void)registNotification;
- (void)closeCloudDisk;
- (id)getTopFolderId;
- (_Bool)checkShowRightNav;
- (_Bool)canRightCreateFolder;
- (_Bool)canRightUploadFolder;
- (_Bool)canRightManageFolder;
- (_Bool)enableRightAuthBtn;
- (void)setTopFolderInfo:(id)arg1;
- (id)uploadExtType;
- (void)GetObjectIdFromNetByObjectId:(id)arg1 topFolder:(id)arg2 withCallback:(CDUnknownBlockType)arg3;
- (void)getForwardMessage:(id)arg1 withCallback:(CDUnknownBlockType)arg2;
- (void)saveObjectsToFavorite:(id)arg1 withCallback:(CDUnknownBlockType)arg2;
- (void)abortUpload:(id)arg1;
- (void)abortDownload:(id)arg1;
- (void)renameTeamFolder:(id)arg1 objectEntry:(id)arg2 acl:(id)arg3 withCallback:(CDUnknownBlockType)arg4;
- (void)renameNormalFolder:(id)arg1 orginalName:(id)arg2 newName:(id)arg3 isFile:(_Bool)arg4 withCallback:(CDUnknownBlockType)arg5;
- (void)deleteFolders:(id)arg1 withCallback:(CDUnknownBlockType)arg2;
- (_Bool)downloadFile:(id)arg1 withCallback:(CDUnknownBlockType)arg2;
- (void)clearObjectSearchCache;
- (id)getTopEntryInfo:(id)arg1 withCallback:(CDUnknownBlockType)arg2;
- (void)searchFolder:(id)arg1 withKeyWords:(id)arg2 withCallback:(CDUnknownBlockType)arg3;
- (_Bool)reUploadFileToFolder:(id)arg1 oldFolder:(id)arg2 withCallback:(CDUnknownBlockType)arg3;
- (_Bool)uploadFileToFolder:(id)arg1 toFolder:(id)arg2 withCallback:(CDUnknownBlockType)arg3;
- (void)modifyCloudDiskObject:(id)arg1 opType:(unsigned long long)arg2 fName:(id)arg3 toFolderId:(id)arg4 acl:(id)arg5 withCallback:(CDUnknownBlockType)arg6;
- (_Bool)createFolderName:(id)arg1 topFolderID:(id)arg2 parentFolderID:(id)arg3 aclList:(id)arg4 withCallback:(CDUnknownBlockType)arg5;
- (void)getFolderListFolderID:(id)arg1 isFromNet:(_Bool)arg2 sortType:(unsigned long long)arg3 withCallback:(CDUnknownBlockType)arg4;
- (id)init;

@end

