//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WWBBSDataChangeNotifyReplyCommentCount : NSObject
{
    unsigned int _replyCommentCount;
    unsigned long long _postId;
    unsigned long long _replyId;
}

@property(nonatomic) unsigned int replyCommentCount; // @synthesize replyCommentCount=_replyCommentCount;
@property(nonatomic) unsigned long long replyId; // @synthesize replyId=_replyId;
@property(nonatomic) unsigned long long postId; // @synthesize postId=_postId;

@end

