//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWCardWallCell.h"

@class UILabel;

@interface WWCardWallAddCommentCell : WWCardWallCell
{
    _Bool _hasComment;
    _Bool _isEditingMode;
    UILabel *_keyLabel;
    UILabel *_addCommentLabel;
}

@property(nonatomic, setter=setEditingMode:) _Bool isEditingMode; // @synthesize isEditingMode=_isEditingMode;
@property(nonatomic, setter=setHasComment:) _Bool hasComment; // @synthesize hasComment=_hasComment;
@property(retain, nonatomic) UILabel *addCommentLabel; // @synthesize addCommentLabel=_addCommentLabel;
@property(retain, nonatomic) UILabel *keyLabel; // @synthesize keyLabel=_keyLabel;
- (void).cxx_destruct;
- (void)updateData;
- (struct CGSize)layoutSubviewsWithWidth:(double)arg1;
- (void)initSubViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

