//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "UISearchBarDelegate-Protocol.h"
#import "VcardServiceProxyObserverDelegate-Protocol.h"
#import "WWKSelectContactsViewControllerDelegate-Protocol.h"

@class NSMutableArray, NSString, UIActivityIndicatorView, UIBarButtonItem, UINavigationItem, UISearchDisplayController, UIView, WWCardWallEmptyView, WWCardWallListSearchController, WWKSearchBar;

@interface WWCardWallListViewController : UITableViewController <VcardServiceProxyObserverDelegate, UISearchBarDelegate, WWKSelectContactsViewControllerDelegate>
{
    struct VcardServiceProxyObserver *_vcardServiceProxyObserver;
    double _oneCardHeight;
    double _headerHeight;
    _Bool _hasHideTableHeaderViewInitial;
    WWKSearchBar *_searchBar;
    UISearchDisplayController *_searchDisplayController;
    WWCardWallListSearchController *_searchController;
    WWCardWallEmptyView *_emptyView;
    UINavigationItem *_topNavigationItem;
    UIBarButtonItem *_backBarButtonItem;
    NSMutableArray *_listDataSource;
    NSMutableArray *_imageArr;
    UIView *_headerCoverView;
    UIActivityIndicatorView *_indicatorView;
    long long _type;
}

@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) _Bool hasHideTableHeaderViewInitial; // @synthesize hasHideTableHeaderViewInitial=_hasHideTableHeaderViewInitial;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) UIView *headerCoverView; // @synthesize headerCoverView=_headerCoverView;
@property(retain, nonatomic) NSMutableArray *imageArr; // @synthesize imageArr=_imageArr;
@property(retain, nonatomic) NSMutableArray *listDataSource; // @synthesize listDataSource=_listDataSource;
@property(retain, nonatomic) UIBarButtonItem *backBarButtonItem; // @synthesize backBarButtonItem=_backBarButtonItem;
@property(retain, nonatomic) UINavigationItem *topNavigationItem; // @synthesize topNavigationItem=_topNavigationItem;
@property(retain, nonatomic) WWCardWallEmptyView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) WWCardWallListSearchController *searchController; // @synthesize searchController=_searchController;
@property(retain, nonatomic) UISearchDisplayController *searchDisplayController; // @synthesize searchDisplayController=_searchDisplayController;
@property(retain, nonatomic) WWKSearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (void)selectContactsViewController:(id)arg1 didConfirmToSelectContacts:(vector_89e6321f)arg2;
- (void)OnSyncStateChanged:(int)arg1 withOldState:(int)arg2;
- (void)OnDeleteBusinessCards:(const vector_4d08d5fa *)arg1;
- (void)OnAddBusinessCards:(const vector_4d08d5fa *)arg1;
- (void)onDidTapMyCardCell:(id)arg1;
- (void)onDidTapCardListCell:(id)arg1;
- (void)scrollToIndexPathWithCardInfo:(const scoped_refptr_bf5b7c69 *)arg1;
- (void)updateNavigationItem:(_Bool)arg1;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (id)sectionIndexTitlesForContentTableView;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)headerView2:(long long)arg1;
- (id)headerView1:(long long)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)islastGroup:(id)arg1;
- (void)stopLoading;
- (void)startLoding;
- (void)gotoScanCard;
- (void)addDidClick;
- (void)p_updateEmptyViewUI;
- (void)viewDidLayoutSubviews;
- (void)p_sortDataSource;
- (void)p_initUI;
- (_Bool)shouldHideTableHeaderViewInitial;
- (void)hideTableHeaderViewInitialIfCanWithAnimated:(_Bool)arg1;
- (void)loadDataSource:(CDUnknownBlockType)arg1;
- (void)fetchLastMyCard:(CDUnknownBlockType)arg1;
- (id)p_getSecionItemWithType:(long long)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;
- (id)initWithType:(long long)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

