//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QMUITextView, UIImageView, UILabel;

@interface WWCardWallManualHeaderContainerView : UIView
{
    UIImageView *_backgroundImage;
    QMUITextView *_corpNameLabel;
    QMUITextView *_nameLabel;
    QMUITextView *_jobLabel;
    UILabel *_mobileLabel;
    UILabel *_telLabel;
    UILabel *_emailLabel;
    UILabel *_addressLabel;
    UILabel *_websiteLabel;
}

@property(retain, nonatomic) UILabel *websiteLabel; // @synthesize websiteLabel=_websiteLabel;
@property(retain, nonatomic) UILabel *addressLabel; // @synthesize addressLabel=_addressLabel;
@property(retain, nonatomic) UILabel *emailLabel; // @synthesize emailLabel=_emailLabel;
@property(retain, nonatomic) UILabel *telLabel; // @synthesize telLabel=_telLabel;
@property(retain, nonatomic) UILabel *mobileLabel; // @synthesize mobileLabel=_mobileLabel;
@property(retain, nonatomic) QMUITextView *jobLabel; // @synthesize jobLabel=_jobLabel;
@property(retain, nonatomic) QMUITextView *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) QMUITextView *corpNameLabel; // @synthesize corpNameLabel=_corpNameLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)initSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

