//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "BusinessCardProxyObserverDelegate-Protocol.h"
#import "WWCardWallCellDelegate-Protocol.h"
#import "WWKForwardingControllerDelegate-Protocol.h"
#import "WWKTableViewDelegate-Protocol.h"

@class MBProgressHUD, NSMutableArray, NSString, NSURL, UIBarButtonItem, UIView, WWCMROCRScanResult, WWCMROCRVCardInfo, WWCardWallDetailTableItem, WWCardWallHeaderInfoView, WWCardWallHeaderMagnifierView, WWCardWallHeaderZoomableView;

@interface WWCardWallDetailViewController : UITableViewController <WWCardWallCellDelegate, WWKForwardingControllerDelegate, BusinessCardProxyObserverDelegate, WWKTableViewDelegate>
{
    struct scoped_ptr<CRTX::GetSharedCardUrlRsp, base::DefaultDeleter<CRTX::GetSharedCardUrlRsp>> _shareInfo;
    CDUnknownBlockType _shareInfoHandler;
    MBProgressHUD *_shareInfoHUD;
    vector_89e6321f _userList;
    scoped_refptr_e1f85e48 _user;
    _Bool _isViewingSharedCard;
    _Bool _isEditingMode;
    WWCardWallHeaderInfoView *_headerInfoView;
    WWCardWallHeaderMagnifierView *_headerMagnifierView;
    WWCardWallHeaderZoomableView *_headerZoomableView;
    WWCMROCRVCardInfo *_info;
    WWCMROCRScanResult *_result;
    NSMutableArray *_data;
    UIView *_viewCardNotifyResponder;
    UIBarButtonItem *_rightBarButtonItem;
    WWCardWallDetailTableItem *_replaceFromAddCommentItem;
    vector_e305eeae _commentVec;
}

@property(readonly, nonatomic) vector_e305eeae commentVec; // @synthesize commentVec=_commentVec;
@property(retain, nonatomic) WWCardWallDetailTableItem *replaceFromAddCommentItem; // @synthesize replaceFromAddCommentItem=_replaceFromAddCommentItem;
@property(retain, nonatomic) UIBarButtonItem *rightBarButtonItem; // @synthesize rightBarButtonItem=_rightBarButtonItem;
@property(nonatomic) __weak UIView *viewCardNotifyResponder; // @synthesize viewCardNotifyResponder=_viewCardNotifyResponder;
@property(nonatomic) _Bool isEditingMode; // @synthesize isEditingMode=_isEditingMode;
@property(nonatomic) _Bool isViewingSharedCard; // @synthesize isViewingSharedCard=_isViewingSharedCard;
@property(retain, nonatomic) NSMutableArray *data; // @synthesize data=_data;
@property(retain, nonatomic) WWCMROCRScanResult *result; // @synthesize result=_result;
@property(retain, nonatomic) WWCMROCRVCardInfo *info; // @synthesize info=_info;
@property(retain, nonatomic) WWCardWallHeaderZoomableView *headerZoomableView; // @synthesize headerZoomableView=_headerZoomableView;
@property(retain, nonatomic) WWCardWallHeaderMagnifierView *headerMagnifierView; // @synthesize headerMagnifierView=_headerMagnifierView;
@property(retain, nonatomic) WWCardWallHeaderInfoView *headerInfoView; // @synthesize headerInfoView=_headerInfoView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)wwkTableViewDidEndTouch;
- (void)OnUpdate:(scoped_refptr_bf5b7c69)arg1;
- (vector_e305eeae)buildCommentDataTest:(vector_e305eeae *)arg1;
- (void)p_sendEmailToReceiver:(id)arg1;
- (void)p_sendEmail:(id)arg1;
- (id)internationalPhoneNum:(id)arg1;
- (void)showMakePhoneAlertWithPhoneNum:(id)arg1;
- (void)makeMobilePhoneCallWithPhoneNum:(id)arg1;
- (void)p_callPhoneNumber:(id)arg1 isMobile:(_Bool)arg2;
- (_Bool)CompareComment:(const struct SharedCardComment *)arg1 And:(const struct SharedCardComment *)arg2;
- (void)DeleteCommentDataSourceWithComment:(const struct SharedCardComment *)arg1;
- (void)UpdateCommentDataSourceWithComment:(const struct SharedCardComment *)arg1;
- (void)deleteComment:(const struct SharedCardComment *)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (void)updateComment:(struct SharedCardComment *)arg1 oldComment:(const struct SharedCardComment *)arg2 withCompletionBlock:(CDUnknownBlockType)arg3;
- (void)repalceTableCommentItemWithAddCommentItem:(id)arg1;
- (void)repalceTableAddCommentItemWithCommentItem;
- (void)storeComment:(struct SharedCardComment *)arg1 withItem:(id)arg2;
- (void)storeDataBcard:(struct BusinessCard *)arg1 andComment:(struct SharedCardComment *)arg2;
- (void)buildDataBcard;
- (_Bool)isMyShareCard;
- (unsigned int)cardImageAngle;
@property(readonly, nonatomic) NSURL *cardImageURL;
- (id)cardImageID;
@property(readonly, nonatomic) struct BusinessCard *card;
@property(readonly, nonatomic) _Bool isBcard;
- (void)respondQueryRect:(id)arg1;
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;
- (void)cardWallCommentCellDidDone:(id)arg1;
- (void)cardWallCellDidGoNextEditingField:(id)arg1;
- (void)cardWallCell:(id)arg1 didUpdateValue:(id)arg2;
- (void)cardWallCell:(id)arg1 reportLayoutHeight:(double)arg2;
- (void)cardWallCellDidEndEditing:(id)arg1;
- (void)cardWallCellDidBeginEditing:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)deleteDidClick:(id)arg1;
- (void)requestShareInfo:(CDUnknownBlockType)arg1;
- (void)shareCardDidClick:(id)arg1;
- (void)shareWechatDidClick:(id)arg1;
- (void)shareWxworkDidClick:(id)arg1;
- (void)viewUserDidClick:(id)arg1;
- (void)viewCardDidClick:(id)arg1;
- (void)moreDidClick:(id)arg1;
- (void)finishDidClick:(id)arg1;
- (void)onClickCancelButton:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)combineCompanyAndTitle;
- (void)updateTableViewRowHeight;
- (id)indexPathForItem:(id)arg1;
- (void)updateData;
- (void)buildData;
- (void)dealloc;
- (id)initWithVcard:(unsigned long long)arg1 fromGid:(unsigned long long)arg2;
- (id)initWithVcard:(id)arg1 OCRResult:(id)arg2;
- (id)initWithVcard:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

