//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKTableViewController.h"

#import "WWCardWallCellDelegate-Protocol.h"
#import "WWCardWallCommentInputToolbarDelegate-Protocol.h"
#import "WWCardWallSelectTagViewDelegate-Protocol.h"
#import "WWKForwardingControllerDelegate-Protocol.h"
#import "WWKPickerViewControllerDelegate-Protocol.h"
#import "WWKTableViewDelegate-Protocol.h"

@class MBProgressHUD, NSMutableArray, NSString, NSURL, UIView, WWCMROCRScanResult, WWCMROCRVCardInfo, WWCardWallCommentInputToolbar, WWCardWallFooterActionView, WWCardWallHeaderInfoView, WWCardWallHeaderMagnifierView, WWCardWallHeaderSummaryView, WWCardWallHeaderZoomableView, WWCardWallManualHeaderView, WWCardWallNavigationbarTitleView, WWCardWallSelectTagView, WWCardWallTableItem, WWKLocationItem;

@interface WWCardWallViewController : WWKTableViewController <WWCardWallCellDelegate, WWKForwardingControllerDelegate, WWCardWallCommentInputToolbarDelegate, WWKTableViewDelegate, WWKPickerViewControllerDelegate, WWCardWallSelectTagViewDelegate>
{
    struct BusinessCardId _cardId;
    struct scoped_ptr<CRTX::GetSharedCardUrlRsp, base::DefaultDeleter<CRTX::GetSharedCardUrlRsp>> _shareInfo;
    CDUnknownBlockType _shareInfoHandler;
    MBProgressHUD *_shareInfoHUD;
    vector_89e6321f _userList;
    scoped_refptr_e1f85e48 _user;
    int _locationState;
    WWKLocationItem *_item;
    struct CGPoint beginDraggingContentOffset;
    struct CGPoint endDraggingContentOffset;
    long long _colorNo;
    struct CGPoint oldOffset;
    _Bool _isViewingSharedCard;
    _Bool _isEditingMode;
    _Bool _isShowAllComment;
    _Bool _canSeeImpression;
    _Bool _isVerticalCardImage;
    _Bool _hasEditing;
    _Bool _isFromScanController;
    _Bool _isFromManual;
    _Bool _isFirstDidAppear;
    _Bool _didShareCard;
    long long _sourceType;
    WWCardWallHeaderInfoView *_headerInfoView;
    WWCardWallHeaderMagnifierView *_headerMagnifierView;
    WWCardWallManualHeaderView *_headerManualView;
    WWCardWallHeaderZoomableView *_headerZoomableView;
    WWCardWallHeaderSummaryView *_headerSummaryView;
    UIView *_headerBackgroundView;
    WWCardWallFooterActionView *_footerActionView;
    WWCMROCRVCardInfo *_info;
    WWCMROCRScanResult *_result;
    WWCardWallCommentInputToolbar *_inputToolbar;
    WWCardWallNavigationbarTitleView *_titleView;
    UIView *_deleteView;
    WWCardWallSelectTagView *_selectTagView;
    NSMutableArray *_data;
    UIView *_viewCardNotifyResponder;
    UIView *_screenView;
    double _verticalCardImageMaxScale;
    UIView *_maskView;
    WWCardWallTableItem *_replaceFromAddCommentItem;
    vector_e305eeae _commentVec;
    struct CGRect _transitionRect;
}

@property(readonly, nonatomic) vector_e305eeae commentVec; // @synthesize commentVec=_commentVec;
@property(retain, nonatomic) WWCardWallTableItem *replaceFromAddCommentItem; // @synthesize replaceFromAddCommentItem=_replaceFromAddCommentItem;
@property(retain, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
@property(nonatomic) _Bool didShareCard; // @synthesize didShareCard=_didShareCard;
@property(nonatomic) _Bool isFirstDidAppear; // @synthesize isFirstDidAppear=_isFirstDidAppear;
@property(nonatomic) _Bool isFromManual; // @synthesize isFromManual=_isFromManual;
@property(nonatomic) _Bool isFromScanController; // @synthesize isFromScanController=_isFromScanController;
@property(nonatomic) _Bool hasEditing; // @synthesize hasEditing=_hasEditing;
@property(nonatomic) double verticalCardImageMaxScale; // @synthesize verticalCardImageMaxScale=_verticalCardImageMaxScale;
@property(nonatomic) _Bool isVerticalCardImage; // @synthesize isVerticalCardImage=_isVerticalCardImage;
@property(retain, nonatomic) UIView *screenView; // @synthesize screenView=_screenView;
@property(nonatomic) struct CGRect transitionRect; // @synthesize transitionRect=_transitionRect;
@property(nonatomic) _Bool canSeeImpression; // @synthesize canSeeImpression=_canSeeImpression;
@property(nonatomic) _Bool isShowAllComment; // @synthesize isShowAllComment=_isShowAllComment;
@property(nonatomic) __weak UIView *viewCardNotifyResponder; // @synthesize viewCardNotifyResponder=_viewCardNotifyResponder;
@property(nonatomic) _Bool isEditingMode; // @synthesize isEditingMode=_isEditingMode;
@property(nonatomic) _Bool isViewingSharedCard; // @synthesize isViewingSharedCard=_isViewingSharedCard;
@property(retain, nonatomic) NSMutableArray *data; // @synthesize data=_data;
@property(retain, nonatomic) WWCardWallSelectTagView *selectTagView; // @synthesize selectTagView=_selectTagView;
@property(retain, nonatomic) UIView *deleteView; // @synthesize deleteView=_deleteView;
@property(retain, nonatomic) WWCardWallNavigationbarTitleView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) WWCardWallCommentInputToolbar *inputToolbar; // @synthesize inputToolbar=_inputToolbar;
@property(retain, nonatomic) WWCMROCRScanResult *result; // @synthesize result=_result;
@property(retain, nonatomic) WWCMROCRVCardInfo *info; // @synthesize info=_info;
@property(retain, nonatomic) WWCardWallFooterActionView *footerActionView; // @synthesize footerActionView=_footerActionView;
@property(retain, nonatomic) UIView *headerBackgroundView; // @synthesize headerBackgroundView=_headerBackgroundView;
@property(retain, nonatomic) WWCardWallHeaderSummaryView *headerSummaryView; // @synthesize headerSummaryView=_headerSummaryView;
@property(retain, nonatomic) WWCardWallHeaderZoomableView *headerZoomableView; // @synthesize headerZoomableView=_headerZoomableView;
@property(retain, nonatomic) WWCardWallManualHeaderView *headerManualView; // @synthesize headerManualView=_headerManualView;
@property(retain, nonatomic) WWCardWallHeaderMagnifierView *headerMagnifierView; // @synthesize headerMagnifierView=_headerMagnifierView;
@property(retain, nonatomic) WWCardWallHeaderInfoView *headerInfoView; // @synthesize headerInfoView=_headerInfoView;
@property(nonatomic) long long sourceType; // @synthesize sourceType=_sourceType;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)SelectTagViewConfirmDidClick:(id)arg1;
- (void)SelectTagViewCancelDidClick;
- (void)didPickerViewSelectedItemAtIndex:(long long)arg1;
- (void)getLocation:(id)arg1 WithBlock:(CDUnknownBlockType)arg2;
- (void)wwkTableViewDidEndTouch;
- (void)requestToSendTextInInputToolbar:(id)arg1;
- (void)updateCardTag:(id)arg1;
- (double)calculateTableViewHeight:(id)arg1;
- (void)keyboardHide:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (_Bool)isOtherShareCard;
- (_Bool)isMyShareCard;
- (basic_string_a490aa4c)p_parseTime:(long long)arg1;
- (_Bool)CompareComment:(const struct SharedCardComment *)arg1 And:(const struct SharedCardComment *)arg2;
- (void)DeleteCommentDataSourceWithComment:(const struct SharedCardComment *)arg1;
- (void)UpdateCommentDataSourceWithComment:(const struct SharedCardComment *)arg1;
- (void)deleteComment:(const struct SharedCardComment *)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (void)createComment:(const struct SharedCardComment *)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (_Bool)isAllCardInfoBlack;
- (void)storeDataBcard:(struct BusinessCard *)arg1;
- (void)buildDataBcard;
@property(readonly, nonatomic) unsigned int cardImageAngle;
@property(readonly, nonatomic) NSURL *cardImageURL;
@property(readonly, nonatomic) NSString *cardImageID;
@property(readonly, nonatomic) struct BusinessCard *card;
@property(readonly, nonatomic) _Bool isBcard;
- (void)p_openUrl:(id)arg1;
- (void)p_sendEmailToReceiver:(id)arg1;
- (void)p_sendEmail:(id)arg1;
- (id)internationalPhoneNum:(id)arg1;
- (void)showMakePhoneAlertWithPhoneNum:(id)arg1;
- (void)makeMobilePhoneCallWithPhoneNum:(id)arg1;
- (void)p_callPhoneNumber:(id)arg1 isMobile:(_Bool)arg2;
- (void)respondQueryRect:(id)arg1;
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;
- (void)moreButtonDidClick:(id)arg1;
- (void)cardWallCommentCellDidDone:(id)arg1;
- (void)cardWallCellDidEndEditing:(id)arg1;
- (void)cardWallCellDidGoNextEditingField:(id)arg1;
- (void)cardWallCell:(id)arg1 didUpdateValue:(id)arg2;
- (void)cardWallCell:(id)arg1 reportLayoutHeight:(double)arg2;
- (void)cardWallCellDidBeginEditing:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 performAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(id)arg3 withSender:(id)arg4;
- (_Bool)tableView:(id)arg1 shouldShowMenuForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)adjustMagnifierViewScale:(id)arg1;
- (_Bool)manualEditMode;
- (void)maskViewWithAnimate:(_Bool)arg1;
- (void)prepareCreateAnimateTransition:(id)arg1;
- (void)animateTransitionForCreateCard;
- (void)animateTransitionToEditCard;
- (void)animateTransitionToViewCard;
- (_Bool)CheckSectionHasSameFeildInfo:(id)arg1 withFeild:(const struct FieldInfo *)arg2;
- (_Bool)CheckCardHasSameFeildInfo:(struct BusinessCard *)arg1 withFeild:(const struct FieldInfo *)arg2;
- (_Bool)checkCStringValueIsBlank:(basic_string_a490aa4c)arg1;
- (_Bool)checkNSStringValueIsBlank:(id)arg1;
- (id)backButtonItem;
- (void)scrollToBottom:(double)arg1;
- (void)scrollToTheBottomUseContentOffset:(double)arg1;
- (void)scrollToTheLastInpression;
- (void)confirmRecommend:(id)arg1;
- (void)addCommentDidClick:(id)arg1;
- (void)doShareCard;
- (void)noShareCard;
- (void)deleteDidClick:(id)arg1;
- (void)requestShareInfo:(CDUnknownBlockType)arg1;
- (void)shareWxworkDidClick:(id)arg1;
- (void)collectionDidClick:(id)arg1;
- (void)addContactDidClick:(id)arg1;
- (void)viewUserDidClick:(id)arg1;
- (void)mailDidClick:(id)arg1;
- (void)phoneDidClick:(id)arg1;
- (void)telDidClick:(id)arg1;
- (void)showCardDidClick:(id)arg1;
- (void)maskViewDidClick:(id)arg1;
- (void)inputToolbarDidClick:(id)arg1;
- (void)viewCardDidClick2:(id)arg1;
- (void)cardDidClick:(id)arg1;
- (void)avatarDidClick:(scoped_refptr_e1f85e48)arg1;
- (void)showAddressDidClick:(id)arg1;
- (void)viewCardDidClick:(id)arg1;
- (void)moreDidClick:(id)arg1;
- (void)showTagPickView;
- (void)uploadImg:(id)arg1 withCallback:(const Callback_346c172f *)arg2;
- (void)delayAnimateTransitionToViewCard;
- (void)finishDidClick:(id)arg1;
- (void)gotoCardWallList:(id)arg1;
- (void)cancelDidClick:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)combineNameAndJob;
- (id)combineCompanyAndTitle;
- (id)combineNameAndCompany;
- (void)updateTableViewRowHeight;
- (id)indexPathForItem:(id)arg1;
- (void)updateActionView;
- (void)updateUserList;
- (void)updateHeaderSummaryViewCollectionView;
- (void)updateVidListButtonShow:(_Bool)arg1;
- (void)updateData;
- (id)firstEditCell;
- (void)buildManualViewData;
- (void)buildData;
- (void)dealloc;
- (id)initWithVcard:(unsigned long long)arg1 fromGid:(unsigned long long)arg2;
- (id)initWithVcard:(id)arg1 OCRResult:(id)arg2 transitionRect:(struct CGRect)arg3;
- (id)initWithVcard:(id)arg1 OCRResult:(id)arg2;
- (id)initWithVcard:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

