//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWCardWallCell.h"

@class UIButton, UILabel;

@interface WWCardWallRecommendCommentCell : WWCardWallCell
{
    UILabel *_recommentLabel;
    UIButton *_button1;
    UIButton *_button2;
    UIButton *_button3;
    UIButton *_button4;
    UIButton *_button5;
    UIButton *_button6;
    UIButton *_confirmButton;
}

@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) UIButton *button6; // @synthesize button6=_button6;
@property(retain, nonatomic) UIButton *button5; // @synthesize button5=_button5;
@property(retain, nonatomic) UIButton *button4; // @synthesize button4=_button4;
@property(retain, nonatomic) UIButton *button3; // @synthesize button3=_button3;
@property(retain, nonatomic) UIButton *button2; // @synthesize button2=_button2;
@property(retain, nonatomic) UIButton *button1; // @synthesize button1=_button1;
@property(retain, nonatomic) UILabel *recommentLabel; // @synthesize recommentLabel=_recommentLabel;
- (void).cxx_destruct;
- (void)confirmRecommend:(id)arg1;
- (void)choose:(id)arg1;
- (struct CGSize)layoutSubviewsWithWidth:(double)arg1;
- (void)updateConfirmButtonState;
- (void)initSubViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

