//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TGLStackedViewController.h"

#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UIActivityIndicatorView, UIBarButtonItem, UINavigationItem, UISearchBar, UITableView, UIView, WWCardWallStackedDataSource, WWCardWallStackedEmptyView;

@interface WWCardWallStackedViewController : TGLStackedViewController <UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate>
{
    WWCardWallStackedDataSource *_dataSource;
    WWCardWallStackedEmptyView *_emptyView;
    UIActivityIndicatorView *_indicatorView;
    UITableView *_searchResultTableView;
    UIView *_searchBarContainerView;
    UISearchBar *_searchBar;
    UINavigationItem *_topNavigationItem;
    UIBarButtonItem *_backBarButtonItem;
    NSMutableArray *_searchCardResult;
    NSMutableArray *_searchCorpResult;
}

@property(retain, nonatomic) NSMutableArray *searchCorpResult; // @synthesize searchCorpResult=_searchCorpResult;
@property(retain, nonatomic) NSMutableArray *searchCardResult; // @synthesize searchCardResult=_searchCardResult;
@property(retain, nonatomic) UIBarButtonItem *backBarButtonItem; // @synthesize backBarButtonItem=_backBarButtonItem;
@property(retain, nonatomic) UINavigationItem *topNavigationItem; // @synthesize topNavigationItem=_topNavigationItem;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) UIView *searchBarContainerView; // @synthesize searchBarContainerView=_searchBarContainerView;
@property(retain, nonatomic) UITableView *searchResultTableView; // @synthesize searchResultTableView=_searchResultTableView;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) WWCardWallStackedEmptyView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) WWCardWallStackedDataSource *dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)keyboardFrameDidChange:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (_Bool)searchBarShouldBeginEditing:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)expandSearchResultDidClick:(id)arg1;
- (void)cancelSearchDidClick:(id)arg1;
- (void)scanDidClick:(id)arg1;
- (void)createDataSource;
- (void)updateNavigationItem:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

