//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface WWCardWallDetailTableItem : NSObject
{
    unsigned long long _type;
    NSString *_value;
    NSString *_key;
    NSString *_subValue;
    unsigned long long _vid;
    struct CGSize _cachedSize;
    struct FieldInfo _fieldInfo;
    struct SharedCardComment _comment;
}

+ (long long)keyboardTypeForType:(unsigned long long)arg1;
+ (unsigned long long)fieldPriority:(unsigned int)arg1;
+ (unsigned int)fieldFromType:(unsigned long long)arg1;
+ (unsigned long long)typeFromField:(unsigned int)arg1;
+ (id)keyFromType:(unsigned long long)arg1;
@property(nonatomic) struct FieldInfo fieldInfo; // @synthesize fieldInfo=_fieldInfo;
@property(nonatomic) struct SharedCardComment comment; // @synthesize comment=_comment;
@property(nonatomic) struct CGSize cachedSize; // @synthesize cachedSize=_cachedSize;
@property unsigned long long vid; // @synthesize vid=_vid;
@property(copy, nonatomic) NSString *subValue; // @synthesize subValue=_subValue;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
@property(copy, nonatomic) NSString *value; // @synthesize value=_value;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)debugDescription;
- (void)saveChanges;
@property(readonly, nonatomic) long long keyboardType;
- (id)initWithType:(unsigned long long)arg1 comment:(const struct SharedCardComment *)arg2;
- (id)initWithType:(unsigned long long)arg1 value:(id)arg2 subvalue:(id)arg3 vid:(unsigned long long)arg4;
- (id)initWithType:(unsigned long long)arg1 fieldInfo:(const struct FieldInfo *)arg2;
- (id)initWithType:(unsigned long long)arg1 key:(id)arg2 value:(id)arg3;
- (id)initWithType:(unsigned long long)arg1 value:(id)arg2;

@end

