//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, WWCardWallCell;

@protocol WWCardWallCellDelegate <NSObject>

@optional
- (void)moreButtonDidClick:(WWCardWallCell *)arg1;
- (void)avatarDidClick:(scoped_refptr_e1f85e48)arg1;
- (void)showAddressDidClick:(NSString *)arg1;
- (void)confirmRecommend:(NSString *)arg1;
- (void)cardWallCommentCellDidDone:(WWCardWallCell *)arg1;
- (void)cardWallCellDidEndEditing:(WWCardWallCell *)arg1;
- (void)cardWallCellDidBeginEditing:(WWCardWallCell *)arg1;
- (void)cardWallCellDidGoNextEditingField:(WWCardWallCell *)arg1;
- (void)cardWallCell:(WWCardWallCell *)arg1 didUpdateValue:(NSString *)arg2;
- (void)cardWallCell:(WWCardWallCell *)arg1 reportLayoutHeight:(double)arg2;
@end

