//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSFastEnumeration-Protocol.h"

@class NSMutableArray;

@interface WWCardWallStackedDataSource : NSObject <NSFastEnumeration>
{
    NSMutableArray *_data;
}

+ (void)createRealDataSourceAsync:(CDUnknownBlockType)arg1;
+ (void)createLocalDataSourceAsync:(CDUnknownBlockType)arg1;
+ (void)createDataSourceAsync:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSMutableArray *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (unsigned long long)count;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;

@end

