//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, UIImage, WWCMROCRProcessor;

@protocol WWCMROCRProcessorDelegate <NSObject>
- (void)processor:(WWCMROCRProcessor *)arg1 wantTurnTorchLightOn:(_Bool)arg2 withCurrentBrightnessValue:(double)arg3;
- (void)processor:(WWCMROCRProcessor *)arg1 analysisDebugWithImg1:(UIImage *)arg2 img2:(UIImage *)arg3 img3:(UIImage *)arg4 img4:(UIImage *)arg5;
- (void)processor:(WWCMROCRProcessor *)arg1 scanUICoverProgressWithCorners:(NSArray *)arg2 imageSize:(struct CGSize)arg3 shouldUpdateCover:(_Bool)arg4 shouldClearCover:(_Bool)arg5;
- (void)processor:(WWCMROCRProcessor *)arg1 scanPhase:(unsigned long long)arg2;
@end

