//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, UIView, WWCMROCRMaskView, WWCMROCRScanner;
@protocol WWCMROCRProcessorDelegate;

@interface WWCMROCRProcessor : NSObject
{
    struct CGSize _pointImgSize;
    NSArray *_cornerArr;
    double _brightnessValue;
    _Bool _isVCardScan;
    _Bool _pauseProcessing;
    _Bool _isUpdatingAnalysis;
    id <WWCMROCRProcessorDelegate> _processDelegate;
    double _lastCaptureTime;
    WWCMROCRScanner *_scanner;
    WWCMROCRMaskView *_weakOCRMaskView;
    UIView *_weakCameraRenderView;
}

+ (id)ocrResultFromUIImage:(id)arg1;
@property(nonatomic) __weak UIView *weakCameraRenderView; // @synthesize weakCameraRenderView=_weakCameraRenderView;
@property(nonatomic) __weak WWCMROCRMaskView *weakOCRMaskView; // @synthesize weakOCRMaskView=_weakOCRMaskView;
@property(retain, nonatomic) WWCMROCRScanner *scanner; // @synthesize scanner=_scanner;
@property double lastCaptureTime; // @synthesize lastCaptureTime=_lastCaptureTime;
@property(nonatomic) _Bool isUpdatingAnalysis; // @synthesize isUpdatingAnalysis=_isUpdatingAnalysis;
@property(nonatomic) _Bool pauseProcessing; // @synthesize pauseProcessing=_pauseProcessing;
@property(nonatomic) __weak id <WWCMROCRProcessorDelegate> processDelegate; // @synthesize processDelegate=_processDelegate;
@property(nonatomic) _Bool isVCardScan; // @synthesize isVCardScan=_isVCardScan;
- (void).cxx_destruct;
- (_Bool)isInVisibleArea:(id)arg1 withSize:(struct CGSize)arg2;
- (id)visibleAreaScaleCorners;
- (void)processImage:(struct Mat *)arg1;
- (void)processCaptureOutPut:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (id)p_genOCRResultFromImage:(id)arg1;
- (id)ted_downSampleImgAndReMappingCornersWithSrcImg:(id)arg1;
- (void)genScanResultFromSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 completed:(CDUnknownBlockType)arg2;
- (id)genScanResultFromSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)p_doInit;
- (id)init;
- (void)dealloc;

@end

