//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MASConstraint, UIActivityIndicatorView, UIButton, UIImageView, UILabel;

@interface WWFavoriteEmptyView : UIView
{
    UILabel *_textLabel;
    UIImageView *_iconView;
    UIView *_containerView;
    UIActivityIndicatorView *_activityIndicator;
    UIButton *_actionButton;
    UILabel *_textButtonInfoLabel;
    MASConstraint *_containerBottom;
}

@property(retain, nonatomic) MASConstraint *containerBottom; // @synthesize containerBottom=_containerBottom;
@property(retain, nonatomic) UILabel *textButtonInfoLabel; // @synthesize textButtonInfoLabel=_textButtonInfoLabel;
@property(retain, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (void).cxx_destruct;
- (void)updateFont;
- (id)initWithActivityIndicatorHeight:(id)arg1 height:(double)arg2;
- (id)initWithActivityIndicator:(id)arg1;
- (void)makeButtonWithBlueStyle;
- (void)setButtonWithTitle:(id)arg1 info:(id)arg2 target:(id)arg3 action:(SEL)arg4;
- (void)setButtonWithTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3;
- (id)initWithIcon:(id)arg1 Title:(id)arg2 autoFit:(_Bool)arg3;

@end

