//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "AVAudioPlayerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WWFavoritesDetailBaseCellViewDelegate-Protocol.h"
#import "WWKForwardingControllerDelegate-Protocol.h"

@class AVAudioPlayer, NSString, WWFavoritesDetailBaseCellView, WWFavoritesDetailFooterCellView, WWFavoritesDetailHeaderCellView, WWFavoritesItem;

@interface WWFavoritesDetailController : UITableViewController <WWKForwardingControllerDelegate, WWFavoritesDetailBaseCellViewDelegate, AVAudioPlayerDelegate, UITableViewDataSource, UITableViewDelegate>
{
    WWFavoritesDetailHeaderCellView *mHeaderCellView;
    WWFavoritesDetailFooterCellView *mFooterCellView;
    WWFavoritesDetailBaseCellView *mContentCellView;
    _Bool _isFavorite;
    AVAudioPlayer *_mVoicePlayer;
    WWFavoritesItem *_mFavItem;
}

@property(retain, nonatomic) WWFavoritesItem *mFavItem; // @synthesize mFavItem=_mFavItem;
@property(retain, nonatomic) AVAudioPlayer *mVoicePlayer; // @synthesize mVoicePlayer=_mVoicePlayer;
@property(nonatomic) _Bool isFavorite; // @synthesize isFavorite=_isFavorite;
- (void).cxx_destruct;
- (void)proximityDidChange:(id)arg1;
- (void)audioPlayerDecodeErrorDidOccur:(id)arg1 error:(id)arg2;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (id)currentPlayingVoice;
- (void)playVoice:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;
- (void)stopVoicePlaying:(_Bool)arg1;
- (void)onMoreBtnClick:(id)arg1;
- (void)initView;
- (void)initNavigationBar;
- (void)deleteFavItemOk:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithFavItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

