//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWFavoritesItemData.h"

@class NSString;

@interface WWFavoritesItemDataVideo : WWFavoritesItemData
{
    unsigned long long _videoByteCount;
    NSString *_videoUrl;
    double _videoDuration;
    double _height;
    double _width;
    NSString *_previewImgUrl;
}

+ (id)createTempVideoPath;
@property(copy, nonatomic) NSString *previewImgUrl; // @synthesize previewImgUrl=_previewImgUrl;
@property(nonatomic) double width; // @synthesize width=_width;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double videoDuration; // @synthesize videoDuration=_videoDuration;
@property(copy, nonatomic) NSString *videoUrl; // @synthesize videoUrl=_videoUrl;
@property(nonatomic) unsigned long long videoByteCount; // @synthesize videoByteCount=_videoByteCount;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *localPath;

@end

