//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKCommonTableViewController.h"

#import "MGSwipeTableCellDelegate-Protocol.h"
#import "WWFavoritesProxyObserverDelegate-Protocol.h"
#import "WWKFavoritesSearchControllerDelegate-Protocol.h"
#import "WWKForwardingControllerDelegate-Protocol.h"

@class NSIndexPath, NSMutableArray, NSMutableDictionary, NSString, WWFavoriteEmptyView, WWFavoritesItemSpaceWarnView, WWKFavoritesSearchController, WWKSearchBar;
@protocol WWFavoritesListSelectDelegate;

@interface WWFavoritesListController : WWKCommonTableViewController <WWFavoritesProxyObserverDelegate, WWKFavoritesSearchControllerDelegate, WWKForwardingControllerDelegate, MGSwipeTableCellDelegate>
{
    NSMutableArray *_mFavDataList;
    struct WWFavoritesProxyObserver *_mFavProxyObserver;
    scoped_refptr_fd92d7bf _curconversation;
    unsigned int _everyLocalIdCount;
    _Bool _isOnSharing;
    _Bool _hasMore;
    _Bool _isDeleteAnimating;
    _Bool _mIsInRefreshList;
    _Bool _mIsLoadingFirstTime;
    _Bool _mIsLoadingMore;
    _Bool _isFirstAppear;
    int _mRefreshListSeq;
    id <WWFavoritesListSelectDelegate> _delegate;
    unsigned long long _mListFromType;
    WWKSearchBar *_searchBar;
    WWKFavoritesSearchController *_mSearchController;
    NSIndexPath *_currentIndex;
    WWFavoritesItemSpaceWarnView *_warnView;
    WWFavoriteEmptyView *_emptyView;
    NSMutableArray *_mHeightArray;
    NSMutableDictionary *_mLocalIdToHeightDic;
}

@property(nonatomic) _Bool isFirstAppear; // @synthesize isFirstAppear=_isFirstAppear;
@property(retain, nonatomic) NSMutableDictionary *mLocalIdToHeightDic; // @synthesize mLocalIdToHeightDic=_mLocalIdToHeightDic;
@property(nonatomic) _Bool mIsLoadingMore; // @synthesize mIsLoadingMore=_mIsLoadingMore;
@property(nonatomic) _Bool mIsLoadingFirstTime; // @synthesize mIsLoadingFirstTime=_mIsLoadingFirstTime;
@property(retain, nonatomic) NSMutableArray *mHeightArray; // @synthesize mHeightArray=_mHeightArray;
@property(nonatomic) int mRefreshListSeq; // @synthesize mRefreshListSeq=_mRefreshListSeq;
@property(nonatomic) _Bool mIsInRefreshList; // @synthesize mIsInRefreshList=_mIsInRefreshList;
@property(nonatomic) _Bool isDeleteAnimating; // @synthesize isDeleteAnimating=_isDeleteAnimating;
@property(retain, nonatomic) WWFavoriteEmptyView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) WWFavoritesItemSpaceWarnView *warnView; // @synthesize warnView=_warnView;
@property(retain, nonatomic) NSIndexPath *currentIndex; // @synthesize currentIndex=_currentIndex;
@property(retain, nonatomic) WWKFavoritesSearchController *mSearchController; // @synthesize mSearchController=_mSearchController;
@property(nonatomic) __weak WWKSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
@property(nonatomic) _Bool isOnSharing; // @synthesize isOnSharing=_isOnSharing;
@property(nonatomic) unsigned long long mListFromType; // @synthesize mListFromType=_mListFromType;
@property(nonatomic) id <WWFavoritesListSelectDelegate> delegate; // @synthesize delegate=_delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onSelectCorpMailFavItem:(id)arg1;
- (void)onSelectPVDocShareFavItem:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)swipeTableCellWillEndSwiping:(id)arg1;
- (void)swipeTableCellWillBeginSwiping:(id)arg1;
- (_Bool)getIsFinishGetServerHistory;
- (void)OnGetServerHistoryFinished;
- (void)OnCollectionUsageChanged;
- (int)reqRefreshListSeq;
- (void)customForwardMessageContentWithFavitem:(id)arg1;
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;
- (_Bool)isCanEditTableView;
- (_Bool)isFavItemValid:(id)arg1;
- (void)onSearchItemController:(id)arg1 didSelectFavItem:(id)arg2;
- (void)OnCollectionFavoriteDataChanged;
- (void)showEmptyUI;
- (void)showLoadingUI;
- (void)showWarningView:(_Bool)arg1 isReloadTable:(_Bool)arg2;
- (void)checkFavoriteDataUsage:(_Bool)arg1;
- (void)delayUpdateServerData;
- (void)didSelectedItem:(id)arg1;
- (void)forwardMessage:(scoped_refptr_c1fa851d)arg1 range:(struct _NSRange)arg2;
- (void)tryLoadMoreData;
- (void)endFooterRefreshing;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)p_forward_favarite:(id)arg1;
- (void)p_delete_favarite:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)onDismissBtnClick:(id)arg1;
- (void)loadData:(unsigned int)arg1 startTime:(unsigned long long)arg2;
- (id)getDataListLastFavItem;
- (void)loadMoreDate;
- (void)safeReloadTable;
- (void)fontSizeChanged;
- (void)updateUI;
- (void)viewDidLoad;
- (void)loadView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)setCurConv:(scoped_refptr_fd92d7bf)arg1;
- (id)initWithListFromType:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

