//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface WWKAttendationBinaryTimeCell2 : UIView
{
    UILabel *_timeLabel;
    UILabel *_recordHintLabel;
    UIView *_topSeperatorLine;
    UIView *_bottomSeperatorLine;
}

+ (_Bool)requiresConstraintBasedLayout;
@property(retain, nonatomic) UIView *bottomSeperatorLine; // @synthesize bottomSeperatorLine=_bottomSeperatorLine;
@property(retain, nonatomic) UIView *topSeperatorLine; // @synthesize topSeperatorLine=_topSeperatorLine;
@property(retain, nonatomic) UILabel *recordHintLabel; // @synthesize recordHintLabel=_recordHintLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
- (void).cxx_destruct;
- (double)timeCellHeight;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

@end

