//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextViewDelegate-Protocol.h"

@class NSString, UILabel, UITextView;

@interface WWKAttendationRandomCheckNoteInfoCellView : UIView <UITextViewDelegate>
{
    _Bool _isReportRemark;
    UITextView *_noteInfoTextView;
    UILabel *_placeHolderLabel;
}

@property(nonatomic) _Bool isReportRemark; // @synthesize isReportRemark=_isReportRemark;
@property(retain, nonatomic) UILabel *placeHolderLabel; // @synthesize placeHolderLabel=_placeHolderLabel;
@property(retain, nonatomic) UITextView *noteInfoTextView; // @synthesize noteInfoTextView=_noteInfoTextView;
- (void).cxx_destruct;
- (double)cellHeight;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (double)p_noteTextViewHeight;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

