//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "WWKAttendationRecordDetailCellViewDelegate-Protocol.h"
#import "WWKForwardingControllerDelegate-Protocol.h"

@class NSString;

@interface WWKAttendationRecordDetailController : UITableViewController <WWKAttendationRecordDetailCellViewDelegate, WWKForwardingControllerDelegate>
{
    scoped_refptr_e21d2ae3 _attendance;
    scoped_refptr_e1f85e48 _senderUser;
    _Bool _isEditable;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (_Bool)p_isMyRecord;
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;
- (void)p_onClickShare:(id)arg1;
- (void)p_showAlertWithSuccess:(_Bool)arg1 tips:(id)arg2;
- (void)p_updateAttendanceWithImageArray:(id)arg1 andText:(id)arg2;
- (void)onDidTapRemarkButton;
- (void)onDidTapImageUrls:(id)arg1 withIndex:(long long)arg2 convertRect:(struct CGRect)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithAttendance:(scoped_refptr_e21d2ae3)arg1 editable:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

