//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel;

@interface WWKAttendationBinaryLocationCell2 : UIView
{
    UIView *bottomSeperatorLine_;
    int _check_exception_state;
    UILabel *_locationDetailLabel;
    UILabel *_locationExceptionLabel;
    UIButton *_reloadButton;
    double _bottomSeperatorLineLeftInset;
    UIImageView *_locationImageView;
}

@property(retain, nonatomic) UIImageView *locationImageView; // @synthesize locationImageView=_locationImageView;
@property(nonatomic) double bottomSeperatorLineLeftInset; // @synthesize bottomSeperatorLineLeftInset=_bottomSeperatorLineLeftInset;
@property(nonatomic) int check_exception_state; // @synthesize check_exception_state=_check_exception_state;
@property(retain, nonatomic) UIButton *reloadButton; // @synthesize reloadButton=_reloadButton;
@property(retain, nonatomic) UILabel *locationExceptionLabel; // @synthesize locationExceptionLabel=_locationExceptionLabel;
@property(retain, nonatomic) UILabel *locationDetailLabel; // @synthesize locationDetailLabel=_locationDetailLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (double)locationCellHeight;
- (id)initWithFrame:(struct CGRect)arg1;

@end

