//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIButton, UIView, WWKApplicationItem;

@interface WWKApplicationPageCollectionCellBase : UICollectionViewCell
{
    _Bool _showRightSepLine;
    _Bool _isEditing;
    WWKApplicationItem *_item;
    UIButton *_containerButton;
    UIView *_bottomSeperatorLine;
    UIView *_rightSeperatorLine;
}

@property(retain, nonatomic) UIView *rightSeperatorLine; // @synthesize rightSeperatorLine=_rightSeperatorLine;
@property(retain, nonatomic) UIView *bottomSeperatorLine; // @synthesize bottomSeperatorLine=_bottomSeperatorLine;
@property(retain, nonatomic) UIButton *containerButton; // @synthesize containerButton=_containerButton;
@property(nonatomic) _Bool isEditing; // @synthesize isEditing=_isEditing;
@property(nonatomic) _Bool showRightSepLine; // @synthesize showRightSepLine=_showRightSepLine;
@property(retain, nonatomic) WWKApplicationItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)p_onCollectionCellDidClicked;
- (id)initWithFrame:(struct CGRect)arg1;

@end

