//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton, UIImageView, UILabel, UIView;
@protocol WWKAnnouncementCellDelegate;

@interface WWKAnnouncementCell : UITableViewCell
{
    scoped_refptr_c1fa851d _message;
    struct AnnounceInfo _announceData;
    _Bool _isShowTime;
    id <WWKAnnouncementCellDelegate> _delegate;
    UIButton *_timeButton;
    UIButton *_containerView;
    UILabel *_nickNameLabel;
    UILabel *_subjectLabel;
    UIView *_seperator1;
    UILabel *_summaryLabel;
    UIImageView *_attachImageView;
    UILabel *_attachCountLabel;
    UIView *_seperator2;
    UIButton *_readFullContentButton;
}

@property(retain, nonatomic) UIButton *readFullContentButton; // @synthesize readFullContentButton=_readFullContentButton;
@property(retain, nonatomic) UIView *seperator2; // @synthesize seperator2=_seperator2;
@property(retain, nonatomic) UILabel *attachCountLabel; // @synthesize attachCountLabel=_attachCountLabel;
@property(retain, nonatomic) UIImageView *attachImageView; // @synthesize attachImageView=_attachImageView;
@property(retain, nonatomic) UILabel *summaryLabel; // @synthesize summaryLabel=_summaryLabel;
@property(retain, nonatomic) UIView *seperator1; // @synthesize seperator1=_seperator1;
@property(retain, nonatomic) UILabel *subjectLabel; // @synthesize subjectLabel=_subjectLabel;
@property(retain, nonatomic) UILabel *nickNameLabel; // @synthesize nickNameLabel=_nickNameLabel;
@property(retain, nonatomic) UIButton *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIButton *timeButton; // @synthesize timeButton=_timeButton;
@property(nonatomic) __weak id <WWKAnnouncementCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isShowTime; // @synthesize isShowTime=_isShowTime;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)p_resetViewsBackgroundColorWithHighlighted:(_Bool)arg1;
- (double)p_getBorderWidth;
- (void)p_updateAttach;
- (void)p_updateSummary;
- (void)p_updateSubject;
- (void)p_updateNickName;
- (void)p_updateTime;
- (void)p_updateUI;
- (struct CGSize)p_layoutSubViewsWithLimitWidth:(double)arg1;
- (double)getHeightWithLimitWidth:(double)arg1;
- (void)onDidTap;
- (void)setContent:(const scoped_refptr_c1fa851d *)arg1;
- (void)layoutSubviews;
- (void)initSubViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

