//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class NSArray, NSMutableArray;
@protocol WWKApplicationOperationTableViewControllerDelegate;

@interface WWKApplicationOperationTableViewController : UITableViewController
{
    id <WWKApplicationOperationTableViewControllerDelegate> _delegate;
    NSArray *_dataList;
    NSMutableArray *_selectedDataList;
    unsigned long long _type;
}

@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSMutableArray *selectedDataList; // @synthesize selectedDataList=_selectedDataList;
@property(copy, nonatomic) NSArray *dataList; // @synthesize dataList=_dataList;
@property(nonatomic) __weak id <WWKApplicationOperationTableViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)p_onClickedDismiss:(id)arg1;
- (void)p_rightNarDidClicked:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLoad;
- (id)initWithDataList:(id)arg1 type:(unsigned long long)arg2;

@end

