//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "CAAnimationDelegate-Protocol.h"

@class NSString, NSTimerProxy, UILabel, WWKAttendanceCheckContainerView_V13, WWKAttendanceFinishResultView, WWKAttendanceNoNeedWorkView, WWKAttendanceResultBottomView, WWKStandardDate;

@interface WWKAttendanceCheckCommonViewController : UIViewController <CAAnimationDelegate>
{
    NSTimerProxy *timeCellRefreshTimeProxy_;
    NSTimerProxy *locationRefreshTimeProxy_;
    WWKAttendanceCheckContainerView_V13 *_containerView;
    WWKAttendanceResultBottomView *_resultBottomView;
    WWKStandardDate *_standardDate;
    WWKAttendanceFinishResultView *_finishResult;
    WWKAttendanceNoNeedWorkView *_nonWorkResultView;
    UILabel *_resultTitleLabel;
}

@property(retain, nonatomic) UILabel *resultTitleLabel; // @synthesize resultTitleLabel=_resultTitleLabel;
@property(retain, nonatomic) WWKAttendanceNoNeedWorkView *nonWorkResultView; // @synthesize nonWorkResultView=_nonWorkResultView;
@property(retain, nonatomic) WWKAttendanceFinishResultView *finishResult; // @synthesize finishResult=_finishResult;
@property(retain, nonatomic) WWKStandardDate *standardDate; // @synthesize standardDate=_standardDate;
@property(retain, nonatomic) WWKAttendanceResultBottomView *resultBottomView; // @synthesize resultBottomView=_resultBottomView;
@property(retain, nonatomic) WWKAttendanceCheckContainerView_V13 *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (void)cm_showNetworkNotAvailableAlert;
- (void)cm_showLocationPermissionClosedAlert;
- (id)cm_findBestLocation:(id)arg1;
- (void)p_onAppWillEnterForeground:(id)arg1;
- (void)p_animationMoveMap;
- (void)cm_handleNonNeedWork;
- (void)cm_handleAllFinish;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)p_animationMoveCheckViewToIcon:(scoped_refptr_e21d2ae3)arg1;
- (void)p_animationBottomResultRise:(scoped_refptr_e21d2ae3)arg1;
- (void)p_prepareResultLabelRise:(scoped_refptr_e21d2ae3)arg1;
- (void)cm_beginAnimation:(scoped_refptr_e21d2ae3)arg1;
- (void)p_onSystemTimeDidChange;
- (void)cm_updateTimeLabel;
- (void)p_onTimeLabelMultiTaped:(id)arg1;
- (_Bool)cm_isNewLocationStrategy;
- (id)cm_getGatewayBSSid;
- (id)cm_getGatewaySSid;
- (basic_string_a490aa4c)cm_getGatewayMacAddress;
- (void)p_onLocationRefreshTimerReached;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) _Bool isInstanceForNotify; // @dynamic isInstanceForNotify;
@property(readonly) Class superclass;

@end

