//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKAttendanceCheckCommonViewController.h"

#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSString, WWKAttendationBreakHintCellView;

@interface WWKAttendanceBinaryCheckViewController : WWKAttendanceCheckCommonViewController <UIImagePickerControllerDelegate, UINavigationControllerDelegate>
{
    struct scoped_ptr<ww_attendance::CacheLocationInfo, base::DefaultDeleter<ww_attendance::CacheLocationInfo>> current_location_info_;
    unsigned long long success_create_checkinid_;
    _Bool _isInstance;
    _Bool _isInstanceForNotify;
    long long _fromType;
    NSString *_checkinId;
    WWKAttendationBreakHintCellView *_breakHintCellView;
    CDUnknownBlockType _imageResultBlock;
    CDUnknownBlockType _imageCancelBlock;
    CDUnknownBlockType _locationBlock;
}

@property(copy, nonatomic) CDUnknownBlockType locationBlock; // @synthesize locationBlock=_locationBlock;
@property(copy, nonatomic) CDUnknownBlockType imageCancelBlock; // @synthesize imageCancelBlock=_imageCancelBlock;
@property(copy, nonatomic) CDUnknownBlockType imageResultBlock; // @synthesize imageResultBlock=_imageResultBlock;
@property(retain, nonatomic) WWKAttendationBreakHintCellView *breakHintCellView; // @synthesize breakHintCellView=_breakHintCellView;
@property(nonatomic) _Bool isInstanceForNotify; // @synthesize isInstanceForNotify=_isInstanceForNotify;
@property(nonatomic) _Bool isInstance; // @synthesize isInstance=_isInstance;
@property(retain, nonatomic) NSString *checkinId; // @synthesize checkinId=_checkinId;
@property(nonatomic) long long fromType; // @synthesize fromType=_fromType;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)p_updateUI_V3_Schedule:(CDUnknownBlockType)arg1;
- (void)p_updateUI_V3_FreeCheck:(scoped_refptr_4757c6a0)arg1 andTodayList:(list_1084d68b *)arg2;
- (void)p_updateUI_V3:(scoped_refptr_4757c6a0)arg1 andTodayList:(list_1084d68b *)arg2 block:(CDUnknownBlockType)arg3;
- (void)p_sortAttendanceRecordByTime_V2:(list_1084d68b *)arg1;
- (unsigned int)p_offWorkSecWithTimeLineID_V2:(unsigned int)arg1 andManageInfo:(scoped_refptr_4757c6a0)arg2;
- (unsigned int)p_nextTimeLineIDWithTimeLineID_V2:(unsigned int)arg1 andManageInfo:(scoped_refptr_4757c6a0)arg2;
- (unsigned int)p_nextTimeLineWorkSecWithTimeLineID_V2:(unsigned int)arg1 andManageInfo:(scoped_refptr_4757c6a0)arg2;
- (unsigned int)p_workSecWithTimeLineID_V2:(unsigned int)arg1 andManageInfo:(scoped_refptr_4757c6a0)arg2;
- (_Bool)p_updateUI_V2NeedOffWork:(const scoped_refptr_4757c6a0 *)arg1 andTodayList:(list_1084d68b *)arg2;
- (_Bool)p_updateUI_V2:(const scoped_refptr_4757c6a0 *)arg1 andTodayList:(list_1084d68b *)arg2;
- (_Bool)p_updateUI_V2NoNeedOffWork:(const scoped_refptr_4757c6a0 *)arg1 andTodayList:(list_1084d68b *)arg2;
- (id)p_configRecordHintisOn:(_Bool)arg1 mintes:(unsigned int)arg2;
- (void)p_configBreakHintCell:(id)arg1;
- (void)p_configFinishAllCheck_V1;
- (_Bool)p_updateUI_V1:(const scoped_refptr_4757c6a0 *)arg1 andTodayList:(const list_1084d68b *)arg2;
- (long long)p_getCurrentBinaryTimeType_V1:(const scoped_refptr_4757c6a0 *)arg1;
- (unsigned int)p_getTodayBinaryCheckStatus_V1:(const list_1084d68b *)arg1;
- (_Bool)p_HandleHoliday:(scoped_refptr_4757c6a0)arg1;
- (void)p_updateDataSource:(CDUnknownBlockType)arg1;
- (void)p_wwkAttendanceItemDidChange:(id)arg1;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)p_makeBinaryCheckWithAttendance:(scoped_refptr_e21d2ae3)arg1;
- (void)p_removeBreakHintCell;
- (void)p_handleAdditionImageAndTextWithAttendance:(scoped_refptr_e21d2ae3)arg1 photoArray:(id)arg2 andTextnote:(id)arg3;
- (void)p_goToConfirm:(scoped_refptr_e21d2ae3)arg1;
- (void)p_handleCreateAttendanceSucess:(scoped_refptr_e21d2ae3)arg1;
- (void)p_handleCreateAttendanceNotSupport:(scoped_refptr_e21d2ae3)arg1;
- (void)p_handleCreateAttendanceError:(scoped_refptr_e21d2ae3)arg1;
- (void)p_handleAheadTimeExcetion:(scoped_refptr_e21d2ae3)arg1 andWording:(const basic_string_a490aa4c *)arg2;
- (void)p_handleWifiExcetion:(scoped_refptr_e21d2ae3)arg1;
- (void)p_handleNoException:(scoped_refptr_e21d2ae3)arg1;
- (void)p_handleNotContinueException:(scoped_refptr_e21d2ae3)arg1 wording:(const basic_string_a490aa4c *)arg2;
- (void)p_handleTimeException:(scoped_refptr_e21d2ae3)arg1;
- (void)p_handleLocationException:(scoped_refptr_e21d2ae3)arg1;
- (void)p_goToReportDetail:(scoped_refptr_e21d2ae3)arg1;
- (void)p_handleExcpetionLogicErrorCode:(int)arg1 excepType:(unsigned int)arg2 attendance:(scoped_refptr_e21d2ae3)arg3 andWording:(basic_string_a490aa4c)arg4;
- (void)p_precheckExceptWithClickButton:(id)arg1;
- (scoped_refptr_e21d2ae3)p_prepareCheckExceptData:(id)arg1;
- (void)p_openCamera:(scoped_refptr_e21d2ae3)arg1;
- (void)p_onDismiss;
- (id)p_instanceCheckinID;
- (void)p_didClickBreakHint;
- (void)p_didClickLocationReloadButton:(id)arg1;
- (void)checkNeedShowInstanceCheck:(CDUnknownBlockType)arg1;
- (void)notifyCheckNeedShowInstanceCheck:(CDUnknownBlockType)arg1;
- (void)cm_handleLocationResult:(unsigned long long)arg1 locations:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)cm_handleUpdateLocationFailed;
- (void)cm_handleClickCheckinButton;
- (void)cm_handleLocationResult:(_Bool)arg1 dataResult:(_Bool)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

