//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface WWKApplicationItem : NSObject
{
    _Bool _isEnable;
    _Bool _isFolder;
    unsigned long long _appId;
    NSString *_iconName;
    NSString *_title;
    NSString *_introduction;
    NSString *_developer;
    NSString *_userUrl;
    NSString *_loginType;
    SEL _action;
    id _target;
    long long _sourceType;
    long long _sectionType;
}

@property(nonatomic) long long sectionType; // @synthesize sectionType=_sectionType;
@property(nonatomic) _Bool isFolder; // @synthesize isFolder=_isFolder;
@property(nonatomic) long long sourceType; // @synthesize sourceType=_sourceType;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic) _Bool isEnable; // @synthesize isEnable=_isEnable;
@property(retain, nonatomic) NSString *loginType; // @synthesize loginType=_loginType;
@property(retain, nonatomic) NSString *userUrl; // @synthesize userUrl=_userUrl;
@property(retain, nonatomic) NSString *developer; // @synthesize developer=_developer;
@property(retain, nonatomic) NSString *introduction; // @synthesize introduction=_introduction;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *iconName; // @synthesize iconName=_iconName;
@property(nonatomic) unsigned long long appId; // @synthesize appId=_appId;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long displayOrder;
- (id)initWithBusinessId:(unsigned long long)arg1;

@end

