//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "AppointmentServiceProxyObserverDelegate-Protocol.h"
#import "NotificationProxyObserverDelegate-Protocol.h"
#import "SPTableViewCustomEditingViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "VcardServiceProxyObserverDelegate-Protocol.h"
#import "WWKAppointmentListControllerDelegate-Protocol.h"
#import "WWKWorkLogViewControllerDelegate-Protocol.h"

@class NSMutableArray, NSString, UITableView, UIView, WWKApplicationEmptyPageView;

@interface WWKApplicationPageController : UIViewController <UITableViewDataSource, UITableViewDelegate, NotificationProxyObserverDelegate, AppointmentServiceProxyObserverDelegate, WWKAppointmentListControllerDelegate, SPTableViewCustomEditingViewDelegate, VcardServiceProxyObserverDelegate, WWKWorkLogViewControllerDelegate>
{
    UITableView *_tableView;
    WWKApplicationEmptyPageView *_emptyPageView;
    UIView *_topBackgroundView;
    NSMutableArray *_applist;
    struct scoped_ptr<NotificationProxyObserver, base::DefaultDeleter<NotificationProxyObserver>> push_notification_observer;
    struct scoped_ptr<AppointmentServiceProxyObserver, base::DefaultDeleter<AppointmentServiceProxyObserver>> _appointmentServiceProxyObserver;
    struct VcardServiceProxyObserver *_vcardServiceProxyObserver;
    _Bool _showFolderApp;
    _Bool _isEditMode;
    _Bool _isAnimate;
    CDUnknownBlockType _swipeActionCallBack;
    NSMutableArray *_folderAppIds;
    NSMutableArray *_totalApps;
}

+ (id)createAppItemWithDefaultApp:(const struct DefaultApplication *)arg1;
+ (void)pushToMailApp:(id)arg1 withDefaultApp:(const struct DefaultApplication *)arg2 hideBottomBar:(_Bool)arg3 backTo:(Class)arg4;
+ (void)push:(id)arg1 withDefaultApp:(const struct DefaultApplication *)arg2 hideBottomBar:(_Bool)arg3;
@property(nonatomic) _Bool isAnimate; // @synthesize isAnimate=_isAnimate;
@property(nonatomic) _Bool isEditMode; // @synthesize isEditMode=_isEditMode;
@property(retain, nonatomic) NSMutableArray *totalApps; // @synthesize totalApps=_totalApps;
@property(retain, nonatomic) NSMutableArray *folderAppIds; // @synthesize folderAppIds=_folderAppIds;
@property(copy, nonatomic) CDUnknownBlockType swipeActionCallBack; // @synthesize swipeActionCallBack=_swipeActionCallBack;
@property(nonatomic) _Bool showFolderApp; // @synthesize showFolderApp=_showFolderApp;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)WorkLogViewController:(id)arg1 didPublishPost:(const struct JournalEntry *)arg2;
- (void)OnVCardUnReadCountChanged:(unsigned int)arg1 withOldCount:(unsigned int)arg2;
- (void)OnVCardTotalCountChanged:(unsigned int)arg1 withOldCount:(unsigned int)arg2;
- (void)onAppointMessageTipsClear;
- (void)OnNotifyUpdateAppointment:(const vector_0d9de00b *)arg1;
- (void)OnNotifyAppendAppointment:(const vector_0d9de00b *)arg1;
- (void)p_swipeEditIndexPath:(id)arg1;
- (void)p_editCell:(id)arg1;
- (long long)p_getDefaultAppOrderWithID:(unsigned long long)arg1;
- (void)sortAppList;
- (void)sortApps:(id)arg1;
- (void)onFinish;
- (void)changeDataWithAnimate:(_Bool)arg1;
- (void)onCancel;
- (void)showOrHideApp;
- (id)footerTextWithSection:(long long)arg1;
- (void)navigation:(id)arg1 pushToViewController:(id)arg2;
- (void)exposeRedPointReport;
- (void)checkParentCellRedPoint;
- (id)redPointKeysWithItem:(id)arg1;
- (void)p_swipeIndexPath:(id)arg1;
- (_Bool)p_openApiItemshouldShow:(struct WSCorpAppDetail)arg1;
- (id)p_createAppSectionItemWithType:(long long)arg1;
- (long long)p_getAppSectionItemPositionWithType:(long long)arg1;
- (id)p_getAppSectionItemWithType:(long long)arg1;
- (id)p_createAppItemWithOpenApiApp:(const struct WSCorpAppDetail *)arg1;
- (id)p_createAppItemWithThirdApp:(const struct ThirdApplication *)arg1;
- (id)p_createAppItemWithDefaultApp:(const struct DefaultApplication *)arg1;
- (void)p_pushModifyMailController;
- (void)onNotification:(int)arg1 source:(const struct NotificationSource *)arg2 details:(const struct NotificationDetails *)arg3;
- (void)updateUI;
- (void)onDynamicFontSizeDidChange;
- (void)onDidPushCardWallController:(id)arg1;
- (void)onDidPushForumController:(id)arg1;
- (void)onDidPushMoreAppController:(id)arg1;
- (void)onDidPushVirtualMoreAppController:(id)arg1;
- (void)onDidPushAppointAppController:(id)arg1;
- (void)onDidPushOpenApiApp:(id)arg1;
- (void)onDidPushApplicationBriefController:(id)arg1;
- (void)onDidPushApplicationBriefController:(id)arg1 navi:(id)arg2;
- (void)onDidPushThirdApp:(id)arg1;
- (void)onDidPushEnterpriseMailController:(id)arg1;
- (void)onDidPstnCallLogListController:(id)arg1;
- (void)onDidPushCloudDiskController:(id)arg1;
- (void)onDidPushAttendanceController:(id)arg1;
- (void)onDidPushAnnouncementListCtroller:(id)arg1;
- (void)onDidPushExpenseCtroller:(id)arg1;
- (void)onDidPushAskForLeaveCtroller:(id)arg1;
- (void)onDidPushWorkLogController:(id)arg1;
- (void)onDidPushApprovalCtroller:(id)arg1;
- (void)onDidPushWechatCustomServiceCtroller:(id)arg1;
- (void)onNotification:(id)arg1;
- (id)tableView:(id)arg1 editingViewForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 editActionsForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)folderAppsIdSaveKey;
- (id)tableFooterView;
- (_Bool)isFolderApp:(unsigned long long)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)initNavigationItems;
- (_Bool)isNotAuthLicence;
- (void)initData;
- (void)initEditData;
- (void)checkAndAddLogReportItem:(_Bool)arg1 container:(id)arg2;
- (void)initRealCorpData;
- (_Bool)needContinue:(id)arg1;
- (void)initVirtualCorpData;
- (void)p_updateCardWallCell;
- (id)p_getIndexPathWithType:(long long)arg1 andAppId:(unsigned long long)arg2;
- (struct AppHideIdItem)p_getAppHideIdItemWithId:(unsigned long long)arg1;
- (long long)p_getFolderOrNotAppCount:(_Bool)arg1;
- (void)uploadHideAppIdsByTotalApps;
- (void)uploadHideAppIdsByID;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

