//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

#import "ConversationProxyObserverDelegate-Protocol.h"
#import "UserProxyObserverDelegate-Protocol.h"

@class NSObject, NSString, UILabel;

@interface WWKAvatarImageView : UIImageView <UserProxyObserverDelegate, ConversationProxyObserverDelegate>
{
    NSObject *guard;
    struct scoped_ptr<UserSmartProxyObserver, base::DefaultDeleter<UserSmartProxyObserver>> _userObserver;
    struct scoped_ptr<ConversationSmartProxyObserver, base::DefaultDeleter<ConversationSmartProxyObserver>> _conversationObserver;
    _Bool _retriesFailedAvatar;
    scoped_refptr_fd92d7bf _conversation;
    scoped_refptr_e1f85e48 _user;
    double _cornerRadiusForUser;
    UILabel *_availableLabel;
    vector_89e6321f _users;
}

+ (id)conversationAvatarData:(struct Conversation *)arg1;
+ (id)placeholderImageWithMemberCount:(long long)arg1 isRoom:(_Bool)arg2;
+ (id)recentImageUrlCache;
+ (_Bool)setRecentImageURL:(id)arg1 withUserId:(long long)arg2;
+ (id)recentImageWithUserId:(long long)arg1 completion:(CDUnknownBlockType)arg2;
+ (id)recentImageWithUserId:(long long)arg1;
+ (id)recentImagePathWithUserId:(long long)arg1;
+ (id)placeholderImageWithUserId:(long long)arg1;
+ (_Bool)isSpecialUid:(long long)arg1;
@property(retain, nonatomic) UILabel *availableLabel; // @synthesize availableLabel=_availableLabel;
@property(nonatomic) double cornerRadiusForUser; // @synthesize cornerRadiusForUser=_cornerRadiusForUser;
@property(nonatomic) _Bool retriesFailedAvatar; // @synthesize retriesFailedAvatar=_retriesFailedAvatar;
@property(nonatomic) vector_89e6321f *users; // @synthesize users=_users;
@property(nonatomic) scoped_refptr_e1f85e48 user; // @synthesize user=_user;
@property(nonatomic) scoped_refptr_fd92d7bf conversation; // @synthesize conversation=_conversation;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)sd_setImageWithURL:(id)arg1 placeholderImage:(id)arg2 options:(unsigned long long)arg3 progress:(CDUnknownBlockType)arg4 completed:(CDUnknownBlockType)arg5;
- (void)OnRemoveMembers:(const vector_4ea3d2e4 *)arg1 inConversation:(scoped_refptr_fd92d7bf)arg2;
- (void)onAddMembers:(const vector_4ea3d2e4 *)arg1 inConversation:(scoped_refptr_fd92d7bf)arg2;
- (void)OnUserPropertyChanged:(scoped_refptr_e1f85e48)arg1;
- (_Bool)setImageWithConversationKey:(const struct Key *)arg1;
- (_Bool)setSpecialConversationImage:(const scoped_refptr_fd92d7bf *)arg1;
- (void)scheduleReloadImageWhenForeground:(id)arg1;
- (void)reloadImageForground;
- (void)setOpenAPIConversationImage;
- (void)setUserConversationImage;
- (void)setNormalConversationImage;
- (void)reloadImage;
- (void)reloadImageThrottled;
- (void)setImage:(id)arg1;
- (void)layoutSubviews;
- (void)needDisplayAvailable:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

