//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKImageTableViewCell.h"

@class UIImageView, UILabel, WWKApplicationItem;

@interface WWKApplicationOperationTableViewCell : WWKImageTableViewCell
{
    _Bool _isSelected;
    UIImageView *_appImageView;
    UIImageView *_selectionIconView;
    UILabel *_appNameLabel;
    WWKApplicationItem *_item;
}

@property(retain, nonatomic) WWKApplicationItem *item; // @synthesize item=_item;
@property(retain, nonatomic) UILabel *appNameLabel; // @synthesize appNameLabel=_appNameLabel;
@property(retain, nonatomic) UIImageView *selectionIconView; // @synthesize selectionIconView=_selectionIconView;
@property(retain, nonatomic) UIImageView *appImageView; // @synthesize appImageView=_appImageView;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

