//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextField.h>

#import "UIKeyInput-Protocol.h"

@class NSString;
@protocol WWKBackspaceTextFieldDelegate;

@interface WWKBackspaceTextField : UITextField <UIKeyInput>
{
    id <WWKBackspaceTextFieldDelegate> _backspaceDelegate;
}

@property(nonatomic) __weak id <WWKBackspaceTextFieldDelegate> backspaceDelegate; // @synthesize backspaceDelegate=_backspaceDelegate;
- (void).cxx_destruct;
- (_Bool)keyboardInputShouldDelete:(id)arg1;
- (void)deleteBackward;

// Remaining properties
@property(nonatomic) long long autocapitalizationType;
@property(nonatomic) long long autocorrectionType;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool enablesReturnKeyAutomatically;
@property(readonly, nonatomic) _Bool hasText;
@property(readonly) unsigned long long hash;
@property(nonatomic) long long keyboardAppearance;
@property(nonatomic) long long keyboardType;
@property(nonatomic) long long returnKeyType;
@property(nonatomic, getter=isSecureTextEntry) _Bool secureTextEntry;
@property(nonatomic) long long spellCheckingType;
@property(readonly) Class superclass;
@property(copy, nonatomic) NSString *textContentType;

@end

