//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIScrollViewDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class NSString, UILabel, UIScrollView, UITapGestureRecognizer, UITextView, UIView, WWKAvatarImageView;

@interface WWKConversationNoticeViewController : UIViewController <UIScrollViewDelegate, UITextViewDelegate>
{
    scoped_refptr_fd92d7bf _conversation;
    double _keyBoardHeight;
    NSString *_lastNoticeString;
    _Bool _isInEdit;
    UITapGestureRecognizer *_singleTapGestureRecognizer;
    WWKAvatarImageView *_avatarImageView;
    UILabel *_nameLabel;
    UILabel *_timeLabel;
    UITextView *_contentTextView;
    UIView *_separatorLineView;
    UIView *_ownerLineView;
    UIScrollView *_scrollView;
    UIView *_headView;
}

@property(retain, nonatomic) UIView *headView; // @synthesize headView=_headView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UIView *ownerLineView; // @synthesize ownerLineView=_ownerLineView;
@property(retain, nonatomic) UIView *separatorLineView; // @synthesize separatorLineView=_separatorLineView;
@property(retain, nonatomic) UITextView *contentTextView; // @synthesize contentTextView=_contentTextView;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) WWKAvatarImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)p_onSingleTapClick:(id)arg1;
- (void)p_updataViewWithEdit:(_Bool)arg1 animated:(_Bool)arg2;
- (void)p_onClickEditButton;
- (void)p_onClickPublishButton;
- (void)p_onClickCancelButton;
- (void)p_AddContent:(id)arg1 toRichMessage:(struct RichMessage *)arg2;
- (id)p_parseRichMessageToNSString:(struct RichMessage)arg1;
- (id)p_parseRichMessage:(struct RichMessage)arg1;
- (basic_string_a490aa4c)p_parseTime:(long long)arg1;
- (void)p_reloadData;
- (void)p_keyBoardWillHide:(id)arg1;
- (void)p_keyboardWillShow:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithConversation:(scoped_refptr_fd92d7bf)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

