//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel, WWCardWallTagBackgroundView;

@interface WWKCardWallListCommentView : UIView
{
    UILabel *_comment;
    WWCardWallTagBackgroundView *_view;
}

@property(retain, nonatomic) WWCardWallTagBackgroundView *view; // @synthesize view=_view;
@property(retain, nonatomic) UILabel *comment; // @synthesize comment=_comment;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setBgColor:(id)arg1;
- (void)setTextColor:(id)arg1;
- (struct CGSize)layoutSubViewsWithWidth:(double)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)initSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

