//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface WWKCorpWaitVerifyItem : NSObject
{
    NSString *_title;
    NSString *_content;
    NSString *_name;
    NSString *_mobile;
    NSString *_mail;
    NSString *_avatarUrl;
    NSString *_faceCardUrl;
    NSString *_backCardUrl;
    unsigned long long _cellType;
    unsigned long long _status;
}

@property(nonatomic) unsigned long long status; // @synthesize status=_status;
@property(nonatomic) unsigned long long cellType; // @synthesize cellType=_cellType;
@property(retain, nonatomic) NSString *backCardUrl; // @synthesize backCardUrl=_backCardUrl;
@property(retain, nonatomic) NSString *faceCardUrl; // @synthesize faceCardUrl=_faceCardUrl;
@property(retain, nonatomic) NSString *avatarUrl; // @synthesize avatarUrl=_avatarUrl;
@property(retain, nonatomic) NSString *mail; // @synthesize mail=_mail;
@property(retain, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

