//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIScrollViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSString, UIButton, UIImageView, UILabel, UITextField, UIView;

@interface WWKConvenientLoginController : UIViewController <UITextFieldDelegate, UIScrollViewDelegate>
{
    struct Profile *current_profile_;
    UIImageView *_head;
    UILabel *_name;
    UITextField *_passwordTextField;
    UIView *_separatorLine;
    UIButton *_loginButton;
    UIButton *_changeAccountButton;
}

@property(nonatomic) __weak UIButton *changeAccountButton; // @synthesize changeAccountButton=_changeAccountButton;
@property(nonatomic) __weak UIButton *loginButton; // @synthesize loginButton=_loginButton;
@property(nonatomic) __weak UIView *separatorLine; // @synthesize separatorLine=_separatorLine;
@property(nonatomic) __weak UITextField *passwordTextField; // @synthesize passwordTextField=_passwordTextField;
@property(nonatomic) __weak UILabel *name; // @synthesize name=_name;
@property(nonatomic) __weak UIImageView *head; // @synthesize head=_head;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)p_onTextFieldDidChange;
- (void)changeAccountButtonPressed:(id)arg1;
- (void)loginButtonPressed:(id)arg1;
- (void)tapGestureRecongnizerResponed:(id)arg1;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

