//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIImageView, UILabel, UIView, WWKCardWallListCommentView;

@interface WWKCardWallListContainerView : UIButton
{
    UIView *_shortSeparator;
    UILabel *_nameLabel;
    UILabel *_jobLabel;
    UILabel *_companyLabel;
    UIImageView *_cardImage;
    UILabel *_lastCommentLabel;
    WWKCardWallListCommentView *_commentView1;
    WWKCardWallListCommentView *_commentView2;
    WWKCardWallListCommentView *_commentView3;
    UIImageView *_lastCommentImageView;
}

@property(retain, nonatomic) UIImageView *lastCommentImageView; // @synthesize lastCommentImageView=_lastCommentImageView;
@property(retain, nonatomic) WWKCardWallListCommentView *commentView3; // @synthesize commentView3=_commentView3;
@property(retain, nonatomic) WWKCardWallListCommentView *commentView2; // @synthesize commentView2=_commentView2;
@property(retain, nonatomic) WWKCardWallListCommentView *commentView1; // @synthesize commentView1=_commentView1;
@property(retain, nonatomic) UILabel *lastCommentLabel; // @synthesize lastCommentLabel=_lastCommentLabel;
@property(retain, nonatomic) UIImageView *cardImage; // @synthesize cardImage=_cardImage;
@property(retain, nonatomic) UILabel *companyLabel; // @synthesize companyLabel=_companyLabel;
@property(retain, nonatomic) UILabel *jobLabel; // @synthesize jobLabel=_jobLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)layoutSubViewsWithWidth:(double)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)initSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

