//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSTimerProxy, WWKLocationRetriever;

@interface WWKConversationViewControllerThirdAppVarType : NSObject
{
    struct scoped_ptr<CRTX::WSCorpAppDetail, base::DefaultDeleter<CRTX::WSCorpAppDetail>> _corpAppDetail;
    NSTimerProxy *_locationReportTimer;
    WWKLocationRetriever *_locationRetriever;
    _Bool hasHandledAppCardButtonEvent;
}

- (id).cxx_construct;
- (void).cxx_destruct;

@end

