//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class CAShapeLayer;

@interface WWKCornerButton : UIButton
{
    CAShapeLayer *_maskLayer;
    unsigned long long _cornerMode;
    double _cornerRadius;
}

@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) unsigned long long cornerMode; // @synthesize cornerMode=_cornerMode;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)path;
- (void)initSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

