//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WWKConversationDataSource : NSObject
{
    scoped_refptr_fd92d7bf _conversation;
    vector_46470f89 pinyin_user_vector_vector_;
    vector_46470f89 valid_user_vector_vector_;
    vector_4ea3d2e4 _sortedMemberList;
    _Bool _isChooseNewCreator;
}

@property(nonatomic) _Bool isChooseNewCreator; // @synthesize isChooseNewCreator=_isChooseNewCreator;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)configureValidDataSource;
- (_Bool)needShowGroupSection;
- (id)initWithConversation:(scoped_refptr_fd92d7bf)arg1;

@end

