//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton, UIImageView, UILabel, UITextField;

@interface WWKConvenientLoginCell : UITableViewCell
{
    UIImageView *_head;
    UILabel *_name;
    UITextField *_loginTextField;
    UIButton *_loginButton;
    UILabel *_moreButton;
}

@property(nonatomic) __weak UILabel *moreButton; // @synthesize moreButton=_moreButton;
@property(nonatomic) __weak UIButton *loginButton; // @synthesize loginButton=_loginButton;
@property(nonatomic) __weak UITextField *loginTextField; // @synthesize loginTextField=_loginTextField;
@property(nonatomic) __weak UILabel *name; // @synthesize name=_name;
@property(nonatomic) __weak UIImageView *head; // @synthesize head=_head;
- (void).cxx_destruct;

@end

