//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class WWCMROCRVCardInfo, WWKCardWallListContainerView;

@interface WWKCardWallListCell : UITableViewCell
{
    WWKCardWallListContainerView *_containerView;
    WWCMROCRVCardInfo *_cardInfo;
}

- (void).cxx_destruct;
- (void)onDidTap;
- (void)setData:(id)arg1;
- (void)layoutSubviews;
- (struct CGSize)layoutSubViewsWithWidth:(double)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)initSubViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

