//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "WWKUpdateMobileControllerDelegate-Protocol.h"

@class NSString, UIButton, UILabel, UISwitch, UIView;
@protocol WWKCardPrivacySettingViewControllerDelegate;

@interface WWKCardPrivacySettingViewController : UIViewController <WWKUpdateMobileControllerDelegate>
{
    id <WWKCardPrivacySettingViewControllerDelegate> _delegate;
    UILabel *_titleLabel;
    UISwitch *_mobileSwitch;
    UISwitch *_mailSwitch;
    UISwitch *_jobSwitch;
    UIButton *_finishButton;
    UIView *_backgroundView;
}

@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIButton *finishButton; // @synthesize finishButton=_finishButton;
@property(retain, nonatomic) UISwitch *jobSwitch; // @synthesize jobSwitch=_jobSwitch;
@property(retain, nonatomic) UISwitch *mailSwitch; // @synthesize mailSwitch=_mailSwitch;
@property(retain, nonatomic) UISwitch *mobileSwitch; // @synthesize mobileSwitch=_mobileSwitch;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <WWKCardPrivacySettingViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)verifyMobileSuccessful:(struct PhoneItem)arg1;
- (void)editTextController:(id)arg1 didClickSaveItemWithText:(id)arg2;
- (void)p_notifyChange;
- (_Bool)p_showEmailBindAlert;
- (_Bool)p_showJobBindAlert;
- (void)p_reloadData;
- (double)wwk_preferredWindowLevel;
- (void)cancelDidClick:(id)arg1;
- (void)finishDidClick:(id)arg1;
- (void)switchDidChange:(id)arg1;
- (void)viewDidLoad;
@property(readonly, nonatomic) _Bool jobSwitchOn;
@property(readonly, nonatomic) _Bool mailSwitchOn;
@property(readonly, nonatomic) _Bool mobileSwitchOn;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

