//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIActivityIndicatorView, UIImageView, UILabel;

@interface WWKConversationTitleView : UIView
{
    struct CGSize _lastFitSize;
    UIActivityIndicatorView *_activityIndictor;
    UILabel *_labelForTitle;
    UILabel *_labelForNumber;
    UIImageView *_topDisView;
    UILabel *_labelForSubTitle;
}

@property(retain, nonatomic) UILabel *labelForSubTitle; // @synthesize labelForSubTitle=_labelForSubTitle;
@property(retain, nonatomic) UIImageView *topDisView; // @synthesize topDisView=_topDisView;
@property(retain, nonatomic) UILabel *labelForNumber; // @synthesize labelForNumber=_labelForNumber;
@property(retain, nonatomic) UILabel *labelForTitle; // @synthesize labelForTitle=_labelForTitle;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)stopLoading;
- (void)startLoading;
- (void)showSubTitle:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

