//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKConversationMessageMaskedBubbleView.h"

@class UIImageView, UILabel, WWKMessageLink;

@interface WWKConversationLinkBubbleView : WWKConversationMessageMaskedBubbleView
{
    UILabel *_titleLabel;
    UILabel *_summaryLabel;
    UIImageView *_thumbImageView;
    double _summaryLabelLineHeightInForumMode;
}

@property(nonatomic) double summaryLabelLineHeightInForumMode; // @synthesize summaryLabelLineHeightInForumMode=_summaryLabelLineHeightInForumMode;
@property(retain, nonatomic) UIImageView *thumbImageView; // @synthesize thumbImageView=_thumbImageView;
@property(retain, nonatomic) UILabel *summaryLabel; // @synthesize summaryLabel=_summaryLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (id)makeForumSummaryStringWithText:(id)arg1;
- (id)makeForumTitleStringWithText:(id)arg1;
- (void)p_onTapAttendanceRemind;
- (void)p_onTapAttendanceSummaryMsg;
- (void)p_onTapWorklogShareMsg;
- (void)p_onTapWorklogAppMsg;
- (_Bool)isWorklogAppMsgLink;
- (_Bool)isWorklogShareMsgLink;
- (_Bool)isAttendanceRemind;
- (_Bool)isAttendanceConversation;
- (_Bool)isAttendanceSummaryRecord;
- (_Bool)isAttendanceRecordLink;
- (_Bool)isNameCardLink;
- (_Bool)isForumLink;
- (id)contextMenuItems;
- (void)viewDidTap:(id)arg1;
- (struct CGSize)layoutSubviewsWithWidth:(double)arg1;
- (void)updateData;
- (Class)messageItemClass;
- (void)initSubviews;

// Remaining properties
@property(readonly, nonatomic) WWKMessageLink *messageItem; // @dynamic messageItem;

@end

