//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIButton, WWKTextInputView;

@interface WWKCreateTeamController : UIViewController
{
    WWKTextInputView *_teamInputView;
    UIButton *_nextButton;
}

- (void).cxx_destruct;
- (void)p_initNavigation;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)handleNext:(id)arg1;
- (void)onEditingTeamName:(id)arg1;
- (void)setupSubviews;
- (void)viewDidLoad;

@end

