//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WWKSelectContactsBarDelegate-Protocol.h"

@class NSString, UITableView, WWKSelectContactsBar;
@protocol WWKChooseAtPeopleDelegate;

@interface WWKChooseAtPeopleController : UIViewController <UITableViewDelegate, UITableViewDataSource, WWKSelectContactsBarDelegate>
{
    vector_89e6321f _userList;
    vector_89e6321f _user_search_list;
    vector_4ea3d2e4 conversation_members_selected;
    _Bool _isAtAll;
    id <WWKChooseAtPeopleDelegate> _delegate;
    UITableView *_contentsTableView;
    UITableView *_searchTableView;
    WWKSelectContactsBar *_selectBar;
    NSString *_conversationName;
}

@property(retain, nonatomic) NSString *conversationName; // @synthesize conversationName=_conversationName;
@property(retain, nonatomic) WWKSelectContactsBar *selectBar; // @synthesize selectBar=_selectBar;
@property(retain, nonatomic) UITableView *searchTableView; // @synthesize searchTableView=_searchTableView;
@property(retain, nonatomic) UITableView *contentsTableView; // @synthesize contentsTableView=_contentsTableView;
@property(nonatomic) __weak id <WWKChooseAtPeopleDelegate> delegate; // @synthesize delegate=_delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)selectContactsBar:(id)arg1 didChangeSearchKeywords:(id)arg2;
- (void)selectContactsBar:(id)arg1 didRemoveUser:(struct UserOrDepartment)arg2;
- (id)p_createSelectAllCellWith:(id)arg1;
- (basic_string_a490aa4c)p_getEnglishName:(const basic_string_a490aa4c *)arg1;
- (vector_89e6321f)p_searchUsers:(basic_string_a490aa4c)arg1;
- (void)p_updateRightItemEnable;
- (void)p_confirmNavigationButtonPressed;
- (void)p_cancelNavigationButtonPressed;
- (void)searchTableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)contentTableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)searchTableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)contentTableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewWillLayoutSubviews;
- (void)initNavigationItems;
- (void)viewDidLoad;
- (id)initWithUsers:(vector_89e6321f *)arg1 andTitle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

