//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"
#import "WWKForwardingControllerDelegate-Protocol.h"

@class MFMailComposeViewController, NSString, UIButton, UIWebView;

@interface WWKDebugLogController : UIViewController <MFMailComposeViewControllerDelegate, UIWebViewDelegate, WWKForwardingControllerDelegate>
{
    struct FilePath currentLogFile;
    _Bool _showOSSLog;
    UIWebView *_webView;
    MFMailComposeViewController *_mailComposeController;
    UIButton *_scrollToBottomButton;
}

@property(nonatomic) _Bool showOSSLog; // @synthesize showOSSLog=_showOSSLog;
@property(nonatomic) __weak UIButton *scrollToBottomButton; // @synthesize scrollToBottomButton=_scrollToBottomButton;
@property(retain, nonatomic) MFMailComposeViewController *mailComposeController; // @synthesize mailComposeController=_mailComposeController;
@property(nonatomic) __weak UIWebView *webView; // @synthesize webView=_webView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)showProgressHUDWithText:(id)arg1;
- (void)sendLogByMail:(id)arg1;
- (void)sendLogByMessage:(id)arg1;
- (void)searchLog:(id)arg1;
- (void)selectLog:(id)arg1;
- (void)scrollToBottom:(id)arg1;
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(long long)arg2 error:(id)arg3;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)viewDidLoad;
- (id)initWithOSSLog;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

