//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "WWKForwardingControllerDelegate-Protocol.h"

@class NSArray, NSString, WWKMeBottomView;

@interface WWKDrawerMeViewController : UITableViewController <MFMailComposeViewControllerDelegate, WWKForwardingControllerDelegate>
{
    _Bool _showDebugCell;
    _Bool _needUpdateUI;
    NSArray *_cellTypes;
    WWKMeBottomView *_bottomView;
}

- (void).cxx_destruct;
- (void)fontSizeChange;
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (id)imageWithIndexPath:(id)arg1;
- (id)cellTitleForIndexPath:(id)arg1;
- (long long)cellTypeWithIndexPath:(id)arg1;
- (void)handleSetting;
- (void)handleManageCompany;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)setupBottomView;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithCellTypes:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

