//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WWKEnterpriseContactsViewController;

@protocol WWKEnterpriseContactsViewControllerDelegate <NSObject>

@optional
- (void)didClickCancelButtonInenterpriseContactsViewController:(WWKEnterpriseContactsViewController *)arg1;
- (void)enterpriseContactsViewController:(WWKEnterpriseContactsViewController *)arg1 didConfirmToSelectContacts:(vector_89e6321f)arg2 andDepartments:(vector_a024b487)arg3;
@end

