//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIScrollViewDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class NSString, UIScrollView, UITextView;
@protocol WWKEditNoticeDelegate;

@interface WWKEditNoticeViewController : UIViewController <UITextViewDelegate, UIScrollViewDelegate>
{
    scoped_refptr_fd92d7bf _conversation;
    double _keyBoardHeight;
    NSString *_lastNoticeString;
    id <WWKEditNoticeDelegate> _delegate;
    UITextView *_editTextView;
    UIScrollView *_scrollView;
}

@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UITextView *editTextView; // @synthesize editTextView=_editTextView;
@property(nonatomic) __weak id <WWKEditNoticeDelegate> delegate; // @synthesize delegate=_delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)keyBoardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (id)p_parseRichMessageToNSString:(struct RichMessage)arg1;
- (id)p_parseRichMessage:(struct RichMessage)arg1;
- (void)p_AddContent:(id)arg1 toRichMessage:(struct RichMessage *)arg2;
- (void)p_onClickPublishButton;
- (void)p_onClickCancelButton;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithConversation:(scoped_refptr_fd92d7bf)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

