//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, WWKForwardingController;

@protocol WWKForwardingControllerDelegate <NSObject>
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;

@optional
- (void)forwardingController:(WWKForwardingController *)arg1 presetUserListAtIndex:(unsigned long long)arg2 fetchUserCompletion:(void (^)(struct vector<scoped_refptr<model::User>, std::__1::allocator<scoped_refptr<model::User>>> *))arg3 noUserCompletion:(void (^)(UIView *))arg4;
- (NSArray *)titlesForPresetUserListInForwardingController:(WWKForwardingController *)arg1;
- (NSString *)defaultConversationNameInForwardingController:(WWKForwardingController *)arg1;
- (void)didClickCancelButtonInforwardingController:(WWKForwardingController *)arg1;
- (void)forwardingController:(WWKForwardingController *)arg1 messageDidCancel:(scoped_refptr_c1fa851d)arg2;
@end

