//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "ImgScrollViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "WWFavoritesProxyObserverDelegate-Protocol.h"
#import "WWKForwardingControllerDelegate-Protocol.h"
#import "WWKShowAllVideosAndImagesControllerDelegate-Protocol.h"
#import "WWKVideoPlayViewDelegate-Protocol.h"

@class MBProgressHUD, NSArray, NSMutableArray, NSMutableDictionary, NSString, UIButton, UIColor, UIPageControl, UIScrollView, UIView, UIWindow, WWKVideoControlView;
@protocol WWKImageBrowseViewControllerDelegate;

@interface WWKImageBrowseViewController : UIViewController <ImgScrollViewDelegate, UIScrollViewDelegate, WWKForwardingControllerDelegate, WWKShowAllVideosAndImagesControllerDelegate, WWKVideoPlayViewDelegate, WWFavoritesProxyObserverDelegate>
{
    struct CGRect _convertRect;
    NSString *_addCustomEmotionMD5;
    NSString *_addCustomEmotionOriUrl;
    MBProgressHUD *_hud;
    struct WWFavoritesProxyObserver *_mFavProxyObserver;
    UIView *imageBrowsePanel;
    UIView *markView;
    UIScrollView *imageBrowseContainer;
    UIButton *_showAllButton;
    UIPageControl *pageControl;
    NSMutableDictionary *_imgCacheDict;
    long long _selectedIndex;
    _Bool _goConversation;
    _Bool _showFavAction;
    _Bool _canDeleteImage;
    _Bool _showSave;
    _Bool _showPageControl;
    _Bool _isNeedUpdate;
    _Bool _isRotating;
    _Bool _showNavigation;
    UIView *_originalView;
    long long _fromChannel;
    NSArray *_wwKImageBrowseViewExternDatas;
    id <WWKImageBrowseViewControllerDelegate> _delegate;
    UIColor *_maskColor;
    UIWindow *_originalWindow;
    UIWindow *_keyWindow;
    MBProgressHUD *_progressHUD;
    long long _count;
    long long _currentIndex;
    NSMutableArray *_mediaItems;
    UIButton *_showOrginalButton;
    WWKVideoControlView *_videoCtrlView;
    NSMutableDictionary *_cacheDict;
    struct CGRect _dismissConvertRect;
}

@property(retain, nonatomic) NSMutableDictionary *cacheDict; // @synthesize cacheDict=_cacheDict;
@property(nonatomic) _Bool showNavigation; // @synthesize showNavigation=_showNavigation;
@property(nonatomic) _Bool isRotating; // @synthesize isRotating=_isRotating;
@property(nonatomic) _Bool isNeedUpdate; // @synthesize isNeedUpdate=_isNeedUpdate;
@property(retain, nonatomic) WWKVideoControlView *videoCtrlView; // @synthesize videoCtrlView=_videoCtrlView;
@property(retain, nonatomic) UIButton *showOrginalButton; // @synthesize showOrginalButton=_showOrginalButton;
@property(retain, nonatomic) NSMutableArray *mediaItems; // @synthesize mediaItems=_mediaItems;
@property(nonatomic) struct CGRect dismissConvertRect; // @synthesize dismissConvertRect=_dismissConvertRect;
@property(nonatomic) long long currentIndex; // @synthesize currentIndex=_currentIndex;
@property(nonatomic) long long count; // @synthesize count=_count;
@property(retain, nonatomic) MBProgressHUD *progressHUD; // @synthesize progressHUD=_progressHUD;
@property(retain, nonatomic) UIWindow *keyWindow; // @synthesize keyWindow=_keyWindow;
@property(nonatomic) __weak UIWindow *originalWindow; // @synthesize originalWindow=_originalWindow;
@property(copy, nonatomic) UIColor *maskColor; // @synthesize maskColor=_maskColor;
@property(nonatomic) _Bool showPageControl; // @synthesize showPageControl=_showPageControl;
@property(nonatomic) _Bool showSave; // @synthesize showSave=_showSave;
@property(nonatomic) _Bool canDeleteImage; // @synthesize canDeleteImage=_canDeleteImage;
@property(nonatomic) __weak id <WWKImageBrowseViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *wwKImageBrowseViewExternDatas; // @synthesize wwKImageBrowseViewExternDatas=_wwKImageBrowseViewExternDatas;
@property(nonatomic) long long fromChannel; // @synthesize fromChannel=_fromChannel;
@property(nonatomic) _Bool showFavAction; // @synthesize showFavAction=_showFavAction;
@property(nonatomic) __weak UIView *originalView; // @synthesize originalView=_originalView;
- (void).cxx_destruct;
- (void)onDidClickShowAll;
- (void)showAllPhotosAndImagesController:(id)arg1 didSelectedAtWWKMeidaItem:(id)arg2;
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setOriginFrame:(id)arg1;
- (void)showQRScanResultWithString:(id)arg1;
- (void)deleteImage:(id)arg1;
- (void)refreshCurrentImage;
- (_Bool)showFavorite;
- (_Bool)showFavoriteState;
- (_Bool)canGoConversationByMessage;
- (_Bool)quitFavoritePreView;
- (void)goConversationByCurrenSelIndex;
- (void)goConversationByMessage:(scoped_refptr_c1fa851d)arg1;
- (id)wwKImageBrowseViewExternDataInIndex:(unsigned long long)arg1;
- (_Bool)isEnableForwardImage:(id)arg1;
- (void)wwkVideoPlayViewDidClickForwardMessage:(scoped_refptr_c1fa851d)arg1;
- (void)favoritesVidioMessage:(scoped_refptr_c1fa851d)arg1 vidioView:(id)arg2 isFavorite:(_Bool)arg3;
- (void)favoritesImageMessage:(id)arg1 isFavorite:(_Bool)arg2;
- (void)OnCollectionEmotionFailed;
- (void)OnCollectionEmotionChanged;
- (void)didStartAddCustomEmotion:(id)arg1 andOriginUrl:(id)arg2;
- (void)AddToEmotion:(id)arg1;
- (_Bool)canShowAddToEmotion:(id)arg1;
- (_Bool)canShowShareToWX:(id)arg1;
- (void)shareImageToWX:(id)arg1;
- (void)forWardImageMessage:(id)arg1;
- (void)hideProgressHUD:(_Bool)arg1;
- (void)showProgressHUD:(id)arg1 success:(_Bool)arg2 atView:(id)arg3;
- (void)tapImageViewTappedWithObject:(id)arg1;
- (void)p_onTapVideoViewNotification:(id)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (void)respondQueryRect:(id)arg1;
- (void)forceQuit;
- (void)dismiss;
- (void)show;
- (void)configScrollView:(id)arg1 withUrl:(id)arg2 placeHolder:(id)arg3 index:(long long)arg4;
- (void)configScrollView:(id)arg1 withLocalImage:(id)arg2 index:(long long)arg3;
- (void)configScrollView:(id)arg1 atIndex:(long long)arg2;
- (void)p_showOrginalImage;
- (void)p_updateShowOrginalButtonTitle:(id)arg1 isDownloading:(_Bool)arg2;
- (void)p_updateShowOrginalButtonTitle:(id)arg1;
- (void)p_updateShowAllButton;
- (void)p_updateShowOrginalButton;
- (id)p_getDisplayingPageAtIndex:(long long)arg1;
- (_Bool)isDisplayingPageAtIndex:(long long)arg1;
- (id)cacheViewKey:(id)arg1;
- (_Bool)compareMessage:(const scoped_refptr_c1fa851d *)arg1 withOtherMessage:(const scoped_refptr_c1fa851d *)arg2;
- (id)getImageWithUrl:(id)arg1;
- (_Bool)imageExistWithUrl:(id)arg1;
- (void)presentWithWWKImageItems:(id)arg1 andConvertRect:(struct CGRect)arg2 index:(long long)arg3 atConversation:(const scoped_refptr_fd92d7bf *)arg4;
- (_Bool)p_isNeedAnimation:(id)arg1;
- (void)p_reserveImageCacheWithFromIndex:(long long)arg1 toIndex:(long long)arg2;
- (void)preparePreviousAndNextPage;
- (void)configureImageBrowseContainerView;
- (void)prepareToShow;
- (void)presentWithUrl:(id)arg1 andConvertRect:(struct CGRect)arg2 andAngle:(unsigned int)arg3;
- (void)presentWithUrl:(id)arg1 andConvertRect:(struct CGRect)arg2;
- (void)presentWithUrls:(id)arg1 andConvertRect:(struct CGRect)arg2 index:(long long)arg3;
- (void)initImageBrowseView;
- (void)initVideoControlView;
- (void)initShowOrginalButton;
- (void)initShowAllButton;
- (void)initSubviews;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

