//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITextFieldDelegate-Protocol.h"
#import "WXApiManagerDelegate-Protocol.h"

@class MBProgressHUD, NSString, UIButton, UILabel, WWKTextInputView;

@interface WWKInputAdminInfoController : UIViewController <UITextFieldDelegate, WXApiManagerDelegate>
{
    WWKTextInputView *_companyNameInputView;
    WWKTextInputView *_nameInputView;
    UIButton *_createTeamButton;
    UILabel *_tipsLabel;
    UIButton *_linkButton;
    MBProgressHUD *_bindWxHud;
}

- (void).cxx_destruct;
- (void)managerBindWxFinish;
- (void)managerEndLoginRequest;
- (void)managerBeginLoginRequest;
- (void)p_showAlertViewWithString:(id)arg1;
- (void)create;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)onTextViewEditting:(id)arg1;
- (void)animateUp:(_Bool)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)linkButtonClicked:(id)arg1;
- (void)setupSubviews;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)applicationDidEnterBackground;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

