//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WWKLogicHelper : NSObject
{
}

+ (id)snapshotImageWithUser:(scoped_refptr_e1f85e48)arg1;
+ (_Bool)strongBindCorpAlertController;
+ (_Bool)checkModifyMemberAbility;
+ (_Bool)isCorpCreatedByMobileAndNotAuthLicense;
+ (void)pushToUserInfoController:(const scoped_refptr_e1f85e48 *)arg1 navigationController:(id)arg2 hideBottomBar:(_Bool)arg3 conversation:(scoped_refptr_fd92d7bf)arg4 fromChannel:(long long)arg5;
+ (void)pushToUserInfoController:(const scoped_refptr_e1f85e48 *)arg1 navigationController:(id)arg2 hideBottomBar:(_Bool)arg3 fromChannel:(long long)arg4;
+ (void)pushToUserInfoController:(const scoped_refptr_e1f85e48 *)arg1 navigationController:(id)arg2 hideBottomBar:(_Bool)arg3;
+ (_Bool)isContinousReceiptEnabled;
+ (_Bool)isHitMailBlackList:(const basic_string_a490aa4c *)arg1;
+ (_Bool)isMailBind;
+ (_Bool)compareUserInfoAlias:(const basic_string_a490aa4c *)arg1 withMailProfileEmail:(const basic_string_a490aa4c *)arg2;
+ (_Bool)compareUserName:(const scoped_refptr_e1f85e48 *)arg1 withOther:(const scoped_refptr_e1f85e48 *)arg2;
+ (_Bool)isDefaultApplicationOpen:(unsigned long long)arg1;
+ (struct PhoneItem)createPhotoItemWithInternationCode:(const basic_string_a490aa4c *)arg1 number:(const basic_string_a490aa4c *)arg2;
+ (void)transformFromAttach:(const struct MailAttachment *)arg1 toMessage:(scoped_refptr_c1fa851d)arg2;
+ (void)setGlobalShieldWithRemainSeconds:(int)arg1;
+ (_Bool)isAnyOneHasEmailInConversation:(scoped_refptr_fd92d7bf)arg1;
+ (_Bool)isAnyOneHasMobileNumberInConversation:(scoped_refptr_fd92d7bf)arg1;
+ (_Bool)isCorpSubManager;
+ (_Bool)isCorpSuperManager;
+ (_Bool)isAvailabelWithUser:(scoped_refptr_e1f85e48)arg1;
+ (_Bool)isTencentStaff;
+ (id)loginUserName;
+ (struct CorpBriefInfo)currentCorpBriefInfo;
+ (vector_89e6321f)sortedUserList:(vector_89e6321f)arg1;
+ (vector_4ea3d2e4)sortedMemberList:(vector_4ea3d2e4)arg1;
+ (struct GlobalBreak)currentGlobalBreak;
+ (int)currentLanguageMode;
+ (double)adjustFontSizeFitsLanguageType:(double)arg1;
+ (double)titleFontSizeFitsLanguageType;

@end

