//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "NotificationProxyObserverDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "WWBBSFellowProxyObserverDelegate-Protocol.h"
#import "WWKForwardingControllerDelegate-Protocol.h"
#import "WWKMeInfoHeaderDelegate-Protocol.h"
#import "WXApiManagerDelegate-Protocol.h"

@class MBProgressHUD, NSMutableArray, NSString, UITapGestureRecognizer;

@interface WWKMeViewController : UITableViewController <WWKForwardingControllerDelegate, WWBBSFellowProxyObserverDelegate, WXApiManagerDelegate, NotificationProxyObserverDelegate, UIGestureRecognizerDelegate, WWKMeInfoHeaderDelegate>
{
    _Bool _needUpdateUI;
    NSMutableArray *_cellTypes;
    unsigned long long _viewControllerType;
    _Bool isSetting;
    UITapGestureRecognizer *multiTapRecognizer;
    MBProgressHUD *_bindWxHud;
    _Bool _suppInfo;
    _Bool _corpConfirm;
    struct WWBBSFellowProxyObserver *_bbsProxyObserver;
    struct scoped_ptr<NotificationProxyObserver, base::DefaultDeleter<NotificationProxyObserver>> _push_notification_observer;
    _Bool _isTencentCorp;
    _Bool _showDebugCell;
    _Bool _showBBSCell;
    _Bool _showHelperCenter;
    _Bool _showContactManager;
    _Bool _showHongbaoCell;
    _Bool _showBBSInTencent;
    _Bool _showHongbaoInTencent;
    _Bool _showLiveInTencent;
    _Bool _bfirstLoaddata;
    struct CGPoint _currOffset;
    _Bool _mNeedShowBbsRedPoint;
    int _nBbsNewMsg;
}

@property(nonatomic) int nBbsNewMsg; // @synthesize nBbsNewMsg=_nBbsNewMsg;
@property(nonatomic) _Bool mNeedShowBbsRedPoint; // @synthesize mNeedShowBbsRedPoint=_mNeedShowBbsRedPoint;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onContainerClick;
- (void)onShareClick;
- (void)onNameClick;
- (void)onCorpNameClick;
- (void)exposeRedPointsReport;
- (void)checkParentCellRedPoint;
- (id)redPointKeysWithCellType:(long long)arg1;
- (void)onNotification:(int)arg1 source:(const struct NotificationSource *)arg2 details:(const struct NotificationDetails *)arg3;
- (void)onBBSNewMsgInfoChanged:(unsigned int)arg1 showRedPoint:(_Bool)arg2;
- (void)managerBindWxFinish;
- (void)managerEndLoginRequest;
- (void)managerBeginLoginRequest;
- (void)privacyDidChange:(id)arg1;
- (void)selfHelpCorpChange;
- (void)fontSizeChange;
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;
- (id)indexPathWithCellType:(long long)arg1;
- (_Bool)isLastRowInSection:(id)arg1;
- (_Bool)isFirstRowInSection:(id)arg1;
- (void)pushViewController:(id)arg1 animated:(_Bool)arg2;
- (id)imageWithIndexPath:(id)arg1;
- (id)cellTitleForIndexPath:(id)arg1;
- (id)mutableCopyWithCellTypes:(id)arg1;
- (void)removeCellType:(long long)arg1;
- (long long)cellTypeWithIndexPath:(id)arg1;
- (void)p_rightItemClick;
- (void)mailLog;
- (void)sendLog;
- (void)p_sendFeedbackByAppRate;
- (void)p_sendFeedback;
- (void)LogoutConfirmSheetShow;
- (void)handleMultiTap:(id)arg1;
- (void)handleManageCompany;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)p_onApplicationDidBecomeActive:(id)arg1;
- (_Bool)p_handletencentCorpControl;
- (void)reloadData;
- (_Bool)needRemoveAppItem;
- (void)dealloc;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithMeViewControllerType:(unsigned long long)arg1;
- (id)initWithStyle:(long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

