//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "WXApiManagerDelegate-Protocol.h"

@class MBProgressHUD, NSString, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UIView;

@interface WWKMyTeamDetailPageController : UIViewController <WXApiManagerDelegate>
{
    UIView *_containerView;
    UIButton *_enterCompanyButton;
    UILabel *_jobLabel;
    UILabel *_subNameLabel;
    UILabel *_mobileLabel;
    UIImageView *_realNameStatusView;
    UIImageView *_avatarView;
    UILabel *_nameLabel;
    UILabel *_corpNameLabel;
    UILabel *_mailLabel;
    UIButton *_deleteCorpButton;
    struct CorpBriefInfo _corpInfo;
    long long _type;
    UIActivityIndicatorView *_indicatorView;
    _Bool _beginLogin;
    MBProgressHUD *_bindWxHud;
    unsigned long long _old_vid;
    struct CorpBriefInfo _enteringCorpInfo;
    _Bool _recomm;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)managerBindWxFinish;
- (void)managerEndLoginRequest;
- (void)managerBeginLoginRequest;
- (void)deleteCorp:(id)arg1;
- (void)p_rightItemClick;
- (void)p_onLoginFinish;
- (void)p_checkToken:(id)arg1 withName:(id)arg2;
- (void)p_showTextFieldAlertViewWithUserName:(id)arg1 checkAgain:(_Bool)arg2;
- (void)p_showAlertViewWithString:(id)arg1;
- (id)p_englishNameWithEmail:(id)arg1;
- (void)p_endLoginWithDelay:(_Bool)arg1;
- (void)p_beginLogin;
- (void)enterCorp:(struct CorpBriefInfo *)arg1;
- (void)p_enterBtnClicked;
- (void)viewWillLayoutSubviews;
- (void)initSubViews;
- (void)setCorpInfo:(struct CorpBriefInfo *)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)smartReportPhoneSearch:(basic_string_a490aa4c)arg1 OrMailSearch:(basic_string_a490aa4c)arg2;
- (void)viewDidLoad;
- (id)initWithType:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

