//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKCommonTableViewController.h"

#import "ConversationListProxyObserverDelegate-Protocol.h"
#import "DepartmentSyncStateProxyObserverDelegate-Protocol.h"
#import "NotificationProxyObserverDelegate-Protocol.h"
#import "SPTableViewCustomEditingViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "WWKBaseMessageCellDelegate-Protocol.h"
#import "WWKDataWrapperListObserverDelegate-Protocol.h"
#import "WWKMainPagePopMenuViewDelegate-Protocol.h"
#import "WWKQRScanViewControllerDelegate-Protocol.h"
#import "WWKSelectContactsViewControllerDelegate-Protocol.h"
#import "WWQRAndVCardScanViewControllerDelegate-Protocol.h"

@class MJRefreshFooter, NSArray, NSDate, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NSTimer, NSTimerProxy, UISearchDisplayController, UITapGestureRecognizer, UIView, WWKGlobalSearchController, WWKMainPagePopMenuView, WWKMessageListTitleView, WWKNetworkErrorWrapper, WWKPcOnlineWrapper, WWKPromoteWrapper, WWKRefreshFooter, WWKRelaxWrapper, WWKSearchBar;

@interface WWKMessageListController : WWKCommonTableViewController <ConversationListProxyObserverDelegate, WWKMainPagePopMenuViewDelegate, WWKDataWrapperListObserverDelegate, SPTableViewCustomEditingViewDelegate, UIScrollViewDelegate, WWKSelectContactsViewControllerDelegate, DepartmentSyncStateProxyObserverDelegate, WWKBaseMessageCellDelegate, NotificationProxyObserverDelegate, WWKQRScanViewControllerDelegate, WWQRAndVCardScanViewControllerDelegate>
{
    struct ConversationListProxyObserver *_convsertionListProxyObserver;
    struct DepartmentSyncStateProxyObserver *_departmentSyncStateProxyObserver;
    struct scoped_ptr<NotificationProxyObserver, base::DefaultDeleter<NotificationProxyObserver>> _notification_observer;
    NSMutableArray *_dataWrapperList;
    NSDictionary *_tableCellTypeAndActionDict;
    NSDictionary *_conversatonTypeMapDataWrapperTypeDict;
    NSMutableDictionary *_cellHeightDict;
    long long _currentScrollUnReadCellPosition;
    NSDate *_syncTime;
    NSTimerProxy *_updateSyncConversationTimer;
    NSTimer *_updateOnlineStatusTimer;
    NSTimerProxy *_updateCellTimeTimer;
    NSTimerProxy *_updateFetchUsersTimer;
    _Bool _isManualSetTop;
    _Bool _isManualSync;
    _Bool _isViewDidAppeared;
    _Bool _isPcOnline;
    int _device_status;
    _Bool _isFirstAddConversations;
    _Bool _willFetchingConversations;
    _Bool _isFetchingConversations;
    _Bool _isSetContentInset;
    _Bool _isAddMailAuthErrorMsg;
    int _onLineDeviceType;
    WWKNetworkErrorWrapper *_netWorkErrorWrapper;
    WWKPcOnlineWrapper *_pcOnlineWrapper;
    WWKRelaxWrapper *_relaxWrapper;
    WWKPromoteWrapper *_promoteWrapper;
    WWKMainPagePopMenuView *_popMenuView;
    UITapGestureRecognizer *_doubleTapRecognizer;
    struct SerialExecutor<std::__1::basic_string<char>> ui_serial_executor_;
    _Bool _needClearNotifications;
    _Bool _isNetworkError;
    _Bool _isFirstSync;
    WWKSearchBar *_searchBar;
    UISearchDisplayController *_searchDisplayController;
    WWKGlobalSearchController *_globalSearchController;
    WWKRefreshFooter *_refreshFooter;
    MJRefreshFooter *_refreshFooter2;
    WWKMessageListTitleView *_titleView;
    UIView *_headerCoverView;
}

@property(retain, nonatomic) UIView *headerCoverView; // @synthesize headerCoverView=_headerCoverView;
@property(nonatomic) _Bool isFirstSync; // @synthesize isFirstSync=_isFirstSync;
@property(retain, nonatomic) WWKMessageListTitleView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) MJRefreshFooter *refreshFooter2; // @synthesize refreshFooter2=_refreshFooter2;
@property(retain, nonatomic) WWKRefreshFooter *refreshFooter; // @synthesize refreshFooter=_refreshFooter;
@property(nonatomic) _Bool isNetworkError; // @synthesize isNetworkError=_isNetworkError;
@property(retain, nonatomic) WWKGlobalSearchController *globalSearchController; // @synthesize globalSearchController=_globalSearchController;
@property(retain, nonatomic) UISearchDisplayController *searchDisplayController; // @synthesize searchDisplayController=_searchDisplayController;
@property(retain, nonatomic) WWKSearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)requestCreateConversation;
- (void)onNotification:(int)arg1 source:(const struct NotificationSource *)arg2 details:(const struct NotificationDetails *)arg3;
- (void)onDidViewTapClose:(id)arg1;
- (void)onDidViewTap:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (id)tableView:(id)arg1 editingViewForRowAtIndexPath:(id)arg2;
- (void)onAddMessage:(const vector_b095e902 *)arg1 inConversation:(scoped_refptr_fd92d7bf)arg2;
- (void)onSetTop:(id)arg1;
- (void)onAudioNotifyWithSender:(unsigned long long)arg1;
- (void)onDidUnReadCountChange;
- (void)onDidOrderChange;
- (void)p_addMethodToSerialExecutor:(const Callback_c5ffa724 *)arg1;
- (void)p_notifySplashWindowDismiss;
- (void)logNonFirstEnterCorp;
- (void)logFirstEnterCorp;
- (void)p_hideProgressHUD;
- (void)p_showProgressHUD;
- (long long)p_getShowConversationsCount;
- (_Bool)p_checkHasMoreHistoryConversation;
- (void)p_removeDataWrappers:(id)arg1 animate:(_Bool)arg2 needUpdateBackground:(_Bool)arg3;
- (void)removeDataWithConversation:(const scoped_refptr_fd92d7bf *)arg1;
- (void)p_addDataWrappers:(id)arg1 needUpdateBackground:(_Bool)arg2;
- (_Bool)p_isDataFilter:(id)arg1;
- (void)p_advanceFetchHistoryMessages;
- (void)p_updateTableBackGroundView;
- (void)p_sendMsg;
- (_Bool)p_getNoDisturbState;
- (void)p_updatePromoteBarState;
- (void)p_updateRelaxState;
- (void)p_updatePcOnlineState;
- (void)p_setTopConversation:(const scoped_refptr_fd92d7bf *)arg1 isTop:(_Bool)arg2;
- (void)p_deleteConversation:(const scoped_refptr_fd92d7bf *)arg1;
- (void)p_manualSync;
- (void)p_showToast:(id)arg1;
- (void)p_updateNetWorkState;
- (void)p_updateOnlineStatus;
- (void)p_updateCellTime;
- (_Bool)p_isNeedShowNetWorkErrorSection;
- (void)p_redoSync;
- (void)p_showSyncErrorAlertView;
- (void)p_markAllReaded;
- (void)p_dateAndTimeSettingChange:(id)arg1;
- (void)updateTitleViewWithTitle:(id)arg1 isSyncing:(_Bool)arg2;
- (void)updateTitleAndTabBarTitle;
- (void)p_hideRefreshFooter;
- (void)p_showRefreshFooter;
- (void)p_hideSearchBar;
- (void)p_showSearchBar;
- (void)p_setTopAtIndexPath:(id)arg1;
- (void)p_deleteDataAtIndexPath:(id)arg1;
- (void)p_checkReachability;
- (long long)p_getNextHasUnReadCountCellPosition:(long long)arg1;
- (long long)p_getTotalMessageUnReadCount;
- (_Bool)p_equalNewDataList:(id)arg1 toOldConvList:(id)arg2;
- (long long)p_findDataWrapperType:(int)arg1 andConvId:(unsigned long long)arg2;
- (void)p_addMailAuthErrorMsg;
- (void)p_addDataSourceWithConversatons:(const vector_8fc7f2c8 *)arg1;
- (void)p_firstSyncAddDataSource:(id)arg1;
- (void)p_addConversations:(const vector_8fc7f2c8 *)arg1;
- (void)p_updateFetchUsersProgress;
- (void)p_updateSyncConversationProgress;
- (void)p_initSyncConversationProgress;
- (void)p_updateProgress:(long long)arg1 withSectionProgress:(double)arg2;
- (void)p_sortDataList;
- (void)presentGuideNotification;
- (void)guideToSettingIfTurnOffNotification;
- (void)OnSyncStateChanged:(const struct SyncState *)arg1;
- (void)OnSyncStateChanged:(int)arg1 withOldState:(int)arg2;
- (void)OnOrderChange;
- (void)OnRemoveConversation:(const scoped_refptr_fd92d7bf *)arg1;
- (void)OnAddConversations:(const vector_8fc7f2c8 *)arg1;
- (void)OnAddConversation:(const scoped_refptr_fd92d7bf *)arg1;
- (_Bool)showQRScanResultWithString:(id)arg1 srcCtrlrIsQRVCardScan:(_Bool)arg2;
- (_Bool)QRScanViewController:(id)arg1 didOutputContent:(id)arg2 withType:(unsigned long long)arg3;
- (_Bool)QRVCardScanViewController:(id)arg1 didOutputContent:(id)arg2 withType:(unsigned long long)arg3;
- (void)wwkMainPagePopMenuViewControllerDidRemoveFromSuperView;
- (void)_onEnterSysContactViewController;
- (void)wwkMainPagePopMenuViewControllerDidSelected:(long long)arg1;
- (void)didConfirmToSelectContacts:(int)arg1 conversation:(const scoped_refptr_fd92d7bf *)arg2 hud:(id)arg3 errorMessage:(basic_string_a490aa4c)arg4;
- (void)selectContactsViewController:(id)arg1 didConfirmToSelectContacts:(vector_89e6321f)arg2;
- (void)selectContactsViewController:(id)arg1 didConfirmToSelectContacts:(vector_89e6321f)arg2 andDepartments:(vector_a024b487)arg3;
- (void)tableView:(id)arg1 didEndEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 editActionsForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 shouldHighlightRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)timeZoneChanged;
- (void)onDynamicFontSizeDidChange;
- (void)onLoginStateDidChange:(id)arg1;
- (void)onWillAppEnterForeground;
- (void)applicationDidBecomeActive;
- (void)onDidSingleClickTabBar;
- (void)onDidDoubleClickTabBar;
- (void)onClickTitleView:(id)arg1;
- (void)p_rightBarItemClick:(id)arg1;
- (void)p_leftBarItemClick:(id)arg1;
- (void)needUpdateDataSource;
- (void)debugCreateTeam:(id)arg1;
- (void)updateNavigationLeftItem:(_Bool)arg1;
- (void)initNavigationItems;
- (void)viewWillLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)networkChanged;
- (void)dealloc;
- (void)fetchHistoryConversations;
- (void)fetchItems;
- (void)viewDidLoad;
@property(readonly, nonatomic) _Bool forbiddenFetchHistroyConvs;
@property(readonly, nonatomic) long long dataSourceCount;
@property(readonly, nonatomic) NSArray *filterType;
@property(readonly, nonatomic) UIView *backgroundEmptyView;
@property(readonly, nonatomic) NSDictionary *showConversationDict;
- (void)initBlock;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

