//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MGSwipeTableCell.h"

@class NSString, UIButton, UIImageView, UILabel, UIView;

@interface WWKMyCurrentTeamTableViewCell : MGSwipeTableCell
{
    UIImageView *_logoView;
    UILabel *_corpNameLabel;
    UIButton *_ownerButton;
    UILabel *_ownerTipsLabel;
    UIView *_separator;
    unsigned long long _owner_vid;
    UIImageView *_stateImageView;
    _Bool _isMeOwner;
    NSString *_logoUrl;
    NSString *_corpName;
    NSString *_ownerName;
    long long _corpStat;
}

@property(nonatomic) long long corpStat; // @synthesize corpStat=_corpStat;
@property(nonatomic) _Bool isMeOwner; // @synthesize isMeOwner=_isMeOwner;
@property(retain, nonatomic) NSString *ownerName; // @synthesize ownerName=_ownerName;
@property(retain, nonatomic) NSString *corpName; // @synthesize corpName=_corpName;
@property(retain, nonatomic) NSString *logoUrl; // @synthesize logoUrl=_logoUrl;
- (void).cxx_destruct;
- (void)chatToOwner:(id)arg1;
- (void)handleManageTeam:(id)arg1;
- (void)layoutSubviews;
- (struct CGSize)p_layoutSubViewsWithLimitWidth:(double)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setOwnerVid:(unsigned long long)arg1;
- (void)initSubViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

