//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKMessageWithAttach.h"

@class NSString, UIImage;

@interface WWKMessageImage : WWKMessageWithAttach
{
    _Bool _isHD;
    NSString *_fileID;
    NSString *_url;
    UIImage *_image;
    unsigned long long _imageByteCount;
    unsigned long long _fileSize;
    unsigned long long _thumbSize;
    struct CGSize _imageSize;
}

+ (_Bool)supportsMergeForwarding;
+ (_Bool)supportsForwarding;
@property(nonatomic) unsigned long long thumbSize; // @synthesize thumbSize=_thumbSize;
@property(nonatomic) _Bool isHD; // @synthesize isHD=_isHD;
@property(nonatomic) unsigned long long fileSize; // @synthesize fileSize=_fileSize;
@property(nonatomic) unsigned long long imageByteCount; // @synthesize imageByteCount=_imageByteCount;
@property(nonatomic) struct CGSize imageSize; // @synthesize imageSize=_imageSize;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *fileID; // @synthesize fileID=_fileID;
- (void).cxx_destruct;
- (void)generateThumbnailsFromOriginalImage;
- (id)htmlRepresentationToWeixin;
- (id)debugDescription;
- (id)htmlAttachments;
- (id)htmlRepresentation;
- (_Bool)htmlCompleted;
- (unsigned long long)attachmentSize;
- (id)imageUrlForSize:(long long)arg1;
@property(readonly, nonatomic) NSString *smartThumbnailUrl;
@property(readonly, nonatomic) NSString *previewUrl;
@property(readonly, nonatomic) NSString *originalUrl;
@property(readonly, nonatomic) NSString *thumbnailUrl;
@property(readonly, nonatomic) NSString *canonicalUrl;
- (id)baseUrl;
- (_Bool)completed;
@property(readonly, nonatomic) NSString *thumbnailPath;
@property(readonly, nonatomic) NSString *previewPath;
@property(readonly, nonatomic) NSString *originalPath;
- (id)localPath;
- (id)pathForURL:(id)arg1;
- (_Bool)addSimplePreviewCustomViewTo:(id)arg1;
- (_Bool)addPreviewCustomViewTo:(id)arg1;
- (_Bool)removeWithContext:(id)arg1;
- (unsigned long long)cleanItemSize;
- (id)cleanItemIcon;
- (id)cleanItemName;

@end

