//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class UIButton, UILabel, WWKModifyCorpNameRecordView;

@interface WWKModifyCorpNameRecordController : UITableViewController
{
    struct CorpBriefInfo info_;
    struct IDCardInfo _idCardInfo;
    id _context;
    WWKModifyCorpNameRecordView *_recordView;
    UILabel *_nameErrorLabel;
    UIButton *_modifyButton;
}

@property(retain, nonatomic) UIButton *modifyButton; // @synthesize modifyButton=_modifyButton;
@property(retain, nonatomic) UILabel *nameErrorLabel; // @synthesize nameErrorLabel=_nameErrorLabel;
@property(retain, nonatomic) WWKModifyCorpNameRecordView *recordView; // @synthesize recordView=_recordView;
@property(nonatomic) __weak id context; // @synthesize context=_context;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)viewWillLayoutSubviews;
- (void)p_onUserNameButtonClicked:(id)arg1;
- (void)p_onModifyButtonClicked:(id)arg1;
- (void)viewDidLoad;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)p_updateUI;
- (void)setInfo:(const struct CorpBriefInfo *)arg1;

@end

