//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKMessageMedia.h"

@class NSArray, NSString;

@interface WWKMessageForwards : WWKMessageMedia
{
    _Bool _isHistoryForward;
    _Bool _isExternalForward;
    NSString *_from;
    NSArray *_textArray;
}

+ (_Bool)supportsMergeForwarding;
+ (_Bool)supportsForwarding;
@property(nonatomic) _Bool isExternalForward; // @synthesize isExternalForward=_isExternalForward;
@property(nonatomic) _Bool isHistoryForward; // @synthesize isHistoryForward=_isHistoryForward;
@property(copy, nonatomic) NSArray *textArray; // @synthesize textArray=_textArray;
@property(copy, nonatomic) NSString *from; // @synthesize from=_from;
- (void).cxx_destruct;
- (id)debugDescription;
- (id)htmlRepresentation;
@property(readonly, nonatomic) NSString *fromTitle;
- (_Bool)addSimplePreviewCustomViewTo:(id)arg1;
- (_Bool)addPreviewCustomViewTo:(id)arg1;

@end

