//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKMessageMedia.h"

@class NSString;

@interface WWKMessageApplyNotify : WWKMessageMedia
{
    long long _applyType;
    long long _innerType;
    NSString *_title;
    NSString *_innerTypeStr;
    double _startTime;
    double _endTime;
    double _duration;
    unsigned long long _expenseSum;
    NSString *_reason;
    NSString *_linkUrl;
    NSString *_commonApplyInfo1;
    NSString *_commonApplyInfo2;
}

+ (id)approvalAskExpenseTitle:(int)arg1;
+ (id)approvalAskLeaveDateString:(double)arg1;
+ (id)approvalAskLeaveLeftTypeStr:(int)arg1;
+ (id)approvalAskLeaveLeftTitle:(const struct ScLeaveInfo *)arg1;
+ (id)approvalDateString2:(double)arg1;
+ (id)approvalDateString:(double)arg1;
+ (id)approvalAskDatetimeString:(double)arg1;
+ (id)getInnerTypeString:(id)arg1;
+ (_Bool)supportsMergeForwarding;
+ (_Bool)supportsForwarding;
@property(copy, nonatomic) NSString *commonApplyInfo2; // @synthesize commonApplyInfo2=_commonApplyInfo2;
@property(copy, nonatomic) NSString *commonApplyInfo1; // @synthesize commonApplyInfo1=_commonApplyInfo1;
@property(copy, nonatomic) NSString *linkUrl; // @synthesize linkUrl=_linkUrl;
@property(copy, nonatomic) NSString *reason; // @synthesize reason=_reason;
@property(nonatomic) unsigned long long expenseSum; // @synthesize expenseSum=_expenseSum;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(nonatomic) double endTime; // @synthesize endTime=_endTime;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(copy, nonatomic) NSString *innerTypeStr; // @synthesize innerTypeStr=_innerTypeStr;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long innerType; // @synthesize innerType=_innerType;
@property(nonatomic) long long applyType; // @synthesize applyType=_applyType;
- (void).cxx_destruct;
- (id)htmlRepresentation;

@end

