//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface WWKMeidaItem : NSObject
{
    scoped_refptr_c1fa851d _modelMessage;
    unsigned int _angle;
    NSString *_url;
    long long _index;
}

@property(nonatomic) unsigned int angle; // @synthesize angle=_angle;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
- (id).cxx_construct;
- (void).cxx_destruct;
- (scoped_refptr_c1fa851d)getModelMessage;
- (id)init;
- (id)initWithMessage:(scoped_refptr_c1fa851d *)arg1;

@end

