//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "UITextFieldDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"
#import "WWKVerifyCodeControllerDelegate-Protocol.h"

@class NSString, UIWebView, WWKInputVerifyView, WWKModifyMailCell, WWKModifyMailFooterView, WWKModifyMailHeaderView, WWKNotSupportMailView, WWKWebViewProgressView;
@protocol WWKModifyMailControllerDelegate;

@interface WWKModifyMailController : UITableViewController <UITextFieldDelegate, UIWebViewDelegate, WWKVerifyCodeControllerDelegate>
{
    _Bool _isChangeVerfiyCode;
    _Bool _isPresent;
    _Bool _isModifyMail;
    _Bool _isShowSuccessToast;
    NSString *_mailAddress;
    id <WWKModifyMailControllerDelegate> _delegate;
    CDUnknownBlockType _completehandle;
    WWKModifyMailHeaderView *_headerView;
    WWKModifyMailFooterView *_footerView;
    WWKModifyMailCell *_modifyMailCell;
    WWKInputVerifyView *_inputVerifyView;
    WWKNotSupportMailView *_notSupportMailView;
    long long _state;
    UIWebView *_webView;
    WWKWebViewProgressView *_progressView;
    long long _wtloginTag;
}

+ (void)ShowAlertAt:(id)arg1 cancelHandle:(CDUnknownBlockType)arg2 completeHandle:(CDUnknownBlockType)arg3;
@property(nonatomic) long long wtloginTag; // @synthesize wtloginTag=_wtloginTag;
@property(retain, nonatomic) WWKWebViewProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(retain, nonatomic) WWKNotSupportMailView *notSupportMailView; // @synthesize notSupportMailView=_notSupportMailView;
@property(retain, nonatomic) WWKInputVerifyView *inputVerifyView; // @synthesize inputVerifyView=_inputVerifyView;
@property(retain, nonatomic) WWKModifyMailCell *modifyMailCell; // @synthesize modifyMailCell=_modifyMailCell;
@property(retain, nonatomic) WWKModifyMailFooterView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) WWKModifyMailHeaderView *headerView; // @synthesize headerView=_headerView;
@property(copy, nonatomic) CDUnknownBlockType completehandle; // @synthesize completehandle=_completehandle;
@property(nonatomic) __weak id <WWKModifyMailControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isShowSuccessToast; // @synthesize isShowSuccessToast=_isShowSuccessToast;
@property(nonatomic) _Bool isModifyMail; // @synthesize isModifyMail=_isModifyMail;
@property(nonatomic) _Bool isPresent; // @synthesize isPresent=_isPresent;
@property(retain, nonatomic) NSString *mailAddress; // @synthesize mailAddress=_mailAddress;
- (void).cxx_destruct;
- (void)smsLogin:(CDUnknownBlockType)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)p_autherApproval;
- (void)p_autherApprovalCancel;
- (void)p_bindMail;
- (void)p_modifyMail;
- (void)p_dismiss;
- (void)p_emailOccupyByUserName:(basic_string_a490aa4c)arg1;
- (void)p_verfiyEMailCodeError;
- (void)p_verifyEmailPasswordError;
- (void)p_verifyWithMailProtocolInfo:(scoped_ptr_6cd7d410)arg1 callback:(CDUnknownBlockType)arg2;
- (void)p_verifyPasswordSuccessWithEmail:(id)arg1 password:(id)arg2 protocolType:(int)arg3 callback:(CDUnknownBlockType)arg4;
- (void)p_verifyPasswordSuccessWithEmail:(id)arg1 password:(id)arg2 protocolType:(int)arg3;
- (void)p_showToast:(id)arg1 mode:(long long)arg2;
- (void)p_processWtLogin:(id)arg1;
- (void)p_QQMailChangeVerifyCode;
- (void)p_bizMailChangeVerifyCode;
- (void)p_changeVerifyCode;
- (void)p_QQmailVerify;
- (void)p_bizMailVerify;
- (void)p_actionVerfiy;
- (void)p_showInputVerfiyView;
- (void)p_updateTextFieldEnable;
- (void)p_QQMailLogin;
- (void)p_bizMailLogin;
- (void)p_pushToNextCtrl:(long long)arg1;
- (void)p_showEmailChangeAlertWithNewMailAddress:(id)arg1 action:(CDUnknownBlockType)arg2;
- (void)p_action;
- (void)p_updateViewsWithMailProtocolType:(int)arg1;
- (void)p_updateViews;
- (id)p_passwordErrorWording:(int)arg1;
- (void)textFieldTextDidChange:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)initViews;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;
- (id)initWithState:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

