//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface WWKModifyCorpNameRecordView : UIView
{
    UIView *_topSepLine;
    UILabel *_corpFullNameLabel;
    UILabel *_corpFullNameTitleLabel;
    UIView *_middleSep1;
    UILabel *_corpShortNameLabel;
    UILabel *_corpShortNameTitleLabel;
    UIView *_middleSep2;
    UILabel *_userNameTitleLabel;
    UILabel *_userNameLabel;
    UIView *_middleSep3;
    UILabel *_userModifyRecordTitleLabel;
    UILabel *_userModifyRecordLabel;
    UIView *_bottomSepLine;
}

+ (_Bool)requiresConstraintBasedLayout;
@property(retain, nonatomic) UIView *bottomSepLine; // @synthesize bottomSepLine=_bottomSepLine;
@property(retain, nonatomic) UILabel *userModifyRecordLabel; // @synthesize userModifyRecordLabel=_userModifyRecordLabel;
@property(retain, nonatomic) UILabel *userModifyRecordTitleLabel; // @synthesize userModifyRecordTitleLabel=_userModifyRecordTitleLabel;
@property(retain, nonatomic) UIView *middleSep3; // @synthesize middleSep3=_middleSep3;
@property(retain, nonatomic) UILabel *userNameLabel; // @synthesize userNameLabel=_userNameLabel;
@property(retain, nonatomic) UILabel *userNameTitleLabel; // @synthesize userNameTitleLabel=_userNameTitleLabel;
@property(retain, nonatomic) UIView *middleSep2; // @synthesize middleSep2=_middleSep2;
@property(retain, nonatomic) UILabel *corpShortNameTitleLabel; // @synthesize corpShortNameTitleLabel=_corpShortNameTitleLabel;
@property(retain, nonatomic) UILabel *corpShortNameLabel; // @synthesize corpShortNameLabel=_corpShortNameLabel;
@property(retain, nonatomic) UIView *middleSep1; // @synthesize middleSep1=_middleSep1;
@property(retain, nonatomic) UILabel *corpFullNameTitleLabel; // @synthesize corpFullNameTitleLabel=_corpFullNameTitleLabel;
@property(retain, nonatomic) UILabel *corpFullNameLabel; // @synthesize corpFullNameLabel=_corpFullNameLabel;
@property(retain, nonatomic) UIView *topSepLine; // @synthesize topSepLine=_topSepLine;
- (void).cxx_destruct;
- (void)updateConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

@end

