//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKMessageMedia.h"

@class NSString;

@interface WWKMessageAttendanceRemind : WWKMessageMedia
{
    long long _checkinType;
    NSString *_title;
    NSString *_summary;
}

+ (_Bool)supportsMergeForwarding;
+ (_Bool)supportsForwarding;
@property(copy, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long checkinType; // @synthesize checkinType=_checkinType;
- (void).cxx_destruct;
- (id)htmlRepresentation;

@end

