//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MGSwipeTableCell.h"

@class UIButton, UILabel, UIView;

@interface WWKMyCurrentVirtualTeamCell : MGSwipeTableCell
{
    struct CorpBriefInfo _corpinfo;
    UILabel *_corpNameLabel;
    UILabel *_corpFullNameLabel;
    UIView *_separatorView;
    UIButton *_editIconButton;
    UIButton *_claimButton;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)p_layoutSubViewsWithLimitWidth:(double)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)editCorpInfo;
- (void)claimButtonClicked;
- (void)setCorpInfo:(const struct CorpBriefInfo *)arg1;
- (void)initSubViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

