//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "NotificationProxyObserverDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "WWKCommonSettingControllerDelegate-Protocol.h"
#import "WWKEditTextDelegate-Protocol.h"
#import "WWKModifyMailControllerDelegate-Protocol.h"
#import "WWKNameEditControllerDelegate-Protocol.h"
#import "WWKUpdateMobileControllerDelegate-Protocol.h"
#import "WWKUpdateVirtualCorpInfoDelegate-Protocol.h"
#import "WWKUploadWorkCardControllerDelegate-Protocol.h"
#import "WWKVerifyMobileDialogControllerDelegate-Protocol.h"
#import "WWKWaitVerifyCorpControllerDelegate-Protocol.h"
#import "WXApiManagerDelegate-Protocol.h"

@class MBProgressHUD, NSMutableArray, NSString;

@interface WWKMeInfoTableViewController : UITableViewController <UIImagePickerControllerDelegate, UINavigationControllerDelegate, WWKVerifyMobileDialogControllerDelegate, WWKEditTextDelegate, WWKCommonSettingControllerDelegate, WXApiManagerDelegate, WWKUpdateMobileControllerDelegate, WWKModifyMailControllerDelegate, NotificationProxyObserverDelegate, WWKNameEditControllerDelegate, WWKUploadWorkCardControllerDelegate, WWKUpdateVirtualCorpInfoDelegate, WWKWaitVerifyCorpControllerDelegate>
{
    NSMutableArray *_dataSource;
    vector_a024b487 department_list_;
    scoped_refptr_e1f85e48 _user;
    MBProgressHUD *_bindWxHud;
    _Bool _suppName;
    _Bool _suppMobile;
    unsigned long long _department_id;
    struct scoped_ptr<NotificationProxyObserver, base::DefaultDeleter<NotificationProxyObserver>> _push_notification_observer;
    struct IDCardInfo _idCardInfo;
    _Bool RTX_SYNC;
    _Bool QYH_BIND;
    _Bool BIZMAIL_BIND;
    _Bool OPENAPI_SYNC;
    unsigned long long _type;
}

@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)OnInfoChange;
- (void)onUpdateVirtualCorpInfoSuccess;
- (void)OnCancelAppying;
- (void)onUploadWorkCardSuccess;
- (void)OnSubTitleClick;
- (void)nameEditController:(id)arg1 didFinishEditingName:(id)arg2;
- (void)onPvMergeWillOpen:(id)arg1;
- (vector_36fe4106 *)allowRedPointKeys;
- (void)exposeRedPointsReport;
- (void)checkParentCellRedPoint;
- (void)managerBindWxFinish;
- (void)managerEndLoginRequest;
- (void)managerBeginLoginRequest;
- (void)controller:(id)arg1 onItemSelected:(long long)arg2;
- (void)verifyMobileDialog:(id)arg1 didCheckMobileSuccessful:(id)arg2;
- (void)verifyMobileSuccessful:(struct PhoneItem)arg1;
- (void)bindMailSuccessful:(id)arg1 currentController:(id)arg2;
- (void)onNotification:(int)arg1 source:(const struct NotificationSource *)arg2 details:(const struct NotificationDetails *)arg3;
- (void)p_reloadMailAddressIndexpath:(id)arg1;
- (void)p_presentModifyMailCtrlWithEMail:(id)arg1;
- (void)didBeginEditText:(id)arg1 EditTextController:(id)arg2 emailString:(id)arg3 phoneString:(id)arg4 nameString:(id)arg5 indexPathRowEdited:(id)arg6;
- (void)editTextController:(id)arg1 didClickSaveItemWithText:(id)arg2;
- (id)p_getIndexpathWithName:(id)arg1;
- (void)presentEditTextControllerWithNavigationTitle:(id)arg1 andContent:(id)arg2 andPlaceholder:(id)arg3 andEditTextType:(unsigned long long)arg4;
- (void)presentEditTextControllerWithContent:(id)arg1 andPlaceholder:(id)arg2 andEditTextType:(unsigned long long)arg3;
- (id)redPointKeysWithInfoPair:(id)arg1;
- (_Bool)isMailCell:(id)arg1;
- (_Bool)isPhoneCell:(id)arg1;
- (_Bool)isNameCell:(id)arg1;
- (_Bool)isGenderCell:(id)arg1;
- (_Bool)isMobileCell:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (_Bool)tryEdit:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tipsFooterView;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onMoreBtnClick:(id)arg1;
- (void)initDataAndRefresh:(_Bool)arg1;
- (void)initCorpData;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)refreshData;
- (void)viewDidLoad;
- (id)initWithUser:(scoped_refptr_e1f85e48)arg1;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

