//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "AnnounceServiceProxyObserverDelegate-Protocol.h"
#import "ConversationProxyObserverDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WWKNewAnnouncementCellDelegate-Protocol.h"
#import "WWKSearchBarDelegate-Protocol.h"

@class MJRefreshFooter, MJRefreshHeader, NSString, UIActivityIndicatorView, UILabel, UISegmentedControl, UITableView, UITapGestureRecognizer, UIView, WWKSearchBar;

@interface WWKNewAnnouncementListController : UIViewController <WWKSearchBarDelegate, UISearchBarDelegate, UITableViewDataSource, UITableViewDelegate, AnnounceServiceProxyObserverDelegate, ConversationProxyObserverDelegate, WWKNewAnnouncementCellDelegate>
{
    UITableView *_receivedAnnounceTableView;
    UITableView *_sentAnnounceTableView;
    UITableView *_draftAnnounceTableVIew;
    UIView *_bottomView;
    UIView *_bottomSeperator;
    UISegmentedControl *_segmentController;
    UITapGestureRecognizer *tapGp_;
    UIView *searchMaskView_;
    UIView *searchLoadingView_;
    UIActivityIndicatorView *searchIndicatorView_;
    UILabel *searchLoadingLabel_;
    UITableView *searchResultDisplayTableView_;
    UIView *searchEmptyView_;
    UILabel *searchEmptyLabel_;
    vector_b97e3dd8 _receivedAnnouncementList;
    vector_b97e3dd8 _sentAnnouncementList;
    vector_b97e3dd8 _draftAnnouncementList;
    long long _currentSelectedSegment;
    struct map<scoped_refptr<model::Message>, double, std::__1::less<scoped_refptr<model::Message>>, std::__1::allocator<std::__1::pair<const scoped_refptr<model::Message>, double>>> _message_row_height_cache;
    struct map<scoped_refptr<announce::model::Announcement>, double, std::__1::less<scoped_refptr<announce::model::Announcement>>, std::__1::allocator<std::__1::pair<const scoped_refptr<announce::model::Announcement>, double>>> _announce_row_height_cache;
    UIActivityIndicatorView *_indicatorView;
    struct AnnounceServiceProxyObserver *_proxyAnnounceServiceObserver;
    _Bool _isAdministrator;
    double _cell_row_height_cache;
    scoped_refptr_8a203b4c _last_announce;
    _Bool _isFetchingHistory;
    _Bool _isSyncing;
    WWKSearchBar *_searchBar;
    MJRefreshHeader *_refreshHeader;
    MJRefreshFooter *_refreshFooter;
}

@property(nonatomic) _Bool isSyncing; // @synthesize isSyncing=_isSyncing;
@property(nonatomic) _Bool isFetchingHistory; // @synthesize isFetchingHistory=_isFetchingHistory;
@property(retain, nonatomic) MJRefreshFooter *refreshFooter; // @synthesize refreshFooter=_refreshFooter;
@property(retain, nonatomic) MJRefreshHeader *refreshHeader; // @synthesize refreshHeader=_refreshHeader;
@property(retain, nonatomic) WWKSearchBar *searchBar; // @synthesize searchBar=_searchBar;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)p_reloadTableView:(id)arg1;
- (void)p_fetchHistory;
- (void)p_sync;
- (void)p_onDynamicFontSizeDidChange;
- (void)p_sortMessages:(vector_b095e902 *)arg1 orderedByAscending:(_Bool)arg2;
- (void)p_sortAnnouncementList:(vector_b97e3dd8 *)arg1;
- (void)p_stopLoading;
- (void)p_startLoading;
- (id)p_getCurrentSelectedTableView;
- (id)p_createContentTableView;
- (void)p_setTableHeaderView:(long long)arg1;
- (void)p_switchContentTableView:(long long)arg1;
- (void)p_onTap:(id)arg1;
- (void)onDidTapAnnouncementCell:(const scoped_refptr_8a203b4c *)arg1;
- (void)onNotifySyncStateChanged:(_Bool)arg1;
- (void)onNotifyUpdateDraftAnnouncement:(const list_a34e2a5e *)arg1;
- (void)onNotifyDeleteDraftAnnouncement:(const list_a34e2a5e *)arg1;
- (void)onNotifyAddDraftAnnouncement:(const list_a34e2a5e *)arg1;
- (void)onNotifyUpdateAnnouncement:(const list_a34e2a5e *)arg1;
- (void)onNotifyDeleteAnnouncement:(const list_a34e2a5e *)arg1;
- (void)onNotifyAddAnnouncement:(const list_a34e2a5e *)arg1;
- (void)onRightNavigationItemClick;
- (void)onDidSegmentSelectChange:(id)arg1;
- (void)searchBarDidClickCustomCancelButton:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)p_presentWriteAnnouncementViewController:(const scoped_refptr_8a203b4c *)arg1;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)fetchDraftAnnounceList;
- (void)fetchSentAnnounceList;
- (void)fetchReceivedAnnounceList;
- (void)viewWillLayoutSubviews;
- (void)initBottomView;
- (void)initSearch;
- (void)initContentTableViews;
- (void)initNavigationItems;
- (void)dealloc;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

