//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "WXApiManagerDelegate-Protocol.h"

@class MBProgressHUD, NSLayoutConstraint, NSString, UIButton, UIImageView, UIView;

@interface WWKNoTeamViewController : UIViewController <WXApiManagerDelegate>
{
    UIButton *_createTeamButton;
    UIView *_containerView;
    UIButton *_searchBtn;
    UIButton *_mobileLoginBtn;
    UIImageView *_arrow;
    MBProgressHUD *_bindWxHud;
    NSLayoutConstraint *positionYConstraint;
    id _context;
    NSLayoutConstraint *_heightConstraint;
}

@property(retain, nonatomic) NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint=_heightConstraint;
@property(nonatomic) __weak id context; // @synthesize context=_context;
- (void).cxx_destruct;
- (void)p_rightButtonClick;
- (void)p_setupSubviews;
- (void)p_initNavigation;
- (void)managerBindWxFinish;
- (void)managerEndLoginRequest;
- (void)managerBeginLoginRequest;
- (void)dealloc;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)applicationWillEnterForeground;
- (void)mobileLogin:(id)arg1;
- (void)searchCorp:(id)arg1;
- (void)createTeam:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

