//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "MailProxyObserverDelegate-Protocol.h"
#import "NotificationProxyObserverDelegate-Protocol.h"
#import "UIDocumentInteractionControllerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"
#import "WKNavigationDelegate-Protocol.h"
#import "WWKForwardingControllerDelegate-Protocol.h"
#import "WWKMessageDelegate-Protocol.h"
#import "WWKZoomImageViewDelegate-Protocol.h"

@class AVPlayerViewController, MPMoviePlayerViewController, NSLayoutConstraint, NSMutableArray, NSString, NSTimer, NSURL, UIActivityIndicatorView, UIButton, UIDocumentInteractionController, UIImage, UIImageView, UILabel, UIView, UIWebView, WEWCloudObjectEntry, WKWebView, WWFavoriteId, WWKFloatingTipView, WWKMessage, WWKMessageFile, WWKProgressIndicator, WWKZoomImageView;

@interface WWKPreviewDocumentController : UIViewController <UIDocumentInteractionControllerDelegate, UIWebViewDelegate, WKNavigationDelegate, UIGestureRecognizerDelegate, WWKForwardingControllerDelegate, NotificationProxyObserverDelegate, MailProxyObserverDelegate, WWKZoomImageViewDelegate, WWKMessageDelegate>
{
    NSURL *_pathURL;
    WWKMessageFile *_file;
    WWKMessage *_message;
    scoped_refptr_b418b350 _mail;
    int _attachmentIndex;
    struct scoped_ptr<NotificationProxyObserver, base::DefaultDeleter<NotificationProxyObserver>> _ftn_state_observer;
    struct scoped_ptr<MailSmartProxyObserver, base::DefaultDeleter<MailSmartProxyObserver>> _attachment_state_observer;
    NSMutableArray *_preview_files_need_delete;
    _Bool _auto_download_processed;
    UIImage *_nav_bar_image;
    _Bool _previewing;
    _Bool _viewAppeared;
    _Bool _showFavAction;
    _Bool _showShareInRightNavigation;
    _Bool _isCloudDisk;
    _Bool _isDownloadCauseByShareToWX;
    long long _fromChannel;
    WWFavoriteId *_favId;
    WEWCloudObjectEntry *_cloudObject;
    CDUnknownBlockType _goCmtBlk;
    UIImageView *_iconView;
    UILabel *_fileNameLabel;
    UILabel *_sizeLabel;
    UILabel *_fileDesLabel;
    UIButton *_actionButton;
    UILabel *_hintLabel;
    UIView *_downloadingView;
    UILabel *_downloadStateLabel;
    WWKProgressIndicator *_progressIndicator;
    UIActivityIndicatorView *_loadingIndicator;
    UIWebView *_uiWebView;
    WKWebView *_wkWebView;
    WWKZoomImageView *_zoomImageView;
    UIView *_blankView;
    AVPlayerViewController *_avPlayerController;
    MPMoviePlayerViewController *_mpPlayerController;
    UIDocumentInteractionController *_documentInteractionController;
    WWKFloatingTipView *_downloadTipView;
    WWKMessage *_persistWWKMessage;
    NSTimer *_mFakeProgressTimer;
    UIButton *_commentBtn;
    NSLayoutConstraint *_commandGap;
    NSLayoutConstraint *_commandWidth;
    UIView *_previewCommandView;
    UIButton *_previewCommandButton;
    UILabel *_previewCommandLabel;
}

@property(nonatomic) __weak UILabel *previewCommandLabel; // @synthesize previewCommandLabel=_previewCommandLabel;
@property(nonatomic) __weak UIButton *previewCommandButton; // @synthesize previewCommandButton=_previewCommandButton;
@property(nonatomic) __weak UIView *previewCommandView; // @synthesize previewCommandView=_previewCommandView;
@property(nonatomic) __weak NSLayoutConstraint *commandWidth; // @synthesize commandWidth=_commandWidth;
@property(nonatomic) __weak NSLayoutConstraint *commandGap; // @synthesize commandGap=_commandGap;
@property(nonatomic) __weak UIButton *commentBtn; // @synthesize commentBtn=_commentBtn;
@property(retain, nonatomic) NSTimer *mFakeProgressTimer; // @synthesize mFakeProgressTimer=_mFakeProgressTimer;
@property(nonatomic) _Bool isDownloadCauseByShareToWX; // @synthesize isDownloadCauseByShareToWX=_isDownloadCauseByShareToWX;
@property(retain, nonatomic) WWKMessage *persistWWKMessage; // @synthesize persistWWKMessage=_persistWWKMessage;
@property(retain, nonatomic) WWKFloatingTipView *downloadTipView; // @synthesize downloadTipView=_downloadTipView;
@property(retain, nonatomic) UIDocumentInteractionController *documentInteractionController; // @synthesize documentInteractionController=_documentInteractionController;
@property(retain, nonatomic) MPMoviePlayerViewController *mpPlayerController; // @synthesize mpPlayerController=_mpPlayerController;
@property(retain, nonatomic) AVPlayerViewController *avPlayerController; // @synthesize avPlayerController=_avPlayerController;
@property(retain, nonatomic) UIView *blankView; // @synthesize blankView=_blankView;
@property(retain, nonatomic) WWKZoomImageView *zoomImageView; // @synthesize zoomImageView=_zoomImageView;
@property(retain, nonatomic) WKWebView *wkWebView; // @synthesize wkWebView=_wkWebView;
@property(retain, nonatomic) UIWebView *uiWebView; // @synthesize uiWebView=_uiWebView;
@property(retain, nonatomic) UIActivityIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(retain, nonatomic) WWKProgressIndicator *progressIndicator; // @synthesize progressIndicator=_progressIndicator;
@property(retain, nonatomic) UILabel *downloadStateLabel; // @synthesize downloadStateLabel=_downloadStateLabel;
@property(retain, nonatomic) UIView *downloadingView; // @synthesize downloadingView=_downloadingView;
@property(retain, nonatomic) UILabel *hintLabel; // @synthesize hintLabel=_hintLabel;
@property(retain, nonatomic) UIButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) UILabel *fileDesLabel; // @synthesize fileDesLabel=_fileDesLabel;
@property(retain, nonatomic) UILabel *sizeLabel; // @synthesize sizeLabel=_sizeLabel;
@property(retain, nonatomic) UILabel *fileNameLabel; // @synthesize fileNameLabel=_fileNameLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(copy, nonatomic) CDUnknownBlockType goCmtBlk; // @synthesize goCmtBlk=_goCmtBlk;
@property(retain, nonatomic) WEWCloudObjectEntry *cloudObject; // @synthesize cloudObject=_cloudObject;
@property(nonatomic) _Bool isCloudDisk; // @synthesize isCloudDisk=_isCloudDisk;
@property(retain, nonatomic) WWFavoriteId *favId; // @synthesize favId=_favId;
@property(nonatomic) long long fromChannel; // @synthesize fromChannel=_fromChannel;
@property(nonatomic) _Bool showShareInRightNavigation; // @synthesize showShareInRightNavigation=_showShareInRightNavigation;
@property(nonatomic) _Bool showFavAction; // @synthesize showFavAction=_showFavAction;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)limitString:(id)arg1;
- (void)actionTextChanged:(id)arg1;
- (_Bool)alertViewShouldEnableFirstOtherButton:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)singleTouchInZoomingImageView:(id)arg1 location:(struct CGPoint)arg2;
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;
- (void)onPvMergeCallWillOpen:(id)arg1;
- (void)respondQueryRect:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)mail:(struct Mail *)arg1 didChangeAttachmentDownloadProgressAtIndex:(int)arg2;
- (void)mail:(struct Mail *)arg1 didChangeAttachmentDownloadStateAtIndex:(int)arg2;
- (void)onNotification:(int)arg1 source:(const struct NotificationSource *)arg2 details:(const struct NotificationDetails *)arg3;
- (void)messageDidUpdate:(id)arg1;
- (void)documentInteractionController:(id)arg1 didEndSendingToApplication:(id)arg2;
- (void)documentInteractionController:(id)arg1 willBeginSendingToApplication:(id)arg2;
- (void)actionButtonDidRelease:(id)arg1;
- (void)actionButtonDidPress:(id)arg1;
- (void)changeAction:(SEL)arg1 withTitle:(id)arg2;
- (long long)mailAttachmentByteSize:(const struct MailAttachment *)arg1;
- (id)fileFastPreviewLocalPath;
- (id)fileLocalPath;
- (id)fileName;
- (unsigned long long)fileSizeAtPath:(id)arg1;
- (_Bool)supportsPreview:(id)arg1;
- (_Bool)isLocalDocumentPrepared;
- (void)viewDidLongPress:(id)arg1;
- (void)downloadTipViewDidClick:(id)arg1;
- (void)goConversationByMessage;
- (void)moreOperationDidClick:(id)arg1;
- (void)interactionDidClick:(id)arg1;
- (void)stopDownloadDidClick:(id)arg1;
- (void)loadBlankView;
- (id)loadZoomImageView;
- (id)loadFileWebView;
- (void)doForwardTask:(id)arg1;
- (void)doForward;
- (_Bool)doInstantPreviewWithViewController:(id)arg1;
- (void)checkNeedShowCommentButton;
- (_Bool)doPreview;
- (void)doPause;
- (void)updateDownloadProgress:(unsigned long long)arg1;
- (unsigned long long)getFileDownloadSize2Show:(unsigned long long)arg1;
- (void)checkAndStartRealDownload;
- (void)updateP2pComplexFakeDownloadProgress;
- (void)doFakeDownloadForP2pComplex;
- (void)doDownload;
- (void)doShareToWeixin;
- (void)doDismiss;
- (void)checkFileState;
- (_Bool)checkFileP2PState;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillLayoutSubviews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)addFileP2PReport;
- (void)goComment;
- (void)viewDidLoad;
- (_Bool)isMessageIncoming;
- (_Bool)isFileP2pComplex;
- (_Bool)isFilePureP2P;
- (_Bool)isFileP2P;
- (void)stopFakeTimer;
- (void)dealloc;
- (id)initWithAttachment:(int)arg1 forMail:(scoped_refptr_b418b350)arg2;
- (id)initWithFile:(id)arg1 forMessage:(id)arg2;
- (id)initWithFile:(id)arg1;
- (id)initWithURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

