//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIScrollView;

@interface WWKPullRefreshView : UIView
{
    UIView *_centerYellowPoint;
    UIView *_leftRedPoint;
    UIView *_rightGreenPoint;
    _Bool _isRefreshing;
    _Bool _isEnabled;
    double _originalInsetTop;
    int _currentState;
    CDUnknownBlockType _pullToRefreshActionHandler;
    UIScrollView *_scrollView;
    NSArray *_pointsArray;
    long long _middlePointIndex;
}

@property(nonatomic) _Bool isEnabled; // @synthesize isEnabled=_isEnabled;
@property(nonatomic) long long middlePointIndex; // @synthesize middlePointIndex=_middlePointIndex;
@property(retain, nonatomic) NSArray *pointsArray; // @synthesize pointsArray=_pointsArray;
@property(nonatomic) int currentState; // @synthesize currentState=_currentState;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(copy, nonatomic) CDUnknownBlockType pullToRefreshActionHandler; // @synthesize pullToRefreshActionHandler=_pullToRefreshActionHandler;
- (void).cxx_destruct;
- (void)contentOffsetChanged:(float)arg1;
- (void)scrollViewDidEndDragging:(float)arg1;
- (void)scrollViewWillBeginDragging:(float)arg1;
- (void)setScrollViewContentInsetTop:(float)arg1;
- (void)doAnimation;
- (void)movePoints;
- (void)collectPoints;
- (void)preparePoints;
- (void)resetScrollViewContentInset;
- (void)resetPointsPosition;
- (void)layoutPoints;
- (id)pointMake:(id)arg1;
- (void)startAnimating;
- (void)reset;
- (void)endRefreshing;
- (void)beginRefreshing;
- (void)setRefreshing:(_Bool)arg1;
@property(readonly, nonatomic, getter=isRefreshing) _Bool refreshing;
- (id)initWithFrame:(struct CGRect)arg1;

@end

