//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UITextView, UIView;

@interface WWKRemindAddAlertNoteCellView : UITableViewCell
{
    UIView *topSeperatorLine_;
    UIView *bottomSeperatorLine_;
    UITextView *_contentTextView;
}

@property(retain, nonatomic) UITextView *contentTextView; // @synthesize contentTextView=_contentTextView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

