//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ALAssetsLibrary, WWKAsset;

@interface WWKRecentPhotoAccesser : NSObject
{
    WWKAsset *lastTimeAsset_;
    ALAssetsLibrary *assetLibrary_;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)p_fetchRecentAssetios7:(CDUnknownBlockType)arg1;
- (id)p_fetchRecentAssetsBugqingwei;
- (id)recentPhotoAsset;
- (void)recentPhotoAssetios7WithBlock:(CDUnknownBlockType)arg1;

@end

