//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "WWKReceiptDetailContentGridViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, UITapGestureRecognizer, WWKMessage;
@protocol WWKReceiptDetailContentCellViewDelegate;

@interface WWKReceiptDetailContentCellView : UITableViewCell <WWKReceiptDetailContentGridViewDelegate>
{
    NSMutableArray *avatarViewArray_;
    UITapGestureRecognizer *tapGP_;
    NSArray *ids_;
    WWKMessage *message_;
    long long _hiddenCount;
    id <WWKReceiptDetailContentCellViewDelegate> _delegate;
}

+ (double)cellHeight;
+ (long long)gridCountEachCell;
@property(nonatomic) __weak id <WWKReceiptDetailContentCellViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long hiddenCount; // @synthesize hiddenCount=_hiddenCount;
- (void).cxx_destruct;
- (void)wwkReceiptDetailContentGridViewDidTapUserID:(unsigned long long)arg1;
- (void)setUserIDs:(id)arg1 andMessage:(id)arg2;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

