//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "WWKForwardingControllerDelegate-Protocol.h"

@class NSString, UIActivityIndicatorView, UIImageView, UILabel, UIView, WWKAvatarImageView;

@interface WWKRoomQRCodeController : UIViewController <WWKForwardingControllerDelegate>
{
    scoped_refptr_fd92d7bf _conversation;
    scoped_refptr_e1f85e48 _user;
    UIView *_coverView;
    UIImageView *_qrcodeImageView;
    WWKAvatarImageView *_avatarImageView;
    UILabel *_titleLabel;
    UILabel *_tipLabel;
    UIActivityIndicatorView *_activityView;
    UILabel *_qrcodeTipLabel;
}

@property(retain, nonatomic) UILabel *qrcodeTipLabel; // @synthesize qrcodeTipLabel=_qrcodeTipLabel;
@property(retain, nonatomic) UIActivityIndicatorView *activityView; // @synthesize activityView=_activityView;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) WWKAvatarImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) UIImageView *qrcodeImageView; // @synthesize qrcodeImageView=_qrcodeImageView;
@property(retain, nonatomic) UIView *coverView; // @synthesize coverView=_coverView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (id)createShareCardImage;
- (void)shareToWeixin;
- (void)rightNavigationItemPressed;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithConversation:(scoped_refptr_fd92d7bf)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

