//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UILabel, WWKMessage;
@protocol WWKReceiptDetailContentGridViewDelegate;

@interface WWKReceiptDetailContentGridView : UIView
{
    UIButton *avatarButton_;
    UILabel *nameLabel_;
    unsigned long long _userID;
    WWKMessage *_message;
    id <WWKReceiptDetailContentGridViewDelegate> _delegate;
}

+ (double)gridViewHeight;
@property(nonatomic) __weak id <WWKReceiptDetailContentGridViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WWKMessage *message; // @synthesize message=_message;
@property(nonatomic) unsigned long long userID; // @synthesize userID=_userID;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)p_onClickedAvatar:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

