//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UILabel, UIView;

@interface WWKRemindAddAlertTimeSelectionCellView : UITableViewCell
{
    UIView *topSeperatorLine_;
    UIView *bottomSeperatorLine_;
    UILabel *_actualTimeLabel;
    UILabel *_timeWordLabel;
}

@property(retain, nonatomic) UILabel *timeWordLabel; // @synthesize timeWordLabel=_timeWordLabel;
@property(retain, nonatomic) UILabel *actualTimeLabel; // @synthesize actualTimeLabel=_actualTimeLabel;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

