//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKUIWebViewController.h"

@class NSURLRequest;

@interface WWKRedEnvWebViewViewController : WWKUIWebViewController
{
    NSURLRequest *_lastLoadUrlReq;
}

@property(retain, nonatomic) NSURLRequest *lastLoadUrlReq; // @synthesize lastLoadUrlReq=_lastLoadUrlReq;
- (void).cxx_destruct;
- (void)p_actionCollect;
- (void)p_actionCopyLink;
- (void)p_actionOpenWithSafari;
- (void)shareToWechatDidClick;
- (void)forwardDidClick;
- (void)loadURL:(id)arg1 withUserId:(long long)arg2;
- (void)didOpenRedEvnSuc:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithURL:(id)arg1;

@end

