//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKWebViewController.h"

#import "MailProxyObserverDelegate-Protocol.h"
#import "UIDocumentInteractionControllerDelegate-Protocol.h"
#import "WWKForwardingControllerDelegate-Protocol.h"
#import "WWKMessageDelegate-Protocol.h"

@class NSLayoutConstraint, NSString, UIActivityIndicatorView, UIBarButtonItem, UIButton, UIDocumentInteractionController, UILabel, UIToolbar, UIView, WWKContainerView, WWKLoadMoreFooterView, WWKMessage, WWKMessageMail, WWKReadmailContactButton;

@interface WWKReadmailViewController : WWKWebViewController <UIDocumentInteractionControllerDelegate, WWKForwardingControllerDelegate, MailProxyObserverDelegate, WWKMessageDelegate>
{
    scoped_refptr_b418b350 _mail;
    NSString *_mailID;
    WWKMessageMail *_mailMessage;
    WWKMessage *_originalMailMessage;
    struct scoped_ptr<mail::model::pb::NewMailTips, base::DefaultDeleter<mail::model::pb::NewMailTips>> _newMailTips;
    struct scoped_ptr<MailSmartProxyObserver, base::DefaultDeleter<MailSmartProxyObserver>> _observer;
    _Bool _showsDetails;
    CDUnknownBlockType _downloadAttachCompletion;
    UILabel *_subjectLabel;
    WWKReadmailContactButton *_senderButton;
    UIButton *_attachmentButton;
    UIButton *_detailButton;
    WWKContainerView *_detailContainerView;
    NSLayoutConstraint *_collapseDetailConstraint;
    UIView *_showPicHintView;
    UIView *_showConversationView;
    NSLayoutConstraint *_showConversationConstraint;
    UIButton *_showPicHintButton;
    NSLayoutConstraint *_collapseShowPicHintConstraint;
    UIView *_backgroundView;
    UIToolbar *_toolbar;
    UIBarButtonItem *_replyToolbarItem;
    UIBarButtonItem *_forwardToolbarItem;
    UIBarButtonItem *_deleteToolbarItem;
    UIBarButtonItem *_moreToolbarItem;
    NSLayoutConstraint *_subjectLabelTopConstraint;
    UIView *_attachmentContainerView;
    UIActivityIndicatorView *_indicator;
    UIDocumentInteractionController *_documentInteractionController;
    WWKLoadMoreFooterView *_loadMoreFooter;
}

+ (id)expireDisplayString:(id)arg1 usingRedFont:(_Bool *)arg2;
+ (_Bool)isUsingPrivateProtocol;
+ (id)readmailViewControllerWithNewMailTips:(struct NewMailTips *)arg1;
+ (id)readmailViewControllerWithMailMessage:(id)arg1;
+ (id)readmailViewControllerWithMailID:(id)arg1;
+ (id)readmailViewControllerWithMail:(scoped_refptr_b418b350)arg1;
@property(retain, nonatomic) WWKLoadMoreFooterView *loadMoreFooter; // @synthesize loadMoreFooter=_loadMoreFooter;
@property(retain, nonatomic) UIDocumentInteractionController *documentInteractionController; // @synthesize documentInteractionController=_documentInteractionController;
@property(retain, nonatomic) UIActivityIndicatorView *indicator; // @synthesize indicator=_indicator;
@property(retain, nonatomic) UIView *attachmentContainerView; // @synthesize attachmentContainerView=_attachmentContainerView;
@property(nonatomic) __weak NSLayoutConstraint *subjectLabelTopConstraint; // @synthesize subjectLabelTopConstraint=_subjectLabelTopConstraint;
@property(retain, nonatomic) UIBarButtonItem *moreToolbarItem; // @synthesize moreToolbarItem=_moreToolbarItem;
@property(retain, nonatomic) UIBarButtonItem *deleteToolbarItem; // @synthesize deleteToolbarItem=_deleteToolbarItem;
@property(retain, nonatomic) UIBarButtonItem *forwardToolbarItem; // @synthesize forwardToolbarItem=_forwardToolbarItem;
@property(retain, nonatomic) UIBarButtonItem *replyToolbarItem; // @synthesize replyToolbarItem=_replyToolbarItem;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) NSLayoutConstraint *collapseShowPicHintConstraint; // @synthesize collapseShowPicHintConstraint=_collapseShowPicHintConstraint;
@property(retain, nonatomic) UIButton *showPicHintButton; // @synthesize showPicHintButton=_showPicHintButton;
@property(retain, nonatomic) NSLayoutConstraint *showConversationConstraint; // @synthesize showConversationConstraint=_showConversationConstraint;
@property(retain, nonatomic) UIView *showConversationView; // @synthesize showConversationView=_showConversationView;
@property(retain, nonatomic) UIView *showPicHintView; // @synthesize showPicHintView=_showPicHintView;
@property(retain, nonatomic) NSLayoutConstraint *collapseDetailConstraint; // @synthesize collapseDetailConstraint=_collapseDetailConstraint;
@property(retain, nonatomic) WWKContainerView *detailContainerView; // @synthesize detailContainerView=_detailContainerView;
@property(retain, nonatomic) UIButton *detailButton; // @synthesize detailButton=_detailButton;
@property(retain, nonatomic) UIButton *attachmentButton; // @synthesize attachmentButton=_attachmentButton;
@property(retain, nonatomic) WWKReadmailContactButton *senderButton; // @synthesize senderButton=_senderButton;
@property(retain, nonatomic) UILabel *subjectLabel; // @synthesize subjectLabel=_subjectLabel;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)mail:(struct Mail *)arg1 didChangeAttachmentDownloadStateAtIndex:(int)arg2;
- (void)forwardingController:(id)arg1 presetUserListAtIndex:(unsigned long long)arg2 fetchUserCompletion:(CDUnknownBlockType)arg3 noUserCompletion:(CDUnknownBlockType)arg4;
- (id)titlesForPresetUserListInForwardingController:(id)arg1;
- (id)defaultConversationNameInForwardingController:(id)arg1;
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;
- (void)documentInteractionController:(id)arg1 didEndSendingToApplication:(id)arg2;
- (void)documentInteractionController:(id)arg1 willBeginSendingToApplication:(id)arg2;
- (void)webView:(id)arg1 handleJavascriptAction:(id)arg2;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (_Bool)verifyBizuin;
- (_Bool)verifyBizmail;
- (_Bool)canReplyAll;
- (basic_string_a490aa4c)_getAttachReadablePath:(int)arg1;
- (_Bool)_weixinDownloadedAttach:(int)arg1;
- (void)weixinAttach:(int)arg1;
- (_Bool)_openDownloadedAttach:(int)arg1;
- (void)openAttach:(int)arg1;
- (_Bool)_mailFtnAttach:(int)arg1;
- (_Bool)_mailDownloadedAttach:(int)arg1;
- (void)mailAttach:(int)arg1;
- (_Bool)_sendFtnAttach:(int)arg1;
- (_Bool)_sendDownloadedAttach:(int)arg1;
- (void)sendAttach:(int)arg1;
- (_Bool)_favoriteFtnAttach:(int)arg1;
- (_Bool)_favoriteDownloadedAttach:(int)arg1;
- (void)favoriteAttach:(int)arg1;
- (_Bool)isConvMail;
- (void)_transferAttach:(int)arg1 completion:(CDUnknownBlockType)arg2;
- (CDUnknownBlockType)_downloadAttachWithoutUI:(int)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_downloadAttach:(int)arg1 completion:(CDUnknownBlockType)arg2;
- (CDUnknownBlockType)_downloadContentOrOneAttachCompletion:(CDUnknownBlockType)arg1;
- (void)_downloadAllAttachCompletion:(CDUnknownBlockType)arg1;
- (void)_downloadContentAndAllAttachCompletion:(CDUnknownBlockType)arg1;
- (void)loadFullMail;
- (void)showPicDidClick:(id)arg1;
- (id)exportAsPDF;
- (void)contentImageDidLongPress:(id)arg1;
- (void)contentLinkDidLongPress:(id)arg1;
- (void)attachmentInfoDidClick:(id)arg1;
- (void)attachmentViewDidClick:(id)arg1;
- (void)toggleDetails:(id)arg1;
- (void)contactDidClick:(id)arg1;
- (void)attachmentButtonDidClick:(id)arg1;
- (void)performForwardingWithoutUndownloadedAttachments:(_Bool)arg1;
- (void)performForwardingCheckingUndownloadedContents;
- (void)blackListDidClick:(id)arg1;
- (void)deleteDidClick:(id)arg1;
- (void)forwardDidClick:(id)arg1;
- (void)forwardMenuDidClick:(id)arg1;
- (void)composeMenuDidClick:(id)arg1;
- (void)markAsUnread:(id)arg1;
- (void)replyDidClick:(id)arg1;
- (void)exportToWeixin:(id)arg1;
- (void)exportToRecipients:(id)arg1;
- (void)exportToConversation:(id)arg1;
- (void)exportDidClick:(id)arg1;
- (void)moreDidClick:(id)arg1;
- (void)viewDidLayoutSubviews;
- (id)wrapHtmlTables:(id)arg1;
- (id)buildReadmailConfiguration;
- (void)fillDataWithPlaceholder;
- (void)fillDataWithNewMailTips:(struct NewMailTips *)arg1;
- (id)replaceCid:(id)arg1;
- (_Bool)updateShowLoadImages;
- (_Bool)showsLoadImages;
- (_Bool)canLoadImages;
- (void)fillDetailDataWithMailInfo:(struct Mail *)arg1;
- (void)fillDataWithMailInfo:(struct Mail *)arg1;
- (void)fillData;
- (void)updateNavigationItems;
- (void)dynamicFontSizeDidChange:(id)arg1;
- (void)loadMail;
- (id)errorTemplateHtmlWithTips:(id)arg1 buttonTitle:(id)arg2;
- (void)showConversationViewDidClick:(id)arg1;
- (void)messageDidUpdate:(id)arg1;
- (void)positionHeaderAndFooter;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (_Bool)hasConversation;
- (id)initWithNewMailTips:(struct NewMailTips *)arg1;
- (id)initWithMailMessage:(id)arg1;
- (id)initWithMailID:(id)arg1;
- (id)initWithMail:(scoped_refptr_b418b350)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

