//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, UILabel;

@interface WWKSearchCorpNameCell : UITableViewCell
{
    UILabel *_nameLabel;
    NSString *_nameString;
    NSString *_currentEditNameString;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)initSubViews;
- (void)setLabelAtribute;
- (void)setEditNameString:(id)arg1;
- (void)setNameString:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

