//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, NSString, UIButton, UIColor, UIScrollView;
@protocol WWKSelectContactsBottomBarDelegate;

@interface WWKSelectContactsBottomBar : UIView
{
    vector_89e6321f user_list;
    vector_a024b487 department_list;
    set_96bcc9b8 userIdSet;
    UIButton *_sureButton;
    NSString *_sureString;
    UIColor *_sureTextColor;
    id <WWKSelectContactsBottomBarDelegate> _delegate;
    unsigned long long _srcType;
    NSMutableArray *_heads;
    UIScrollView *_headsScrollView;
    UIView *_topSeparator;
}

@property(retain, nonatomic) UIView *topSeparator; // @synthesize topSeparator=_topSeparator;
@property(retain, nonatomic) UIScrollView *headsScrollView; // @synthesize headsScrollView=_headsScrollView;
@property(retain, nonatomic) NSMutableArray *heads; // @synthesize heads=_heads;
@property(nonatomic) unsigned long long srcType; // @synthesize srcType=_srcType;
@property(nonatomic) __weak id <WWKSelectContactsBottomBarDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIColor *sureTextColor; // @synthesize sureTextColor=_sureTextColor;
@property(retain, nonatomic) NSString *sureString; // @synthesize sureString=_sureString;
@property(retain, nonatomic) UIButton *sureButton; // @synthesize sureButton=_sureButton;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setSureButtonTitleHeadNumber:(id)arg1;
- (void)setUserInteractionEnabled:(_Bool)arg1;
- (void)sureButtonClicked:(id)arg1;
- (void)departmentHeadClicked:(id)arg1;
- (void)userHeadClicked:(id)arg1;
- (_Bool)isDepartmentHasSelected:(scoped_refptr_85c18dd7)arg1;
- (_Bool)isUserHasSelected:(scoped_refptr_e1f85e48)arg1;
- (void)clearSelectedUserList;
- (vector_a024b487)selectedDepartmentList;
- (const set_96bcc9b8 *)selectedUserIdSet;
- (const vector_89e6321f *)selectedUserList;
- (void)layoutDepartmentHeadsOnScrollViewWithAnimated;
- (void)layoutHeadsOnScrollViewWithAnimated;
- (void)removeDepartment:(scoped_refptr_85c18dd7)arg1;
- (void)removeMemberWithUser:(scoped_refptr_e1f85e48)arg1;
- (void)removeMemberWithUsers:(const set_96bcc9b8 *)arg1;
- (void)addDepartment:(scoped_refptr_85c18dd7)arg1;
- (long long)countByAddUsers:(const set_96bcc9b8 *)arg1;
- (void)addMemberWithUsers:(vector_89e6321f)arg1;
- (void)addMemberWithUser:(scoped_refptr_e1f85e48)arg1;
- (id)init;

@end

