//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class WWKSelectContactsBottomBar;

@protocol WWKSelectContactsBottomBarDelegate <NSObject>

@optional
- (void)selectContactsBottomBar:(WWKSelectContactsBottomBar *)arg1 didClickSureButtonWithDepartmentList:(vector_a024b487)arg2 andUserList:(vector_89e6321f)arg3;
- (void)selectContactsBottomBar:(WWKSelectContactsBottomBar *)arg1 didRemoveUserList:(const set_96bcc9b8 *)arg2;
- (void)selectContactsBottomBar:(WWKSelectContactsBottomBar *)arg1 didClickSureButtonWithDepartmentList:(vector_a024b487)arg2;
- (void)selectContactsBottomBar:(WWKSelectContactsBottomBar *)arg1 didRemoveDepartment:(scoped_refptr_85c18dd7)arg2;
- (void)selectContactsBottomBar:(WWKSelectContactsBottomBar *)arg1 didClickSureButtonWithUserList:(vector_89e6321f)arg2;
- (void)selectContactsBottomBar:(WWKSelectContactsBottomBar *)arg1 didRemoveUser:(scoped_refptr_e1f85e48)arg2;
@end

