//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface WWKSelectedView : UIView
{
    scoped_refptr_85c18dd7 _department;
    UILabel *_titleLabel;
    UIImageView *_iconView;
}

@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setAssociatedDepartment:(scoped_refptr_85c18dd7)arg1;
- (scoped_refptr_85c18dd7)associatedDepartment;
- (id)initWithFrame:(struct CGRect)arg1;

@end

