//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKBaseLayeredCardViewController.h"

@class WWKSendApplicationCard;

@interface WWKShareCardViewController : WWKBaseLayeredCardViewController
{
    WWKSendApplicationCard *_myCardView;
    CDUnknownBlockType _handler;
}

@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(retain, nonatomic) WWKSendApplicationCard *myCardView; // @synthesize myCardView=_myCardView;
- (void).cxx_destruct;
- (double)scrollDismissThreshold;
- (double)scrollFadeThreshold;
- (void)privacyFinishLayout;
- (void)privacyIdleLayout;
- (void)idleLayout4;
- (void)idleLayout3;
- (void)idleLayout2;
- (void)initialLayout;
- (void)cancelDidClick:(id)arg1;
- (void)sendDidClick:(id)arg1;
- (void)privacyDidChange:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithHandler:(CDUnknownBlockType)arg1;

@end

