//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class MSWeakTimer, NSString, UIButton, UIImageView, UILabel;

@interface WWKSendClaimMailSuccessController : UIViewController
{
    int _timeCounter;
    MSWeakTimer *_timer;
    NSString *_emailAddress;
    UIImageView *_iconView;
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    UIButton *_bottomButton;
}

@property(retain, nonatomic) UIButton *bottomButton; // @synthesize bottomButton=_bottomButton;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) NSString *emailAddress; // @synthesize emailAddress=_emailAddress;
- (void).cxx_destruct;
- (void)timeCountAfterButtonPressed:(id)arg1;
- (void)onBottomButtonClick:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;

@end

