//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextFieldDelegate-Protocol.h"
#import "WWKBackspaceTextFieldDelegate-Protocol.h"

@class NSMutableArray, NSString, UIImageView, UIScrollView, WWKBackspaceTextField;
@protocol WWKSelectContactsBarDelegate;

@interface WWKSelectContactsBar : UIView <UITextFieldDelegate, WWKBackspaceTextFieldDelegate>
{
    vector_fcf831c7 user_list;
    NSString *_lastSearchText;
    _Bool _didAddMemberAnimated;
    id <WWKSelectContactsBarDelegate> _delegate;
    NSMutableArray *_heads;
    UIScrollView *_membersScrollView;
    WWKBackspaceTextField *_searchTextField;
    UIImageView *_searchIcon;
}

@property(retain, nonatomic) UIImageView *searchIcon; // @synthesize searchIcon=_searchIcon;
@property(retain, nonatomic) WWKBackspaceTextField *searchTextField; // @synthesize searchTextField=_searchTextField;
@property(retain, nonatomic) UIScrollView *membersScrollView; // @synthesize membersScrollView=_membersScrollView;
@property(retain, nonatomic) NSMutableArray *heads; // @synthesize heads=_heads;
@property(nonatomic) __weak id <WWKSelectContactsBarDelegate> delegate; // @synthesize delegate=_delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)textFieldDidClickBackspace:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)textFieldDidChangeText:(id)arg1;
- (_Bool)isUserHasSelected:(struct UserOrDepartment)arg1;
- (vector_fcf831c7)selectedUserList;
- (void)removeMemberWithUser:(struct UserOrDepartment)arg1;
- (void)addMemberWithUser:(struct UserOrDepartment)arg1;
- (void)clearSearchText;
- (void)userHeadClicked:(id)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

