//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, UIImageView, UILabel;

@interface WWKSendClaimMailAppintController : UIViewController
{
    NSString *_claimName;
    UIImageView *_iconView;
    UILabel *_nameLabel;
    UILabel *_tipsLabel;
}

- (void).cxx_destruct;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)setClaimName:(id)arg1;

@end

