//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class WWKSendClaimMailFooter, WWKSendClaimMailHeader;

@interface WWKSendClaimMailController : UITableViewController
{
    WWKSendClaimMailFooter *_footerView;
    WWKSendClaimMailHeader *_headerView;
    _Bool _hideHeader;
}

@property(nonatomic) _Bool hideHeader; // @synthesize hideHeader=_hideHeader;
- (void).cxx_destruct;
- (Class)p_cellClass;
- (void)getMail:(id)arg1 cell:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onTap:(id)arg1;
- (void)viewDidLoad;

@end

