//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface WWKSendClaimMailHeader : UIView
{
    UILabel *_titleLabel;
    UIImageView *_iconView1;
    UIImageView *_iconView2;
    UIImageView *_iconView3;
    UILabel *_tipsLabel1;
    UILabel *_tipsSubLabel1;
    UILabel *_linkLabel;
    UILabel *_tipsLabel2;
    UILabel *_tipsSubLabel2;
    UILabel *_tipsLabel3;
    UILabel *_tipsSubLabel3;
    UIView *_separatorView;
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)p_layoutSubViewsWithWidth:(double)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)linkLabelTap;
- (void)initSubViews;
- (id)init;

@end

