//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@interface WWKSendClaimMailCell : UITableViewCell
{
}

- (void)setButtonLoading:(_Bool)arg1;
- (void)setButtonEnable:(_Bool)arg1;
- (void)setError:(id)arg1;
- (void)setEmailAddress:(id)arg1;
- (id)getEmailAddress;

@end

