//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITabBarController.h>

#import "NotificationProxyObserverDelegate-Protocol.h"
#import "UITabBarControllerDelegate-Protocol.h"
#import "WWKMainViewController-Protocol.h"
#import "WWKURLRoutable-Protocol.h"
#import "WWKWelcomeViewControllerDelegate-Protocol.h"

@class NSMutableArray, NSString, UIToolbar, UIWindow;

@interface WWKTabBarController : UITabBarController <WWKWelcomeViewControllerDelegate, UITabBarControllerDelegate, NotificationProxyObserverDelegate, WWKURLRoutable, WWKMainViewController>
{
    UIWindow *_enterWindow;
    UIToolbar *_blurredView;
    struct scoped_ptr<NotificationProxyObserver, base::DefaultDeleter<NotificationProxyObserver>> _notification_observer;
    struct unique_ptr<ClosureThrottling<std::__1::basic_string<char>>, std::__1::default_delete<ClosureThrottling<std::__1::basic_string<char>>>> _throttling_ptr;
    NSMutableArray *_badgeLabels;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)performRoute:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)p_perform;
- (void)onEnterButtonClicked;
- (void)showVerfEnterWindow;
- (void)showEnterWindowWithAnimate:(_Bool)arg1;
- (long long)selectTabItemIndexWithType:(long long)arg1;
- (id)navigationControllerWithType:(long long)arg1;
- (id)navigationControllerWithIndex:(long long)arg1;
- (_Bool)isValidPushRootController;
- (long long)tabBarCount;
- (void)selectTabbarControllerIndex:(long long)arg1 andResetPushToViewController:(id)arg2 animated:(_Bool)arg3;
- (void)selectTabbarControllerIndex:(long long)arg1 andResetPushToViewController:(id)arg2;
- (void)selectMainControllerType:(long long)arg1 andResetPushToViewController:(id)arg2 animated:(_Bool)arg3;
- (void)selectMainControllerIndex:(long long)arg1 andResetPushToViewController:(id)arg2 animated:(_Bool)arg3;
- (void)tabBar:(id)arg1 didSelectItem:(id)arg2;
- (void)p_setUpTabBar;
- (void)p_setUpBadgeViews;
- (void)onNotification:(int)arg1 source:(const struct NotificationSource *)arg2 details:(const struct NotificationDetails *)arg3;
- (void)selfHelpCorpChange;
- (void)fontDidChange;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)setBadgeValue:(id)arg1 forType:(long long)arg2;
- (void)dealloc;
- (void)viewDidLoad;
- (id)meNavigation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

