//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WWKTeamUIManager : NSObject
{
    struct CorpBriefInfo _enteringCorpInfo;
    unsigned long long _old_vid;
    int _currentLoginType;
}

+ (id)sharedManager;
@property(nonatomic) int currentLoginType; // @synthesize currentLoginType=_currentLoginType;
- (id).cxx_construct;
- (void).cxx_destruct;
- (long long)pendingCorpCount;
- (long long)myCorpCount;
- (void)p_onLoginFinish;
- (id)p_englishNameWithEmail:(id)arg1;
- (void)p_checkToken:(id)arg1 withName:(id)arg2;
- (void)p_showTextFieldAlertViewWithUserName:(id)arg1 checkAgain:(_Bool)arg2;
- (void)p_showAlertViewWithString:(id)arg1;
- (void)searchCorpFinish:(vector_4c3fbd75)arg1 context:(id)arg2;
- (void)enterCorp:(unsigned long long)arg1;
- (void)enterCorp:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)corpNavigationByKickout:(_Bool)arg1;
- (void)corpNavigationByKickout:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;

@end

