//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel, WWKAvatarImageView, WWkNameCoverClickView;
@protocol WWKMeInfoHeaderDelegate;

@interface WWKUserInfoHeader : UIView
{
    UIView *_containerView;
    UILabel *_corpNameLabel;
    UILabel *_nameLabel;
    UILabel *_subNameLabel;
    UILabel *_jobLabel;
    WWKAvatarImageView *_avatarView;
    UIImageView *_genderView;
    UIImageView *_starContactView;
    UIImageView *_realNameStatusView;
    UIView *_corpNameCoverClickView;
    WWkNameCoverClickView *_nameCoverClickView;
    UIImageView *_turnOverImageView;
    UIView *_waterMakeContainerView;
    UILabel *_positonLabel;
    scoped_refptr_e1f85e48 _user;
    _Bool _isInDepartment;
    id <WWKMeInfoHeaderDelegate> _delegate;
}

@property(nonatomic) __weak id <WWKMeInfoHeaderDelegate> delegate; // @synthesize delegate=_delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setInDepartment:(_Bool)arg1;
- (void)avatarDidTap:(id)arg1;
- (id)contextMenuItems;
- (void)menuControllerWillHide:(id)arg1;
- (void)onnameClicked;
- (void)onCorpNameClicked;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)layoutContentWithWidth:(double)arg1;
- (void)layoutSubviews;
- (void)setUser:(const scoped_refptr_e1f85e48 *)arg1 withSuitableDepartmentID:(unsigned long long)arg2;
- (void)initSubviews;
- (id)init;

@end

