//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WWKModifyCorpNameEditCellDelegate-Protocol.h"
#import "WWKModifyCorpWorkCardCellDelegate-Protocol.h"

@class NSMutableArray, NSString, UIActivityIndicatorView, UIButton, UIImage, UITableView, UIView, WWKCorpEditItem, WWKSearchCorpNameEditView;
@protocol WWKUpdateVirtualCorpInfoDelegate;

@interface WWKUpdateVirtualCorpInfoController : UIViewController <WWKModifyCorpNameEditCellDelegate, UITableViewDelegate, UITableViewDataSource, WWKModifyCorpWorkCardCellDelegate>
{
    NSMutableArray *_dataSource;
    NSMutableArray *_searchDataSource;
    struct CorpBriefInfo _corpInfo;
    UIButton *_commitButton;
    UITableView *_searchTableView;
    WWKSearchCorpNameEditView *_editView;
    UIView *_editViewHeader;
    UIImage *_image;
    NSString *_imageUrl;
    _Bool _beginLoading;
    UIActivityIndicatorView *_indicatorView;
    WWKCorpEditItem *_editingItem;
    double _keyboardHeight;
    _Bool _isCamera;
    id <WWKUpdateVirtualCorpInfoDelegate> _delegage;
    UITableView *_tableView;
}

@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <WWKUpdateVirtualCorpInfoDelegate> delegage; // @synthesize delegage=_delegage;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onDeleteImage;
- (void)onAddImage:(id)arg1 isCamera:(_Bool)arg2;
- (void)editChange:(id)arg1 text:(id)arg2;
- (void)editComplete:(id)arg1 text:(id)arg2;
- (void)onTextFieldDidBeginEdit:(id)arg1 withCell:(id)arg2;
- (void)onTextFieldDidChange:(id)arg1 withCell:(id)arg2;
- (double)headerViewHeight;
- (double)footerViewHeight;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)p_setButtonEnable:(_Bool)arg1;
- (void)p_setButtonLoading:(_Bool)arg1;
- (void)p_showAlertString:(id)arg1;
- (id)editViewHeader;
- (id)editView;
- (id)searchTableView;
- (void)commitCorpBriefName:(id)arg1 fullName:(id)arg2 cardUrl:(id)arg3;
- (void)onButtonClicked;
- (void)DoUpdateVirtualCorpName;
- (void)initSearchDataWithItem:(id)arg1;
- (void)initData;
- (void)p_updateButton;
- (void)setCorpInfo:(struct CorpBriefInfo *)arg1;
- (void)onKeybordShow:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

