//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, NSTimerProxy, UIButton, UILabel, UIScrollView, UITextField, UIView;
@protocol WWKVerificationViewControllerDelegate;

@interface WWKVerificationViewController : UIViewController
{
    NSTimerProxy *_timer;
    long long _second;
    NSString *_loginUserName;
    id <WWKVerificationViewControllerDelegate> _delegate;
    UILabel *_titleLabel;
    UITextField *_phoneNumField;
    UITextField *_codeField;
    UIButton *_codeButton;
    UIButton *_nextButton;
    UIView *_phoneNumSeparator;
    UIView *_codeSeparator;
    UIScrollView *_scrollView;
}

@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UIView *codeSeparator; // @synthesize codeSeparator=_codeSeparator;
@property(retain, nonatomic) UIView *phoneNumSeparator; // @synthesize phoneNumSeparator=_phoneNumSeparator;
@property(retain, nonatomic) UIButton *nextButton; // @synthesize nextButton=_nextButton;
@property(retain, nonatomic) UIButton *codeButton; // @synthesize codeButton=_codeButton;
@property(retain, nonatomic) UITextField *codeField; // @synthesize codeField=_codeField;
@property(retain, nonatomic) UITextField *phoneNumField; // @synthesize phoneNumField=_phoneNumField;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <WWKVerificationViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)p_checkToken:(id)arg1;
- (void)p_showTextFieldAlertViewWithUserName:(id)arg1 checkAgain:(_Bool)arg2;
- (void)p_showAlertViewWithString:(id)arg1;
- (void)p_setCodeButtonEnable:(_Bool)arg1;
- (void)p_setCodeButtonTitle:(id)arg1;
- (_Bool)p_isCodeButtonValidate;
- (_Bool)p_isNextButtonValidate;
- (void)p_updateTitle;
- (void)p_resetTimer;
- (id)p_englishNameWithEmail:(id)arg1;
- (void)nextStep;
- (void)getCode;
- (void)p_onTextFieldDidChange:(id)arg1;
- (_Bool)p_onKeyboardDidDisappear;
- (_Bool)p_onKeyboardDidShow;
- (void)viewDidTap:(id)arg1;
- (void)dismiss;
- (void)viewWillLayoutSubviews;
- (void)initSubView;
- (void)dealloc;
- (void)viewDidLoad;

@end

