//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "WWKAssetGroupsControllerDelegate-Protocol.h"
#import "WWKVerifyCorpPreViewCardControllerDelegate-Protocol.h"

@class NSString, UIActivityIndicatorView, UIButton, UIImageView, UILabel;

@interface WWKVerifyCorpHeaderView : UIView <WWKAssetGroupsControllerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, WWKVerifyCorpPreViewCardControllerDelegate>
{
    NSString *_faceUrl;
    _Bool _beginLoading;
    _Bool _isCamera;
    UILabel *_titleLabel;
    UIImageView *_faceImageView;
    UIButton *_verifyButton;
    UILabel *_errorLabel;
    UIActivityIndicatorView *_indicatorView;
    UIButton *_faceTakePhoneButton;
}

@property(retain, nonatomic) UIButton *faceTakePhoneButton; // @synthesize faceTakePhoneButton=_faceTakePhoneButton;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) UILabel *errorLabel; // @synthesize errorLabel=_errorLabel;
@property(retain, nonatomic) UIButton *verifyButton; // @synthesize verifyButton=_verifyButton;
@property(retain, nonatomic) UIImageView *faceImageView; // @synthesize faceImageView=_faceImageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)didClickDeleteItemInController:(id)arg1;
- (void)didFinishPickPhotos:(id)arg1 isSendOriginalSize:(_Bool)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)p_updateButton;
- (void)onButtonClicked;
- (void)p_addImage;
- (void)onImageViewTap:(id)arg1;
- (void)onFaceTap:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (struct CGSize)layoutContentWithWidth:(double)arg1;
- (void)layoutSubviews;
- (void)setButtonLoading:(_Bool)arg1;
- (void)setButtonEnable:(_Bool)arg1;
- (void)setError:(id)arg1;
- (void)initSubviews;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

