//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, UIButton, UILabel;

@interface WWKVerifyMailViewController : UIViewController
{
    NSString *_mailAddress;
    id _context;
    long long _type;
    UIButton *_getVerifyCodeBtn;
    UILabel *_mail;
}

@property(nonatomic) __weak UILabel *mail; // @synthesize mail=_mail;
@property(nonatomic) __weak UIButton *getVerifyCodeBtn; // @synthesize getVerifyCodeBtn=_getVerifyCodeBtn;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) __weak id context; // @synthesize context=_context;
@property(retain, nonatomic) NSString *mailAddress; // @synthesize mailAddress=_mailAddress;
- (void).cxx_destruct;
- (void)getVerifyCode:(id)arg1;
- (void)viewDidLoad;

@end

