//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "FOXMonthCalendarViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WWKWorkLogCanlendarViewControllerDelegate-Protocol.h"
#import "WorkflowProxyObserverDelegate-Protocol.h"

@class NSString, UITableView, WWKCommonEmptyView, WWKWorkLogCanlendarViewController, WWKWorkLogListToolbarView;

@interface WWKWorkLogListViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, FOXMonthCalendarViewDelegate, WWKWorkLogCanlendarViewControllerDelegate, WorkflowProxyObserverDelegate>
{
    double _curDate;
    vector_fd724ca3 _journalEntryList;
    WWKWorkLogCanlendarViewController *_calendarViewController;
    struct WorkflowProxyObserver *_workflowObserver;
    WWKWorkLogListToolbarView *_toolBar;
    UITableView *_tableView;
    WWKCommonEmptyView *_emptyView;
}

@property(retain, nonatomic) WWKCommonEmptyView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) WWKWorkLogListToolbarView *toolBar; // @synthesize toolBar=_toolBar;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)updateUI:(_Bool)arg1;
- (void)doAfterFectchDataBack:(int)arg1 withList:(const vector_fd724ca3 *)arg2 withDatetime:(double)arg3;
- (void)loadData:(double)arg1;
- (void)removeCalendarView;
- (void)didMonthCalendarCancelSelected;
- (void)didMonthCalendarSelected:(long long)arg1 month:(long long)arg2 day:(long long)arg3;
- (void)OnJournalDetailDataChanged;
- (void)initCalendarView;
- (void)onClickSelectButton:(id)arg1;
- (void)onClickNextDayButton:(id)arg1;
- (void)onClickPreDayButton:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithDate:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

