//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, WWKAvatarImageView;

@interface WWKWorkLogListTableViewCell : UITableViewCell
{
    WWKAvatarImageView *_headImgView;
    UILabel *_titleLabel;
    UILabel *_timeLabel;
    UILabel *_detailLabel;
    UIImageView *_attacheIcon;
}

+ (double)cellHeightForContent:(id)arg1;
@property(retain, nonatomic) UIImageView *attacheIcon; // @synthesize attacheIcon=_attacheIcon;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) WWKAvatarImageView *headImgView; // @synthesize headImgView=_headImgView;
- (void).cxx_destruct;
- (id)detailLabelAttributedStringWithText:(id)arg1 includeImage:(_Bool)arg2;
- (void)initView;
- (void)configureCell:(unsigned long long)arg1 withCreatorInfoData:(const basic_string_a490aa4c *)arg2 timeString:(id)arg3 contentString:(id)arg4 isIncludeImage:(_Bool)arg5;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

