//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WWKWebViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"
#import "WKNavigationDelegate-Protocol.h"
#import "WKScriptMessageHandler-Protocol.h"
#import "WKUIDelegate-Protocol.h"
#import "WWKForwardingControllerDelegate-Protocol.h"
#import "WWKScrollActionSheetDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, UIBarButtonItem, UIImageView, UIScreenEdgePanGestureRecognizer, WWFavoriteId, WWKLoadFailedView, WWKLoadingView, WWKPullBackgroundView, WWKScrollActionSheet, WWKWebBrowserHistory, WWKWebBrowserTitleView, WWKWebViewProgressView;

@interface WWKWebBrowserController : WWKWebViewController <WWKScrollActionSheetDelegate, WWKForwardingControllerDelegate, UITableViewDataSource, UITableViewDelegate, WKUIDelegate, WKNavigationDelegate, WKScriptMessageHandler, UIWebViewDelegate, UIGestureRecognizerDelegate>
{
    NSString *_initUrl;
    NSMutableArray *_actionSheetRow1;
    NSMutableArray *_actionSheetRow2;
    WWKScrollActionSheet *_scrollActionSheet;
    NSString *_currentOpenUrl;
    NSString *_forwardMessageSayMore;
    _Bool _isLoadSuccess;
    _Bool _isBack;
    NSArray *_rightBarButtonItems;
    UIBarButtonItem *_rightBarButtonItem;
    double _translateX;
    long long _loadingCount;
    long long _uiBackCount;
    _Bool _isShowCloseButton;
    WWKWebViewProgressView *_progressView;
    UIImageView *_screenSnotImageView;
    WWKWebBrowserHistory *_webViewHistory;
    WWKLoadFailedView *_loadFailedView;
    WWKLoadingView *_loadingView;
    scoped_refptr_c1fa851d _model_message;
    _Bool _showAuthLoading;
    _Bool _disablesWeworkScheme;
    _Bool _backIsClose;
    _Bool _hideRightmenu;
    _Bool _showPullBackgroundTitle;
    _Bool _showEnterConvMenuItem;
    WWKPullBackgroundView *_pullBackgroundView;
    long long _fromChannel;
    WWFavoriteId *_favId;
    WWKWebBrowserTitleView *_titleView;
    NSString *_forceTitle;
    NSString *_subtitle;
    NSArray *_leftBarButtonItems;
    unsigned long long _thisAppID;
    UIScreenEdgePanGestureRecognizer *_panGesture;
}

@property(retain, nonatomic) UIScreenEdgePanGestureRecognizer *panGesture; // @synthesize panGesture=_panGesture;
@property(nonatomic) _Bool showEnterConvMenuItem; // @synthesize showEnterConvMenuItem=_showEnterConvMenuItem;
@property(nonatomic) unsigned long long thisAppID; // @synthesize thisAppID=_thisAppID;
@property(retain, nonatomic) NSArray *leftBarButtonItems; // @synthesize leftBarButtonItems=_leftBarButtonItems;
@property(nonatomic) _Bool showPullBackgroundTitle; // @synthesize showPullBackgroundTitle=_showPullBackgroundTitle;
@property(copy, nonatomic) NSString *currentOpenUrl; // @synthesize currentOpenUrl=_currentOpenUrl;
@property(nonatomic) _Bool hideRightmenu; // @synthesize hideRightmenu=_hideRightmenu;
@property(nonatomic) _Bool backIsClose; // @synthesize backIsClose=_backIsClose;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *forceTitle; // @synthesize forceTitle=_forceTitle;
@property(retain, nonatomic) WWKWebBrowserTitleView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) WWFavoriteId *favId; // @synthesize favId=_favId;
@property(nonatomic) long long fromChannel; // @synthesize fromChannel=_fromChannel;
@property(nonatomic) _Bool disablesWeworkScheme; // @synthesize disablesWeworkScheme=_disablesWeworkScheme;
@property(nonatomic) _Bool showAuthLoading; // @synthesize showAuthLoading=_showAuthLoading;
@property(retain, nonatomic) WWKPullBackgroundView *pullBackgroundView; // @synthesize pullBackgroundView=_pullBackgroundView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)forceToOrientation:(long long)arg1;
- (void)forceToOrientation2:(long long)arg1;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (id)getBarButtonItemWithInterfaceOrientation;
- (void)onClickFailView;
- (void)p_hideLoadFailedView;
- (void)p_showLoadFailedView:(id)arg1;
- (void)showLoadFailedView:(id)arg1 errorImage:(id)arg2 enableAction:(_Bool)arg3;
- (void)p_hideLoadingView;
- (void)p_showLoadingView;
- (void)p_updateCurrentOpenUrl;
- (void)p_removeSwipeGesture;
- (void)p_addSwipeGesture;
- (void)p_goBackWithIsNeedUpdateWebViewHistory:(_Bool)arg1;
- (void)goBack;
- (void)onReturn;
- (void)onClose;
- (void)updateNavigationBarRightItem;
- (void)setRightBarButtonItem:(id)arg1;
- (void)setRightBarButtonItems:(id)arg1;
- (id)initialURL;
- (void)clearBrowserHistory;
- (void)p_dismissViewController;
- (void)p_updateNavigationBarRightItem;
- (void)p_updateNavigationLeftBarItems;
- (void)p_updateNavigationTitle;
- (void)p_updateSnapshotWithURL:(id)arg1;
- (void)p_checkHistoryWithRequest:(id)arg1;
- (void)p_handlePan:(id)arg1;
- (void)p_checkSwipeGesture;
- (void)p_finishLoadRequst;
- (void)p_startLoadRequst;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)webView:(id)arg1 enableGL:(_Bool)arg2;
- (void)applicationDidEnterBackground;
- (void)applicationWillEnterForeground;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (_Bool)webViewShouldStartLoadWithRequest:(id)arg1 navigationType:(long long)arg2;
- (void)stopLoading;
- (void)startLoading;
- (void)changeWebViewFontSize;
- (id)navigationTitle;
- (void)reload;
- (void)loadRequest:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (scoped_refptr_c1fa851d *)getUrlModelMsg;
- (void)setLinkModelMsg:(scoped_refptr_c1fa851d *)arg1;
- (void)dealloc;
- (id)init;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)forwardingMessage:(scoped_refptr_c1fa851d)arg1 ToConversation:(scoped_refptr_fd92d7bf)arg2 isSuccess:(_Bool)arg3;
- (struct LinkMessage)p_createLinkMessage;
- (void)scrollActionSheet:(id)arg1 didSelecteItem:(id)arg2;
- (id)defaultWebViewUrl;
- (id)defaultWebViewTitle;
- (id)defaultWebViewDescription;
- (id)defaultWebViewIconUrl;
- (void)p_showToastWithTips:(id)arg1;
- (void)p_actionEvaluate;
- (void)p_actionReload;
- (void)p_actionChangeFont;
- (void)p_actionCopyLink;
- (void)p_actionEnterConv;
- (void)p_actionCollect;
- (void)p_actionCancelCollect;
- (void)p_actionSendMail;
- (void)p_actionOpenWithSafari;
- (void)forwardDidClick;
- (void)shareToWechatDidClick;
- (id)str_actionEvaluate;
- (id)str_actionReload;
- (id)str_actionChangeFont;
- (id)str_actionCopyLink;
- (id)str_actionEnterConv;
- (id)str_actionCancelCollect;
- (id)str_actionCollect;
- (id)str_actionSendMail;
- (id)str_actionOpenWithSafari;
- (id)str_actionShareToWexin;
- (id)str_actionForward;
- (_Bool)showsMenuAction:(id)arg1;
- (void)p_addActionItemTitle:(id)arg1 andIcon:(id)arg2 toRowArray:(id)arg3;
- (void)p_setupRow2;
- (void)p_setupRow1;
- (void)moreOperationDidClick:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

