//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class NSMutableArray, UIImage, UILabel;
@protocol WWKWaitVerifyCorpControllerDelegate;

@interface WWKWaitVerifyCorpController : UITableViewController
{
    struct CorpBriefInfo _corpInfo;
    NSMutableArray *_dataSource;
    UILabel *_applyTimeLabel;
    _Bool _isFrontImageDownloading;
    id <WWKWaitVerifyCorpControllerDelegate> _delegate;
    unsigned long long _verifyType;
    UIImage *_idFrontImage;
}

@property(nonatomic) _Bool isFrontImageDownloading; // @synthesize isFrontImageDownloading=_isFrontImageDownloading;
@property(retain, nonatomic) UIImage *idFrontImage; // @synthesize idFrontImage=_idFrontImage;
@property(nonatomic) unsigned long long verifyType; // @synthesize verifyType=_verifyType;
@property(nonatomic) __weak id <WWKWaitVerifyCorpControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)waterMarkImage:(id)arg1 withText:(id)arg2;
- (void)p_cancelApply;
- (void)p_EnsureRefuse;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setCorpInfo:(struct CorpBriefInfo)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)initData;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

@end

