//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WWKWorkLogDataHelper : NSObject
{
}

+ (_Bool)isAdminEggOpen;
+ (void)adminEggSetOpen:(_Bool)arg1;
+ (void)cleanGuideBannerAndAlsoSetMemory:(_Bool)arg1;
+ (_Bool)shouldShowGuideBanner;
+ (void)DoTestJournalModify:(_Bool)arg1;
+ (void)DoTestJournalReporter;
+ (void)DoTestJournalSummary;
+ (void)DoTestJournalDetail;
+ (void)DoTestSubitJournal;
+ (id)getTextContentFromJournalEntry:(struct JournalEntry *)arg1;
+ (struct JournalEntryContent)makeJournalEntryTextContent:(id)arg1;
+ (id)worklogDetailContentWith:(const struct JournalEntry *)arg1;
+ (void)createWorklogShareMsgWithJournalEntry:(struct JournalEntry)arg1 completed:(CDUnknownBlockType)arg2;
+ (id)getReportNameText:(const scoped_refptr_8a36260b *)arg1 isAllName:(_Bool)arg2;
+ (id)getTitleForLogType:(int)arg1;
+ (_Bool)isWorklogAppMsg:(struct Message *)arg1;
+ (_Bool)isWorklogShareMsg:(struct Message *)arg1;
+ (_Bool)isNetWorkOK;
+ (id)journalCreatorHeadUrlFromClientDataString:(const basic_string_a490aa4c *)arg1;
+ (id)journalCreatorNameFromClientDataString:(const basic_string_a490aa4c *)arg1;
+ (struct SubmitJournalReq)convertJournalEntry2SubmitReq:(struct JournalEntry)arg1 opType:(int)arg2;

@end

