//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIButton, UIImageView, UILabel, UIView;
@protocol WWKWelcomeViewControllerDelegate;

@interface WWKWelcomeViewController : UIViewController
{
    scoped_refptr_e1f85e48 _user;
    struct Profile *current_profile_;
    id <WWKWelcomeViewControllerDelegate> _delegate;
    UIImageView *_avatar;
    UIView *_userInfoBackgound;
    UILabel *_name;
    UILabel *_job;
    UILabel *_department;
    UIButton *_enterButton;
    UILabel *_nameLabel;
    UILabel *_jobLabel;
}

@property(retain, nonatomic) UILabel *jobLabel; // @synthesize jobLabel=_jobLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak UIButton *enterButton; // @synthesize enterButton=_enterButton;
@property(nonatomic) __weak UILabel *department; // @synthesize department=_department;
@property(nonatomic) __weak UILabel *job; // @synthesize job=_job;
@property(nonatomic) __weak UILabel *name; // @synthesize name=_name;
@property(nonatomic) __weak UIView *userInfoBackgound; // @synthesize userInfoBackgound=_userInfoBackgound;
@property(nonatomic) __weak UIImageView *avatar; // @synthesize avatar=_avatar;
@property(nonatomic) __weak id <WWKWelcomeViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)viewWillLayoutSubviews;
- (void)setData;
- (void)enterButtonClicked:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

@end

