//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSTimer, WWMarkupLineStyle;
@protocol WWMarkupViewDelegate;

@interface WWMarkupView : UIView
{
    _Bool _mHasMouseDown;
    WWMarkupLineStyle *_linstyle;
    NSTimer *_timer;
    double _lastMouseDrag;
    _Bool _isSelfShare;
    _Bool _isInEditState;
    id <WWMarkupViewDelegate> _mDelegate;
    UIView *_weakNxtResponder;
}

@property(nonatomic) _Bool isInEditState; // @synthesize isInEditState=_isInEditState;
@property(nonatomic) __weak UIView *weakNxtResponder; // @synthesize weakNxtResponder=_weakNxtResponder;
@property(nonatomic) _Bool isSelfShare; // @synthesize isSelfShare=_isSelfShare;
@property(nonatomic) __weak id <WWMarkupViewDelegate> mDelegate; // @synthesize mDelegate=_mDelegate;
- (void).cxx_destruct;
- (void)onTimer;
- (void)resetTimer;
- (void)markupLineStyleAttributeChanged;
- (void)drawRect:(struct CGRect)arg1;
- (void)p_touchUP:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)resetNewLine;
- (void)setMarkupStyleObject:(id)arg1;
- (void)setElementAlpha:(double)arg1;
- (void)p_doInit;
- (id)initWithFrame:(struct CGRect)arg1;

@end

