//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, UIView;

@interface WWRedEnvRankingListCell : UITableViewCell
{
    unsigned int _mRank;
    UIView *_mDivideLineView;
    UIView *_mDivideTopLineView;
    scoped_refptr_af14610e _mRankItem;
    UILabel *_mSeqLabel;
    UILabel *_mNameLabel;
    UILabel *_mRedEnvCountLabel;
    UIImageView *_mUserImageView;
}

+ (double)getCellHeight;
@property(retain, nonatomic) UIImageView *mUserImageView; // @synthesize mUserImageView=_mUserImageView;
@property(retain, nonatomic) UILabel *mRedEnvCountLabel; // @synthesize mRedEnvCountLabel=_mRedEnvCountLabel;
@property(retain, nonatomic) UILabel *mNameLabel; // @synthesize mNameLabel=_mNameLabel;
@property(retain, nonatomic) UILabel *mSeqLabel; // @synthesize mSeqLabel=_mSeqLabel;
@property(nonatomic) unsigned int mRank; // @synthesize mRank=_mRank;
@property(nonatomic) scoped_refptr_af14610e mRankItem; // @synthesize mRankItem=_mRankItem;
@property(retain, nonatomic) UIView *mDivideTopLineView; // @synthesize mDivideTopLineView=_mDivideTopLineView;
@property(retain, nonatomic) UIView *mDivideLineView; // @synthesize mDivideLineView=_mDivideLineView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateUI;
- (void)updateRankingItem:(struct RedEnvelopesRecvRankItem *)arg1 rank:(unsigned int)arg2;
- (void)initUI;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

