//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSDictionary, NSMapTable;

@interface WWRedEnvAnimateView : UIView
{
    NSDictionary *_viewsByName;
    NSMapTable *_completionBlocksByAnimation;
}

@property(retain, nonatomic) NSMapTable *completionBlocksByAnimation; // @synthesize completionBlocksByAnimation=_completionBlocksByAnimation;
@property(retain, nonatomic) NSDictionary *viewsByName; // @synthesize viewsByName=_viewsByName;
- (void).cxx_destruct;
- (void)removeAllAnimations;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)removeWWRedEnvAnimationViewAnimation;
- (void)addWWRedEnvAnimationViewAnimationWithBeginTime:(double)arg1 andFillMode:(id)arg2 andRemoveOnCompletion:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)addWWRedEnvAnimationViewAnimationAndRemoveOnCompletion:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addWWRedEnvAnimationViewAnimationAndRemoveOnCompletion:(_Bool)arg1;
- (void)addWWRedEnvAnimationViewAnimationWithCompletion:(CDUnknownBlockType)arg1;
- (void)addWWRedEnvAnimationViewAnimation;
- (void)setupHierarchy;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

