//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIActionSheetDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UISearchDisplayDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WWKAssetGroupsControllerDelegate-Protocol.h"
#import "WWYunPanCreateTeamFolderDelegate-Protocol.h"
#import "WWYunPanListFolderCellDelegate-Protocol.h"
#import "WWYunPanMemberEditFinishDelegate-Protocol.h"
#import "WeDrawViewControllerDelegate-Protocol.h"

@class NSMutableArray, NSString, UIAlertView, UIBarButtonItem, UISearchDisplayController, UITableView, UIToolbar, WEWCloudObjectEntry, WWFavoriteEmptyView, WWKCloudDiskAssistMessage, WWKMessage, WWKSearchBar, WWYunPanListFolderCell;

@interface WWYunPanListViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UIActionSheetDelegate, WWYunPanMemberEditFinishDelegate, WWKAssetGroupsControllerDelegate, UIImagePickerControllerDelegate, WWYunPanListFolderCellDelegate, UISearchDisplayDelegate, UISearchBarDelegate, WeDrawViewControllerDelegate, WWYunPanCreateTeamFolderDelegate>
{
    _Bool _topFolder;
    _Bool _isSearch;
    _Bool _viewAppearNeedUpdateData;
    WEWCloudObjectEntry *_objectEntry;
    NSString *_currentObejctId;
    WWKMessage *_saveMessage;
    CDUnknownBlockType _saveToCloudDiskblock;
    UITableView *_mTableview;
    WWKSearchBar *_mSearchBar;
    UISearchDisplayController *_mSearchDispCtlr;
    WWFavoriteEmptyView *_mEmptyView;
    NSMutableArray *_mDataList;
    NSMutableArray *_mSearchDataList;
    NSString *_realCurrentObjectId;
    UIAlertView *_createFolderAlertView;
    UIAlertView *_renameFolderAlertView;
    UIAlertView *_renameSelfAlertView;
    long long _renameIndex;
    NSString *_selectedObjectId;
    unsigned long long _listType;
    WWYunPanListFolderCell *_tempCell;
    UIToolbar *_mToolbar;
    UIBarButtonItem *_choseDone;
    WWKCloudDiskAssistMessage *_forwardMessage;
    WEWCloudObjectEntry *_preSearchTopEntry;
}

@property(retain, nonatomic) WEWCloudObjectEntry *preSearchTopEntry; // @synthesize preSearchTopEntry=_preSearchTopEntry;
@property(retain, nonatomic) WWKCloudDiskAssistMessage *forwardMessage; // @synthesize forwardMessage=_forwardMessage;
@property(nonatomic) _Bool viewAppearNeedUpdateData; // @synthesize viewAppearNeedUpdateData=_viewAppearNeedUpdateData;
@property(nonatomic) _Bool isSearch; // @synthesize isSearch=_isSearch;
@property(retain, nonatomic) UIBarButtonItem *choseDone; // @synthesize choseDone=_choseDone;
@property(retain, nonatomic) UIToolbar *mToolbar; // @synthesize mToolbar=_mToolbar;
@property(retain, nonatomic) WWYunPanListFolderCell *tempCell; // @synthesize tempCell=_tempCell;
@property(nonatomic) unsigned long long listType; // @synthesize listType=_listType;
@property(copy, nonatomic) NSString *selectedObjectId; // @synthesize selectedObjectId=_selectedObjectId;
@property(nonatomic) long long renameIndex; // @synthesize renameIndex=_renameIndex;
@property(retain, nonatomic) UIAlertView *renameSelfAlertView; // @synthesize renameSelfAlertView=_renameSelfAlertView;
@property(retain, nonatomic) UIAlertView *renameFolderAlertView; // @synthesize renameFolderAlertView=_renameFolderAlertView;
@property(retain, nonatomic) UIAlertView *createFolderAlertView; // @synthesize createFolderAlertView=_createFolderAlertView;
@property(copy, nonatomic) NSString *realCurrentObjectId; // @synthesize realCurrentObjectId=_realCurrentObjectId;
@property(retain, nonatomic) NSMutableArray *mSearchDataList; // @synthesize mSearchDataList=_mSearchDataList;
@property(retain, nonatomic) NSMutableArray *mDataList; // @synthesize mDataList=_mDataList;
@property(retain, nonatomic) WWFavoriteEmptyView *mEmptyView; // @synthesize mEmptyView=_mEmptyView;
@property(retain, nonatomic) UISearchDisplayController *mSearchDispCtlr; // @synthesize mSearchDispCtlr=_mSearchDispCtlr;
@property(retain, nonatomic) WWKSearchBar *mSearchBar; // @synthesize mSearchBar=_mSearchBar;
@property(retain, nonatomic) UITableView *mTableview; // @synthesize mTableview=_mTableview;
@property(copy, nonatomic) CDUnknownBlockType saveToCloudDiskblock; // @synthesize saveToCloudDiskblock=_saveToCloudDiskblock;
@property(retain, nonatomic) WWKMessage *saveMessage; // @synthesize saveMessage=_saveMessage;
@property(copy, nonatomic) NSString *currentObejctId; // @synthesize currentObejctId=_currentObejctId;
@property(retain, nonatomic) WEWCloudObjectEntry *objectEntry; // @synthesize objectEntry=_objectEntry;
@property(nonatomic) _Bool topFolder; // @synthesize topFolder=_topFolder;
- (void).cxx_destruct;
- (void)ww_settingCurrentCorpDir;
- (void)ww_settingAndForward:(id)arg1 currentEntry:(id)arg2;
- (void)doError:(id)arg1 toObjId:(id)arg2 forceRefresh:(_Bool)arg3;
- (void)doForwardFolder:(id)arg1;
- (void)forward;
- (double)p_sendImageJPEGQuality;
- (void)onUploadFileToFolder;
- (void)onMemberEidtFinish:(id)arg1 withCellDatas:(vector_5df9642c *)arg2;
- (void)sendImg:(id)arg1;
- (void)didFinishPickPhotos:(id)arg1 isSendOriginalSize:(_Bool)arg2;
- (void)ww_afterUploadFileRefresh;
- (void)ww_uploadFile:(id)arg1;
- (void)ww_uploadVideo:(id)arg1;
- (void)ww_uploadImage:(id)arg1 orImageData:(id)arg2 isHD:(_Bool)arg3;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)p_tryToConvertMovToMP4AndThenSend:(id)arg1 withPicker:(id)arg2;
- (void)handleCloudDiskProgressOnFinishNotification:(id)arg1;
- (void)handleCloudDiskProgressOnChangeNotification:(id)arg1;
- (void)handleCloudDiskProgressOnStartNotification:(id)arg1;
- (id)limitString:(id)arg1;
- (void)actionTextChanged:(id)arg1;
- (_Bool)alertViewShouldEnableFirstOtherButton:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)ww_renameSelf;
- (void)ww_deleteSelf;
- (void)ww_createNormalFolder:(id)arg1;
- (void)ww_renameFolderAlertShow;
- (void)ww_renameSelfAlertShow;
- (void)ww_createNormalFolderAlertShow;
- (void)ww_removeIndexToUI:(unsigned long long)arg1;
- (void)ww_deleteIndex:(unsigned long long)arg1;
- (id)ww_findConfigureByObjectId:(id)arg1;
- (void)ww_transferToFavorite:(unsigned long long)arg1;
- (void)ww_renameIndex:(unsigned long long)arg1;
- (void)ww_browMember;
- (void)ww_uploadSheet;
- (void)ww_showHud:(id)arg1 isSuccess:(_Bool)arg2;
- (void)showAlertViewWithAVAuthorizationStatus:(long long)arg1;
- (void)ww_openCamera;
- (void)ww_updateNavigationItem;
- (id)ww_getIndexPathForObjectConfig:(id)arg1;
- (id)ww_getTableview;
- (id)ww_getDataSourceByTableView:(id)arg1;
- (id)ww_getDataSource;
- (_Bool)ww_isTopFolder:(id)arg1;
- (void)ww_updateSearchCellInfo:(id)arg1 withConfigure:(id)arg2 isSearchResultTableView:(_Bool)arg3 isFolder:(_Bool)arg4;
- (void)onCreateTeamFolderName:(id)arg1 addObjects:(id)arg2 withSelfId:(unsigned long long)arg3;
- (void)handleCloudFileUpdatedComeNotification:(id)arg1;
- (id)cloudDiskObjectsToModelConfigure:(id)arg1;
- (void)loadFolderId:(id)arg1 fromNet:(_Bool)arg2 withSortType:(unsigned long long)arg3;
- (void)loadFolderId:(id)arg1 fromNet:(_Bool)arg2 sortType:(unsigned long long)arg3 withFinishBlock:(CDUnknownBlockType)arg4;
- (void)actionMore:(id)arg1;
- (void)actionCreateNewFolder:(id)arg1;
- (void)actionReturn;
- (void)folderCell:(id)arg1 selected:(_Bool)arg2 atIndexpath:(id)arg3;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (_Bool)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 editActionsForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)setupNavigationItem;
- (void)onDismissBtnClick:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)showEmptyUI;
- (void)showLoadingUI;
- (void)initUI;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)initData;
- (void)dealloc;
- (void)unregistNotification;
- (void)registNotification;
- (id)initTop:(_Bool)arg1 type:(unsigned long long)arg2 forwardMessage:(id)arg3 withObjectId:(id)arg4;
- (id)initTop:(_Bool)arg1 type:(unsigned long long)arg2 withObjectId:(id)arg3;
- (id)initTop:(_Bool)arg1 withObjectId:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

