//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, UIImageView, UILabel, UIProgressView, WWYunPanListFileCellConfig;

@interface WWYunPanListFileCell : UITableViewCell
{
    _Bool _uploading;
    _Bool _failed;
    _Bool _isSearchMode;
    double _uploadCurrentSize;
    NSString *_folderName;
    WWYunPanListFileCellConfig *_config;
    UILabel *_mCreatorLabel;
    UILabel *_mSizeLabel;
    UILabel *_mTimeLabel;
    UILabel *_mCommandLabel;
    UIProgressView *_mUploadProgressView;
    UILabel *_mUploadSizeLabel;
    UILabel *_mUploadStateLabel;
    UIImageView *_mUploadStateIcon;
}

@property(retain, nonatomic) UIImageView *mUploadStateIcon; // @synthesize mUploadStateIcon=_mUploadStateIcon;
@property(retain, nonatomic) UILabel *mUploadStateLabel; // @synthesize mUploadStateLabel=_mUploadStateLabel;
@property(retain, nonatomic) UILabel *mUploadSizeLabel; // @synthesize mUploadSizeLabel=_mUploadSizeLabel;
@property(retain, nonatomic) UIProgressView *mUploadProgressView; // @synthesize mUploadProgressView=_mUploadProgressView;
@property(retain, nonatomic) UILabel *mCommandLabel; // @synthesize mCommandLabel=_mCommandLabel;
@property(retain, nonatomic) UILabel *mTimeLabel; // @synthesize mTimeLabel=_mTimeLabel;
@property(retain, nonatomic) UILabel *mSizeLabel; // @synthesize mSizeLabel=_mSizeLabel;
@property(retain, nonatomic) UILabel *mCreatorLabel; // @synthesize mCreatorLabel=_mCreatorLabel;
@property(retain, nonatomic) WWYunPanListFileCellConfig *config; // @synthesize config=_config;
@property(nonatomic) _Bool isSearchMode; // @synthesize isSearchMode=_isSearchMode;
@property(retain, nonatomic) NSString *folderName; // @synthesize folderName=_folderName;
@property(nonatomic) double uploadCurrentSize; // @synthesize uploadCurrentSize=_uploadCurrentSize;
@property(nonatomic) _Bool failed; // @synthesize failed=_failed;
@property(nonatomic) _Bool uploading; // @synthesize uploading=_uploading;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)initUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

