//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton, UILabel, WWKInteractiveLabel, WWYunPanCommandConfig;
@protocol WWYunPanCommentCellDelegate;

@interface WWYunPanCommandCell : UITableViewCell
{
    WWYunPanCommandConfig *_config;
    id <WWYunPanCommentCellDelegate> _delegate;
    UILabel *_mFromUserLabel;
    UILabel *_mActionLabel;
    UILabel *_mToUserLabel;
    WWKInteractiveLabel *_mCommandLabel;
    UILabel *_mTimeLabel;
    UIButton *_mContainerView;
}

@property(retain, nonatomic) UIButton *mContainerView; // @synthesize mContainerView=_mContainerView;
@property(retain, nonatomic) UILabel *mTimeLabel; // @synthesize mTimeLabel=_mTimeLabel;
@property(retain, nonatomic) WWKInteractiveLabel *mCommandLabel; // @synthesize mCommandLabel=_mCommandLabel;
@property(retain, nonatomic) UILabel *mToUserLabel; // @synthesize mToUserLabel=_mToUserLabel;
@property(retain, nonatomic) UILabel *mActionLabel; // @synthesize mActionLabel=_mActionLabel;
@property(retain, nonatomic) UILabel *mFromUserLabel; // @synthesize mFromUserLabel=_mFromUserLabel;
@property(nonatomic) __weak id <WWYunPanCommentCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) WWYunPanCommandConfig *config; // @synthesize config=_config;
- (void).cxx_destruct;
- (void)onDidTap;
- (struct CGSize)layoutAndSizeToFit;
- (void)layoutSubviews;
- (void)setupUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

