//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WWKSelectContactsViewControllerDelegate-Protocol.h"
#import "WWYunPanMemberEditFinishDelegate-Protocol.h"
#import "WWYunPanPermissionControllerDelegate-Protocol.h"

@class NSMutableArray, NSString, UITableView, WEWCloudObjectAcl, WWKSelectContactsViewController;
@protocol WWYunPanMemberEditFinishDelegate;

@interface WWYunPanMemberListViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, WWYunPanPermissionControllerDelegate, WWKSelectContactsViewControllerDelegate, WWYunPanMemberEditFinishDelegate>
{
    vector_5df9642c _cellDatas;
    vector_5df9642c _mirroDatas;
    _Bool _isCreat;
    _Bool _isAdmin;
    _Bool _isAllowDeleteSelf;
    _Bool _needCallbackDataConverted;
    _Bool _hasModify;
    id <WWYunPanMemberEditFinishDelegate> _delegate;
    UITableView *_mTableview;
    NSMutableArray *_membersData;
    WEWCloudObjectAcl *_objectAcl;
    unsigned long long _current;
    WWYunPanMemberListViewController *_controller;
    WWKSelectContactsViewController *_selectContactController;
}

@property(retain, nonatomic) WWKSelectContactsViewController *selectContactController; // @synthesize selectContactController=_selectContactController;
@property(retain, nonatomic) WWYunPanMemberListViewController *controller; // @synthesize controller=_controller;
@property(nonatomic) _Bool hasModify; // @synthesize hasModify=_hasModify;
@property(nonatomic) unsigned long long current; // @synthesize current=_current;
@property(retain, nonatomic) WEWCloudObjectAcl *objectAcl; // @synthesize objectAcl=_objectAcl;
@property(retain, nonatomic) NSMutableArray *membersData; // @synthesize membersData=_membersData;
@property(retain, nonatomic) UITableView *mTableview; // @synthesize mTableview=_mTableview;
@property(nonatomic) _Bool needCallbackDataConverted; // @synthesize needCallbackDataConverted=_needCallbackDataConverted;
@property(nonatomic) _Bool isAllowDeleteSelf; // @synthesize isAllowDeleteSelf=_isAllowDeleteSelf;
@property(nonatomic) _Bool isAdmin; // @synthesize isAdmin=_isAdmin;
@property(nonatomic) _Bool isCreat; // @synthesize isCreat=_isCreat;
@property(nonatomic) __weak id <WWYunPanMemberEditFinishDelegate> delegate; // @synthesize delegate=_delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)permissionClickedWithType:(long long)arg1;
- (void)onDeleteOneMember:(struct cellData *)arg1;
- (void)onMemberEidtFinish:(id)arg1 withCellDatas:(vector_5df9642c *)arg2;
- (void)ww_gotoNextAfterSelectMember:(vector_89e6321f)arg1 withDepartmentList:(vector_a024b487)arg2 selectContactViewController:(id)arg3;
- (void)ww_deleteRow:(id)arg1;
- (_Bool)canSelectDepartmentInSelectContactsViewController:(id)arg1;
- (void)selectContactsViewController:(id)arg1 didConfirmToSelectContacts:(vector_89e6321f)arg2;
- (void)selectContactsViewController:(id)arg1 didConfirmToSelectContacts:(vector_89e6321f)arg2 andDepartments:(vector_a024b487)arg3;
- (id)titleForNumberExceedMax:(id)arg1;
- (long long)numberOfMaxSelectedContacts:(id)arg1;
- (_Bool)checkDiff;
- (void)actionFinishEdit;
- (void)actionDone;
- (void)actionLastStep;
- (void)addMember;
- (void)setTopCloudObjectAcl:(id)arg1;
- (id)ww_getAddObjects;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setUsersList:(vector_89e6321f)arg1 witDepartsList:(vector_a024b487)arg2;
- (void)dealloc;
- (void)viewDidLayoutSubviews;
- (_Bool)canPopViewController;
- (_Bool)shouldHoldBackButtonEvent;
- (void)initNavigationItem;
- (void)initUI;
- (void)setIsCreat:(_Bool)arg1 isAdmin:(_Bool)arg2 allowDeleteSelf:(_Bool)arg3;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initIsAdmin:(_Bool)arg1 isCreat:(_Bool)arg2 allowDeleteSelf:(_Bool)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

