//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UIButton, UIImageView, UILabel, UIProgressView, WWYunPanListFileCellConfig;

@interface WWYunPanFileDetailViewController : UIViewController
{
    WWYunPanListFileCellConfig *_fileConfig;
    UIImageView *_mTypeIconView;
    UILabel *_mTitleLabel;
    UILabel *_mStateLabel;
    UIButton *_mCommandButton;
    UIButton *_mDownloadButton;
    UIProgressView *_mProgressView;
    UIButton *_mCancleButton;
}

@property(retain, nonatomic) UIButton *mCancleButton; // @synthesize mCancleButton=_mCancleButton;
@property(retain, nonatomic) UIProgressView *mProgressView; // @synthesize mProgressView=_mProgressView;
@property(retain, nonatomic) UIButton *mDownloadButton; // @synthesize mDownloadButton=_mDownloadButton;
@property(retain, nonatomic) UIButton *mCommandButton; // @synthesize mCommandButton=_mCommandButton;
@property(retain, nonatomic) UILabel *mStateLabel; // @synthesize mStateLabel=_mStateLabel;
@property(retain, nonatomic) UILabel *mTitleLabel; // @synthesize mTitleLabel=_mTitleLabel;
@property(retain, nonatomic) UIImageView *mTypeIconView; // @synthesize mTypeIconView=_mTypeIconView;
@property(retain, nonatomic) WWYunPanListFileCellConfig *fileConfig; // @synthesize fileConfig=_fileConfig;
- (void).cxx_destruct;
- (void)handleCloudDiskProgressOnFinishNotification:(id)arg1;
- (void)handleCloudDiskProgressOnChangeNotification:(id)arg1;
- (void)handleCloudDiskProgressOnStartNotification:(id)arg1;
- (void)doDownload;
- (void)goComment;
- (void)dealloc;
- (void)viewDidLayoutSubviews;
- (void)initUI;
- (void)didReceiveMemoryWarning;
- (id)initWithCellConfig:(id)arg1;
- (void)registNotification;
- (void)viewDidLoad;

@end

