//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextViewDelegate-Protocol.h"

@class CALayer, NSString, UIButton, UILabel, UITextView;
@protocol WWYunPanCommandInputViewDelegate;

@interface WWYunPanCommandInputView : UIView <UITextViewDelegate>
{
    _Bool _active;
    _Bool _isEmotion;
    id <WWYunPanCommandInputViewDelegate> _delegate;
    UITextView *_mInputView;
    long long _mode;
    UILabel *_mPlaceHolderLabel;
    NSString *_placeholder;
    UIButton *_mSwitchButton;
    CALayer *_mBorderTop;
    CALayer *_mBorderBottom;
}

@property(nonatomic) _Bool isEmotion; // @synthesize isEmotion=_isEmotion;
@property(retain, nonatomic) CALayer *mBorderBottom; // @synthesize mBorderBottom=_mBorderBottom;
@property(retain, nonatomic) CALayer *mBorderTop; // @synthesize mBorderTop=_mBorderTop;
@property(retain, nonatomic) UIButton *mSwitchButton; // @synthesize mSwitchButton=_mSwitchButton;
@property(retain, nonatomic) NSString *placeholder; // @synthesize placeholder=_placeholder;
@property(retain, nonatomic) UILabel *mPlaceHolderLabel; // @synthesize mPlaceHolderLabel=_mPlaceHolderLabel;
@property(nonatomic) _Bool active; // @synthesize active=_active;
@property(nonatomic) long long mode; // @synthesize mode=_mode;
@property(retain, nonatomic) UITextView *mInputView; // @synthesize mInputView=_mInputView;
@property(nonatomic) __weak id <WWYunPanCommandInputViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)actionSwitchEmotion;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (void)setupUI;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

