//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITextFieldDelegate-Protocol.h"
#import "WWKSelectContactsViewControllerDelegate-Protocol.h"
#import "WWYunPanMemberEditFinishDelegate-Protocol.h"

@class CALayer, NSString, UIBarButtonItem, UITextField, WWKSelectContactsViewController, WWYunPanMemberListViewController;
@protocol WWYunPanCreateTeamFolderDelegate;

@interface WWYunPanEditNameViewController : UIViewController <UITextFieldDelegate, WWKSelectContactsViewControllerDelegate, WWYunPanMemberEditFinishDelegate>
{
    id <WWYunPanCreateTeamFolderDelegate> _delegate;
    UITextField *_mFolderNameField;
    CALayer *_mFolderFieldBorder;
    UIBarButtonItem *_mNextStepButton;
    WWYunPanMemberListViewController *_controller;
    WWKSelectContactsViewController *_selectContactController;
}

@property(retain, nonatomic) WWKSelectContactsViewController *selectContactController; // @synthesize selectContactController=_selectContactController;
@property(retain, nonatomic) WWYunPanMemberListViewController *controller; // @synthesize controller=_controller;
@property(retain, nonatomic) UIBarButtonItem *mNextStepButton; // @synthesize mNextStepButton=_mNextStepButton;
@property(retain, nonatomic) CALayer *mFolderFieldBorder; // @synthesize mFolderFieldBorder=_mFolderFieldBorder;
@property(retain, nonatomic) UITextField *mFolderNameField; // @synthesize mFolderNameField=_mFolderNameField;
@property(nonatomic) __weak id <WWYunPanCreateTeamFolderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onDeleteOneMember:(struct cellData *)arg1;
- (void)onMemberEidtFinish:(id)arg1 withCellDatas:(vector_5df9642c *)arg2;
- (_Bool)checkListHasSelf:(vector_89e6321f)arg1;
- (_Bool)canSelectDepartmentInSelectContactsViewController:(id)arg1;
- (id)getAddMembersFromUsers:(vector_89e6321f)arg1;
- (void)selectContactsViewController:(id)arg1 didConfirmToSelectContacts:(vector_89e6321f)arg2;
- (void)selectContactsViewController:(id)arg1 didConfirmToSelectContacts:(vector_89e6321f)arg2 andDepartments:(vector_a024b487)arg3;
- (id)titleForNumberExceedMax:(id)arg1;
- (long long)numberOfMaxSelectedContacts:(id)arg1;
- (id)limitString:(id)arg1;
- (void)actionTextChanged;
- (void)dealloc;
- (void)actionNextStep;
- (void)actionCancel;
- (void)initNavigationItem;
- (void)initUI;
- (void)viewDidAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

