//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface WXCCommonUtil : NSObject
{
}

+ (_Bool)isWXCOCRGoodCaseUploadImgEnable;
+ (_Bool)isWXCOCRUploadImgEnable;
+ (unsigned int)p_wxcFeature;
+ (id)wxcLogEncryptWithData:(id)arg1;
+ (id)aesEncryptForKey:(id)arg1 andData:(id)arg2;
+ (id)JSONStringFromDictionary:(id)arg1;
+ (id)DictionaryFromJSONData:(id)arg1;
+ (id)DictionaryFromJSONString:(id)arg1;
+ (id)imageWithView:(id)arg1;
+ (void)_wxc_logConvert:(id)arg1 level:(int)arg2 function:(id)arg3;
+ (id)generateUUIDString:(id)arg1;
+ (_Bool)isOtherCompanyWithVidFromCache:(unsigned long long)arg1;
+ (id)fetchImgUrlFromVid:(unsigned long long)arg1;
+ (void)fetchNameFromVid:(unsigned long long)arg1 asyncUpdateBlock:(CDUnknownBlockType)arg2;
+ (id)fetchNameFromVid:(unsigned long long)arg1;
+ (id)_rtxUserCellPhone;
+ (unsigned long long)fetchSelfVid;
+ (id)weworkSelfName;
+ (unsigned long long)currentRTXUserVid;
+ (id)_rtxUserRemoteID;
+ (id)userPhone;
+ (id)_wxc_deviceID;
+ (id)_rtx_deviceID;
+ (id)deviceID;
+ (id)currentOSVersion;
+ (id)deviceVersionReadableString;
+ (int)appBuildNumber;
+ (id)_stringByRemoveSpecialChar:(id)arg1;
+ (id)_nameFirstStringToDrawWithFullString:(id)arg1;
+ (struct CGRect)_centerStringInImage:(id)arg1 rect:(struct CGRect)arg2 font:(id)arg3;
+ (id)_headImageForString:(id)arg1 isSmaller:(_Bool)arg2;
+ (id)headImageForSmallerString:(id)arg1;
+ (id)headImageForString:(id)arg1;
+ (void)renderStatusBarStyleLight;
+ (void)renderStatusBarStyleDark;
+ (id)formatedTimeDuration:(unsigned long long)arg1;
+ (id)scaleToSizeByMin:(id)arg1 size:(struct CGSize)arg2;
+ (id)scaleToSize:(id)arg1 size:(struct CGSize)arg2;
+ (float)globalIosVersion;
+ (_Bool)compareArrayIsEqualWithOrigArray:(id)arg1 newArray:(id)arg2 origSortComparator:(CDUnknownBlockType)arg3 newSortComparator:(CDUnknownBlockType)arg4 arrayComparator:(CDUnknownBlockType)arg5 isStrict:(_Bool)arg6;
+ (_Bool)compareArrayIsEqualWithOrigArray:(id)arg1 newArray:(id)arg2 comparator:(CDUnknownBlockType)arg3 isStrict:(_Bool)arg4;
+ (void)compareArrayChangeWithOrigArray:(id)arg1 newArray:(id)arg2 outAddArray:(id)arg3 outRemoveArray:(id)arg4 outSameArray:(id)arg5 comparator:(CDUnknownBlockType)arg6;

@end

