//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class WXCDialLCDTextView;

@interface WXCDialLCDView : UIView
{
    WXCDialLCDTextView *_textView;
}

@property(retain, nonatomic) WXCDialLCDTextView *textView; // @synthesize textView=_textView;
- (void).cxx_destruct;
- (void)setDialDetailStr:(id)arg1;
- (void)setDialNumStr:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

